# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "bluetooth"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]

[dependencies]
actor-framework = { path = "../actor-framework" }
async-trait = "0.1.68"
bytes = "1.4.0"
device-actor = { path = "../device-actor" }
futures = "0.3.31"
hex = "0.4.3"
netsim-model = { path = "../model" }
netsim-packets = { path = "../packets" }
rootcanal = { path = "../rootcanal" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.32.0", default-features = false, features = [
  "rt",
  "time",
  "sync",
  "macros",
] }
tracing = "0.1"
zerocopy = "0.8.25"

[features]
default = []
test-utils = []

[dev-dependencies]
rootcanal = { path = "../rootcanal" }
netsim-testing = { path = "../testing", features = ["testing"] }
rand = "0.8.5"
tokio-stream = "0.1.17"
