# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "link-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
actor-framework = { path = "../actor-framework" }
async-trait = "0.1"
link-api = { path = "../link-api" }
netsim-model = { path = "../model" }
