// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

//! # Features Engine
//!
//! This module provides the runtime support for executing BDD-style tests in
//! Rust. It defines the `Features` struct, which holds registered steps, and
//! the logic to match regex patterns against test input.

use std::path::Path;

use gherkin::Feature;
use regex::Regex;

use crate::step::{AsyncStep, StepContext, World};

/// The Features engine responsible for managing and executing Gherkin steps.
///
/// It holds a registry of regex patterns mapped to `AsyncStep` implementations.
/// Steps are typically registered via code generated by `codegen`.
///
/// Type parameter `W` matches the "World" struct used to maintain state across
/// steps.
pub struct Features<W: ?Sized> {
    steps: Vec<(Regex, Box<dyn AsyncStep<W>>)>,
    before_hooks: Vec<Box<dyn AsyncStep<W>>>,
    after_hooks: Vec<Box<dyn AsyncStep<W>>>,
    tag_filter: Option<String>,
}

impl<W: ?Sized> Default for Features<W> {
    fn default() -> Self {
        Self::new()
    }
}

impl<W: ?Sized> Features<W> {
    pub fn new() -> Self {
        Self {
            steps: Vec::new(),
            before_hooks: Vec::new(),
            after_hooks: Vec::new(),
            tag_filter: None,
        }
    }

    /// Sets a tag filter. Only scenarios with this tag (or belonging to a
    /// feature with this tag) will be executed.
    pub fn filter(&mut self, tag: &str) {
        self.tag_filter = Some(tag.to_string());
    }

    /// Registers a step with a regex pattern.
    ///
    /// This method is primarily used by the generated code from `codegen`.
    pub fn register<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        let regex = Regex::new(pattern).expect("Invalid regex");
        self.steps.push((regex, Box::new(step)));
    }

    pub fn before<S>(&mut self, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.before_hooks.push(Box::new(step));
    }

    pub fn after<S>(&mut self, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.after_hooks.push(Box::new(step));
    }

    // Semantic aliases for Gherkin keywords
    pub fn given<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn when<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn then<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn and<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub async fn run(&self, text: &str, world: &mut W) {
        self.run_with_context(text, world, StepContext::default()).await;
    }

    pub async fn run_with_context(&self, text: &str, world: &mut W, ctx: StepContext) {
        // Dispatch to Global Registry
        for (regex, step) in &self.steps {
            if let Some(captures) = regex.captures(text) {
                // Enforce full match to prevent unintended partial matches
                let m = captures.get(0).unwrap();
                if m.start() == 0 && m.end() == text.len() {
                    let args: Vec<String> = captures
                        .iter()
                        .skip(1)
                        .map(|m| m.map_or("", |m| m.as_str()).to_string())
                        .collect();
                    step.call(world, args, ctx).await;
                    return;
                }
            }
        }

        panic!("No step definition found for: {}", text);
    }

    async fn run_hooks(&self, hooks: &[Box<dyn AsyncStep<W>>], world: &mut W) {
        for hook in hooks {
            hook.call(world, vec![], StepContext::default()).await;
        }
    }

    /// Executes a Gherkin feature from a string.
    pub async fn execute_from_memory(&self, content: &str, world: &mut W)
    where
        W: World,
    {
        let feature = Feature::parse(content, Default::default()).expect("Failed to parse feature");

        for scenario in &feature.scenarios {
            if self.is_ignored(&feature.tags, &scenario.tags) {
                println!("Scenario: {} ... SKIP", scenario.name);
                continue;
            }
            if !self.matches_filter(&feature.tags, &scenario.tags) {
                continue;
            }

            if scenario.examples.is_empty() {
                self.run_scenario(&feature, scenario, world).await;
            } else {
                self.run_scenario_outline(&feature, scenario, world).await;
            }
        }
    }

    /// Parses a Gherkin feature and prints its matched scenarios and steps in
    /// Cucumber style without executing them.
    pub fn dry_run_list(&self, content: &str) {
        let feature = Feature::parse(content, Default::default()).expect("Failed to parse feature");
        // No longer print the Feature title to save vertical noise

        if let Some(bg) = &feature.background {
            let sep = if bg.name.is_empty() { "" } else { " " };
            println!("  Background:{}{}", sep, bg.name);
            for step in &bg.steps {
                let status = if self.is_match(&step.value) {
                    "\x1b[32m# ok\x1b[0m"
                } else {
                    "\x1b[31m# UNDEFINED\x1b[0m"
                };
                println!("    {} {} {}", step.keyword, step.value, status);
            }
            println!();
        }

        for scenario in &feature.scenarios {
            if self.is_ignored(&feature.tags, &scenario.tags) {
                println!("  Scenario: {} ... \x1b[33mSKIP\x1b[0m", scenario.name);
                continue;
            }
            if !self.matches_filter(&feature.tags, &scenario.tags) {
                continue;
            }
            if scenario.examples.is_empty() {
                println!("  Scenario: {}", scenario.name);
                for step in &scenario.steps {
                    let status = if self.is_match(&step.value) {
                        "\x1b[32m# ok\x1b[0m"
                    } else {
                        "\x1b[31m# UNDEFINED\x1b[0m"
                    };
                    println!("    {} {} {}", step.keyword, step.value, status);
                }
                println!();
            } else {
                for example in &scenario.examples {
                    let Some(table) = &example.table else { continue };
                    if table.rows.is_empty() {
                        continue;
                    }
                    let header_row = &table.rows[0];
                    let headers: Vec<String> =
                        header_row.iter().map(|s| format!("<{}>", s)).collect();

                    for row in table.rows.iter().skip(1) {
                        println!("  Scenario Outline: {}", scenario.name);
                        let replacements: Vec<(&str, &str)> = headers
                            .iter()
                            .zip(row.iter())
                            .map(|(h, v)| (h.as_str(), v.as_str()))
                            .collect();
                        for step in &scenario.steps {
                            let value =
                                crate::utils::apply_replacements(&step.value, &replacements);
                            let status = if self.is_match(&value) {
                                "\x1b[32m# ok\x1b[0m"
                            } else {
                                "\x1b[31m# UNDEFINED\x1b[0m"
                            };
                            println!("    {} {} {}", step.keyword, value, status);
                        }
                        println!();
                    }
                }
            }
        }
    }

    fn is_match(&self, text: &str) -> bool {
        for (regex, _) in &self.steps {
            if let Some(m) = regex.find(text) {
                if m.start() == 0 && m.end() == text.len() {
                    return true;
                }
            }
        }
        false
    }

    fn is_ignored(&self, feature_tags: &[String], scenario_tags: &[String]) -> bool {
        feature_tags.iter().any(|t| t == "skip" || t == "ignore")
            || scenario_tags.iter().any(|t| t == "skip" || t == "ignore")
    }

    fn matches_filter(&self, feature_tags: &[String], scenario_tags: &[String]) -> bool {
        if let Some(filter) = &self.tag_filter {
            let filter_str = filter.as_str();
            let filter_name = filter_str.strip_prefix("@").unwrap_or(filter_str);

            return feature_tags.iter().any(|t| t == filter_str || t == filter_name)
                || scenario_tags.iter().any(|t| t == filter_str || t == filter_name);
        }
        true
    }

    async fn run_scenario(&self, feature: &Feature, scenario: &gherkin::Scenario, world: &mut W)
    where
        W: World,
    {
        use std::io::Write;
        print!("Scenario: {} ... ", scenario.name);
        std::io::stdout().flush().unwrap();

        let start = std::time::Instant::now();
        world.reset().await;
        self.run_hooks(&self.before_hooks, world).await;
        self.run_background(&feature.background, world).await;
        self.run_steps(&scenario.steps, world, &[]).await;
        self.run_hooks(&self.after_hooks, world).await;

        let elapsed = start.elapsed().as_secs_f64() * 1000.0;
        println!("PASS ({:.1} ms)", elapsed);
    }

    async fn run_scenario_outline(
        &self,
        feature: &Feature,
        scenario: &gherkin::Scenario,
        world: &mut W,
    ) where
        W: World,
    {
        for example in &scenario.examples {
            let Some(table) = &example.table else { continue };
            if table.rows.is_empty() {
                continue;
            }

            // Assume first row is header
            let header_row = &table.rows[0];
            let headers: Vec<String> = header_row.iter().map(|s| format!("<{}>", s)).collect();

            for row in table.rows.iter().skip(1) {
                world.reset().await;
                self.run_hooks(&self.before_hooks, world).await;
                self.run_background(&feature.background, world).await;

                let replacements: Vec<(&str, &str)> =
                    headers.iter().zip(row.iter()).map(|(h, v)| (h.as_str(), v.as_str())).collect();

                let desc = replacements
                    .iter()
                    .map(|(k, v)| format!("{}={}", k, v))
                    .collect::<Vec<_>>()
                    .join(", ");
                use std::io::Write;
                print!("Scenario Outline: {} [{}] ... ", scenario.name, desc);
                std::io::stdout().flush().unwrap();

                let start = std::time::Instant::now();
                self.run_steps(&scenario.steps, world, &replacements).await;
                self.run_hooks(&self.after_hooks, world).await;

                let elapsed = start.elapsed().as_secs_f64() * 1000.0;
                println!("PASS ({:.1} ms)", elapsed);
            }
        }
    }

    async fn run_steps(
        &self,
        steps: &[gherkin::Step],
        world: &mut W,
        replacements: &[(&str, &str)],
    ) {
        for step in steps {
            let value = crate::utils::apply_replacements(&step.value, replacements);
            let table = step.table.as_ref().map(|t| apply_table_replacements(t, replacements));
            self.run_with_context(&value, world, StepContext { table }).await;
        }
    }

    async fn run_background(&self, bg: &Option<gherkin::Background>, world: &mut W) {
        if let Some(ref bg) = bg {
            // Suppress background trace prints to keep test output clean
            for step in &bg.steps {
                let table =
                    step.table.clone().map(|t| t.rows.iter().map(|row| row.to_vec()).collect());
                self.run_with_context(&step.value, world, StepContext { table }).await;
            }
        }
    }

    /// Executes a Gherkin feature from a file.
    pub async fn execute<P: AsRef<Path>>(&self, path: P, world: &mut W)
    where
        W: World,
    {
        let content = std::fs::read_to_string(path).expect("Failed to read feature file");
        self.execute_from_memory(&content, world).await;
    }
}

fn apply_table_replacements(
    table: &gherkin::Table,
    replacements: &[(&str, &str)],
) -> crate::step::DataTable {
    table
        .rows
        .iter()
        .map(|row| {
            row.iter().map(|cell| crate::utils::apply_replacements(cell, replacements)).collect()
        })
        .collect()
}
