# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

"""Defines a module extension to create repos for local rust crates for netsim."""

load("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")
load("//cargo:repository_rules.bzl", "patched_new_local_repository")

def _lrc_impl(module_ctx):
    # Compute the repo root dynamically from the location of this module
    netsim_dir = module_ctx.path(Label("//:MODULE.bazel")).dirname
    workspace_root = str(netsim_dir.dirname.dirname)

    android_crates_io = "/".join([workspace_root, "external", "rust", "android-crates-io", "crates"])

    # 1. Custom Path Crates
    _CUSTOM_PATH_CRATES = [
        struct(name = "getrandom_v0_2", path = "/".join([workspace_root, "external", "rust", "android-crates-io-pinned", "crates", "getrandom"])),
        struct(name = "pica", path = workspace_root + "/third_party/rust/crates/pica"),
        struct(name = "protobuf-rust", path = android_crates_io + "/protobuf"),
        # winapi-util is required by termcolor on Windows (and so, transitively,
        # by the cxx codegen host tool via codespan-reporting). AOSP does not
        # ship it in external/rust/android-crates-io because nothing in the
        # platform build targets Windows, so the only copy in the checkout is
        # the one vendored for the emulator. TODO: move this crate into
        # android-crates-io so the path below can be dropped.
        struct(name = "winapi-util", path = workspace_root + "/hardware/generic/goldfish/third_party/rust/crates/winapi-util-0.1.9"),
    ]

    for crate in _CUSTOM_PATH_CRATES:
        new_local_repository(
            name = crate.name,
            build_file = "@netsim//cargo/build:{}.BUILD.bazel".format(crate.name),
            path = crate.path,
        )

    # 2. Patched Dependencies (tempfile)
    patched_new_local_repository(
        name = "tempfile",
        build_file = "@netsim//cargo/build:tempfile.BUILD.bazel",
        path = "{}/tempfile".format(android_crates_io),
        patches = ["@netsim//cargo/build:tempfile.patch"],
    )

    # 3. Standard Android Crates
    _ANDROID_CRATES = [
        "aho-corasick",
        "android_log-sys",
        "anstyle",
        "anyhow",
        "argh",
        "argh_derive",
        "argh_shared",
        "arrayvec",
        "async-trait",
        "base64",
        "bitflags",
        "byteorder",
        "bytes",
        "cfg-if",
        "chacha20",
        "chrono",
        "clap",
        "clap_builder",
        "clap_derive",
        "clap_lex",
        "codespan-reporting",
        "command-fds",
        "cpufeatures",
        "crc32fast",
        "data-encoding",
        "displaydoc",
        "downcast",
        "env_filter",
        "env_logger",
        "equivalent",
        "errno",
        "etherparse",
        "fastrand",
        "flate2",
        "fnv",
        "foldhash",
        "form_urlencoded",
        "fragile",
        "futures",
        "futures-channel",
        "futures-core",
        "futures-executor",
        "futures-io",
        "futures-macro",
        "futures-sink",
        "futures-task",
        "futures-util",
        "getrandom",
        "gherkin",
        "glam",
        "grpcio",
        "grpcio-sys",
        "hashbrown",
        "heck",
        "hex",
        "http",
        "httparse",
        "icu_collections",
        "icu_locale_core",
        "icu_normalizer",
        "icu_normalizer_data",
        "icu_properties",
        "icu_properties_data",
        "icu_provider",
        "idna",
        "idna_adapter",
        "indexmap",
        "itoa",
        "jiff",
        "lazy_static",
        "libc",
        "libz-sys",
        "litemap",
        "lock_api",
        "log",
        "matchers",
        "memchr",
        "memoffset",
        "minimal-lexical",
        "mio",
        "mockall",
        "mockall_derive",
        "nix",
        "nom",
        "num-bigint",
        "num-derive",
        "num-integer",
        "num-traits",
        "num_cpus",
        "once_cell",
        "parking_lot",
        "parking_lot_core",
        "pdl-compiler",
        "pdl-runtime",
        "peg",
        "peg-macros",
        "peg-runtime",
        "percent-encoding",
        "pest",
        "pest_derive",
        "pest_generator",
        "pest_meta",
        "pin-project-lite",
        "pin-utils",
        "potential_utf",
        "predicates",
        "predicates-core",
        "predicates-tree",
        "prettyplease",
        "proc-macro2",
        "protobuf-codegen",
        "protobuf-json-mapping",
        "protobuf-parse",
        "protobuf-support",
        "quote",
        "rand",
        "rand_core",
        "regex",
        "regex-automata",
        "regex-syntax",
        "ring",
        "rustix",
        "ryu",
        "scopeguard",
        "serde",
        "serde-xml-rs",
        "serde_core",
        "serde_derive",
        "serde_json",
        "sharded-slab",
        "signal-hook-registry",
        "slab",
        "smallvec",
        "socket2",
        "spin",
        "stable_deref_trait",
        "strsim",
        "syn",
        "synstructure",
        "termcolor",
        "termtree",
        "textwrap",
        "thiserror",
        "thiserror-impl",
        "thread_local",
        "tinystr",
        "tokio",
        "tokio-macros",
        "tokio-stream",
        "tokio-util",
        "tracing",
        "tracing-attributes",
        "tracing-core",
        "tracing-log",
        "tracing-subscriber",
        "tungstenite",
        "typed-builder",
        "typed-builder-macro",
        "ucd-trie",
        "unicode-bidi",
        "unicode-ident",
        "unicode-width",
        "untrusted",
        "url",
        "utf-8",
        "utf8_iter",
        "which",
        "windows-link",
        "windows-sys",
        "windows-targets",
        "windows_aarch64_gnullvm",
        "windows_i686_gnullvm",
        "windows_x86_64_gnullvm",
        "writeable",
        "xml-rs",
        "yoke",
        "yoke-derive",
        "zerocopy",
        "zerocopy-derive",
        "zerofrom",
        "zerofrom-derive",
        "zerotrie",
        "zerovec",
        "zerovec-derive",
        "zip",
        "zlib-rs",
        "zmij",
    ]

    for crate_name in _ANDROID_CRATES:
        new_local_repository(
            name = crate_name,
            build_file = "@netsim//cargo/build:{}.BUILD.bazel".format(crate_name),
            path = "{}/{}".format(android_crates_io, crate_name),
        )

    return module_ctx.extension_metadata(root_module_direct_deps = "all", root_module_direct_dev_deps = [], reproducible = True)

lrc = module_extension(
    implementation = _lrc_impl,
    tag_classes = {},
)
