# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "nfc-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
actor-framework = { path = "../actor-framework" }
async-trait = "0.1"
bytes = "1"
device-actor = { path = "../device-actor" }
device-api = { path = "../device-api" }
futures = "0.3"
netsim-model = { path = "../model" }
thiserror = "1"
tracing = "0.1"

[features]
cuttlefish = []
