# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "nfc-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
actor-framework = { path = "../actor-framework" }
anyhow = "1"
async-trait = "0.1"
bytes = "1"
casimir = { path = "../../../../packages/modules/Nfc/libnfc-nci/tools/casimir" }
device-actor = { path = "../device-actor" }
device-api = { path = "../device-api" }
futures = "0.3"
netsim-model = { path = "../model" }
netsim-proto = { path = "../../proto" }
thiserror = "1"
tokio = { version = "1.28.2", features = ["process", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["io", "codec"] }
tracing = "0.1"

[features]
cuttlefish = []
