# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "netsim-cli"
version = "0.3.92"
edition = "2024"

[[bin]]
name = "netsim"
path = "src/main.rs"
doc = false

[dependencies]
clap = { version = "4.1.8", default-features = false, features = [
  "derive",
  "error-context",
  "help",
  "std",
  "usage",
] }
futures = "0.3.30"
futures-util = { version = "0.3.30", default-features = false, features = [
  "sink",
] }
grpcio = { version = "0.13.0", default-features = false, features = [
  "protobufv3-codec",
] }
hex = "0.4.3"
netsim-common = { path = "../common" }
netsim-packets = { path = "../packets" }
protobuf = "3.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
