[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
actor-framework = { path = "../actor-framework" }
bluetooth-actor = { package = "bluetooth", path = "../bluetooth-actor" }
capture-actor = { path = "../capture-actor" }
cell = { path = "../cell" }
chrono = { version = "0.4", features = ["now"] }
clap = { version = "4.1.8", default-features = false, features = [
  "derive",
  "error-context",
  "help",
  "std",
  "usage",
  "env",
] }
client = { path = "../client" }
device-actor = { path = "../device-actor" }
grpc-server = { path = "../grpc-server" }
grpcio = { version = "0.13", default-features = false, features = [
  "protobufv3-codec",
  "openssl",
] }
link-actor = { path = "../link-actor" }
log = "0.4"
netsim-common = { path = "../common" }
netsim-model = { path = "../model" }
packet-stream = { path = "../packet-stream" }
tokio = { version = "1.28.2", features = ["full"] }
uwb-actor = { path = "../uwb-actor" }
wifi-actor = { path = "../wifi-actor" }

[dev-dependencies]
tempfile = "3"

[features]
default = []
cuttlefish = []
