# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lib",
    testonly = True,
    srcs = [
        "src/features.rs",
        "src/lib.rs",
        "src/step.rs",
        "src/utils.rs",
    ],
    crate_name = "features",
    edition = "2021",
    proc_macro_deps = [
    ],
    deps = [
        "@anyhow",
        "@gherkin",
        "@regex",
        "@serde",
        "@serde_json",
        "@termcolor",
    ],
)

rust_test(
    name = "integration-test",
    srcs = [
        "tests/lib_test_world.rs",
    ],
    compile_data = glob([
        "tests/features/*.feat",
        "tests/features/*.feature",
    ]),
    crate_features = ["testing"],
    crate_root = "tests/lib_test_world.rs",
    edition = "2021",
    proc_macro_deps = [
        "//next/verify/macros:verify_macros",
    ],
    deps = [
        ":lib",
        "//next/packets",
        "@anyhow",
        "@bytes",
        "@futures",
        "@gherkin",
        "@regex",
        "@serde",
        "@serde_json",
        "@tokio",
        "@tokio-stream",
        "@tracing",
        "@tracing-subscriber",
    ],
)
