# Copyright 2025 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""netsim bazel build rule."""

load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

proto_library(
    name = "netsimd-proto",
    srcs = [
        "proto/netsim/common.proto",
        "proto/netsim/frontend.proto",
        "proto/netsim/hci_packet.proto",
        "proto/netsim/model.proto",
        "proto/netsim/packet_streamer.proto",
        "proto/netsim/startup.proto",
        "proto/netsim/stats.proto",
    ],
    strip_import_prefix = "proto",
    deps = [
        "@protobuf//:empty_proto",
        "@protobuf//:timestamp_proto",
        "@rootcanal//:rootcanal-configuration-proto",
    ],
)

rust_library(
    name = "netsim_common",
    srcs = glob(["rust/common/src/**/*.rs"]),
    deps = [
        "@anyhow",
        "@chrono",
        "@env_logger",
        "@libc",
        "@log_rust",
        "@protobuf_json_mapping",
        "@rand",
        "@zip",
    ],
)

rust_test(
    name = "netsim_common_tests",
    crate = ":netsim_common",
    tags = ["general_tests"],
)

rust_library(
    name = "netsim_proto",
    srcs = glob(["rust/proto/src/**/*.rs"]),
    crate_name = "netsim_proto",
    deps = [
        "@grpcio",
        "@protobuf-rust",
    ],
)
