# Copyright 2025 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""netsim bazel build rule."""

load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

proto_library(
    name = "netsimd-proto",
    srcs = [
        "proto/netsim/common.proto",
        "proto/netsim/frontend.proto",
        "proto/netsim/hci_packet.proto",
        "proto/netsim/model.proto",
        "proto/netsim/packet_streamer.proto",
        "proto/netsim/startup.proto",
        "proto/netsim/stats.proto",
    ],
    strip_import_prefix = "proto",
    deps = [
        "@protobuf//:empty_proto",
        "@protobuf//:timestamp_proto",
        "@rootcanal//:rootcanal-configuration-proto",
    ],
)

# BLE Advertisers

rust_library(
    name = "ble_advertisers",
    srcs = glob(["rust/ble-advertisers/src/**/*.rs"]),
    deps = [
        "@hex",
        "@thiserror",
        "@zerocopy",
    ],
)

rust_test(
    name = "ble_advertisers_tests",
    crate = ":ble_advertisers",
    tags = ["general_tests"],
)

rust_library(
    name = "netsim_common",
    srcs = glob(["rust/common/src/**/*.rs"]),
    deps = [
        "@anyhow",
        "@chrono",
        "@env_logger",
        "@libc",
        "@log_rust",
        "@protobuf_json_mapping",
        "@rand",
        "@zip",
    ],
)

rust_test(
    name = "netsim_common_tests",
    crate = ":netsim_common",
    tags = ["general_tests"],
)

rust_library(
    name = "netsim_proto",
    srcs = glob(["rust/proto/src/**/*.rs"]),
    crate_name = "netsim_proto",
    deps = [
        "@grpcio",
        "@protobuf-rust",
    ],
)

rust_library(
    name = "netsim_cli",
    srcs = glob(["rust/cli/src/**/*.rs"]),
    crate_name = "netsim_cli",
    deps = [
        ":netsim_common",
        ":netsim_proto",
        "@clap",
        "@futures",
        "@futures_util",
        "@grpcio",
        "@hex",
        "@log_rust",
        "@protobuf-rust",
    ],
)

rust_test(
    name = "netsim_cli_tests",
    crate = ":netsim_cli",
    tags = ["general_tests"],
)

# PDL generated files
genrule(
    name = "netsim_netlink_rust_gen",
    srcs = ["pdl/netlink.pdl"],
    outs = ["netlink_packets.rs"],
    cmd = "$(location @pdl_compiler//:pdlc) --output-format rust $(SRCS) > $(OUTS)",
    tools = ["@pdl_compiler//:pdlc"],
)

genrule(
    name = "netsim_mac80211_hwsim_rust_gen",
    srcs = ["pdl/mac80211_hwsim.pdl"],
    outs = ["mac80211_hwsim_packets.rs"],
    cmd = "$(location @pdl_compiler//:pdlc) --output-format rust $(SRCS) > $(OUTS)",
    tools = ["@pdl_compiler//:pdlc"],
)

genrule(
    name = "netsim_ieee80211_rust_gen",
    srcs = ["pdl/ieee80211.pdl"],
    outs = ["ieee80211_packets.rs"],
    cmd = "$(location @pdl_compiler//:pdlc) --output-format rust $(SRCS) > $(OUTS)",
    tools = ["@pdl_compiler//:pdlc"],
)

genrule(
    name = "netsim_llc_rust_gen",
    srcs = ["pdl/llc.pdl"],
    outs = ["llc_packets.rs"],
    cmd = "$(location @pdl_compiler//:pdlc) --output-format rust $(SRCS) > $(OUTS)",
    tools = ["@pdl_compiler//:pdlc"],
)

genrule(
    name = "netsim_link_layer_packets_rust_gen",
    srcs = ["@rootcanal//:packets/link_layer_packets.pdl"],
    outs = ["link_layer_packets.rs"],
    cmd = "$(location @pdl_compiler//:pdlc) --output-format rust $(SRCS) > $(OUTS)",
    tools = ["@pdl_compiler//:pdlc"],
)

rust_library(
    name = "netsim_packets",
    srcs = glob(["rust/packets/src/**/*.rs"]) + [
        ":netsim_ieee80211_rust_gen",
        ":netsim_link_layer_packets_rust_gen",
        ":netsim_llc_rust_gen",
        ":netsim_mac80211_hwsim_rust_gen",
        ":netsim_netlink_rust_gen",
    ],
    crate_name = "netsim_packets",
    rustc_env = {
        "OUT_DIR": "../../..",
    },
    deps = [
        "@anyhow",
        "@bytes",
        "@pdl_runtime",
    ],
)
