# Copyright 2024 The Android Open Source Project
"""The top level module definition for netsim build."""

include("//build/bazel/toolchains:toolchain.MODULE.bazel")

bazel_dep(name = "netsim", version = "0.0.1")
bazel_dep(name = "rules_jvm_external", version = "6.10")
bazel_dep(name = "fmt", version = "12.1.0")

# Force buildozer 8.2.1 checksum in lockfile for cloud presubmit
bazel_dep(name = "buildozer", version = "8.2.1")
bazel_dep(name = "casimir", version = "0.0.1")

custom_toolchains = use_extension("@goldfish_build//extensions:toolchain.bzl", "toolchain")
custom_toolchains.clang(root_path = "prebuilts/clang/host")
custom_toolchains.java(
    root_path = "prebuilts/studio/jdk",
    version = "jdk17",
)

remote_android_extensions = use_extension("@rules_android//bzlmod_extensions:android_extensions.bzl", "remote_android_tools_extensions")
use_repo(remote_android_extensions, "android_tools")

register_toolchains("@android_tools//:all")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "androidx.core.uwb:uwb:1.0.0-alpha05",
        "androidx.test.uiautomator:uiautomator:2.3.0",
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3",
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3",
    ],
    known_contributing_modules = [
        "grpc-java",
        "netsim",
        "protobuf",
    ],
    lock_file = "//tools/netsim:maven_install.json",
    repositories = [
        "https://repo.maven.apache.org/maven2/",
        "https://maven.google.com",
    ],
)
use_repo(maven, "maven")

local_path_override(
    module_name = "casimir",
    path = "packages/modules/Nfc/libnfc-nci/tools/casimir",
)
