[package]
name = "uwb-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
actor-framework = { path = "../actor-framework" }
async-trait = "0.1"
bytes = "1"
client = { path = "../client" }
device-api = { path = "../device-api" }
futures = "0.3"
log = "0.4"
netsim-model = { path = "../model" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[dev-dependencies]
netsim-testing = { path = "../testing", features = ["testing"] }
