[package]
name = "uwb-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
actor-framework = { path = "../actor-framework" }
anyhow = "1"
async-trait = "0.1"
bytes = "1"
device-actor = { path = "../device-actor" }
futures = "0.3"
glam = "0.25"
log = "0.4"
netsim-model = { path = "../model" }
pica = { version = "0.1", default-features = false }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
device-api = { path = "../device-api" }
netsim-testing = { path = "../testing", features = ["testing"] }
