# Copyright 2024 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "capture"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]

[dependencies]
tokio = { version = "1.32.0", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
] }
zerocopy = "0.8.25"
zerocopy-derive = "0.8.25"
