# Copyright 2024 The Android Open Source Project

[package]
name = "netsim-packets"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
doctest = false

[dependencies]
anyhow = "1"
bytes = { version = ">=1.4.0" }
pdl-runtime = "0.4.2"
serde_json = "1.0.143"
hex = "0.4.3"
zerocopy = { version = "0.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
