[package]
name = "netsim-next"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["now"] }
env_logger = "0.10"
log = "0.4"
netsim-api = { path = "../netsim-api" }
bluetooth = { path = "../bluetooth" }
devices = { path = "../devices" }
packet-stream = { path = "../packet-stream" }
tokio = { version = "1.28.2", features = ["full"] }

[dev-dependencies]

[features]
default = []
cuttlefish = []
