# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

package(default_visibility = ["//visibility:public"])

rust_proc_macro(
    name = "verify_macros",
    srcs = ["src/lib.rs"],
    edition = "2024",
    deps = [
        "@proc-macro2",
        "@quote",
        "@syn",
    ],
)
