// Copyright 2026 The Android Open Source Project

use netsim_packets::transport::udp::UdpHeader;
use netsim_testing::cuke::{Cuke, DataTable};
use zerocopy::IntoBytes;

/// # Example World
///
/// This is an example of a "World" struct that holds the state for Cuke tests.
/// It demonstrates how to use the `cuke_codegen` macro to automatically
/// generate glue code.
///
/// The `cuke_codegen` tool (invoked via `genrule` in BUILD) parses this file,
/// finds methods commented with `/// Cuke:`, and generates
/// `cuke_world_glue.rs`.
struct TestWorld {
    /// The main display register (accumulator)
    display: i32,
    log: Vec<String>,
    users: std::collections::HashMap<String, i32>,
    tx_power: TxPower,
    enabled: bool,
    temperature: f64,
    /// The memory register (M+, M-, MR, MC)
    memory: i32,
    /// Mock network interface buffer (stores received packets)
    received_packets: Vec<Vec<u8>>,
}

#[derive(Debug, PartialEq, Clone, Copy)]
enum TxPower {
    High,
    Medium,
    Low,
    Ultralow,
}

impl std::str::FromStr for TxPower {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "High" => Ok(TxPower::High),
            "Medium" => Ok(TxPower::Medium),
            "Low" => Ok(TxPower::Low),
            "Ultralow" => Ok(TxPower::Ultralow),
            _ => Err(format!("Invalid TxPower: {}", s)),
        }
    }
}

impl TestWorld {}

/// Cuke: Given I reset the counter
async fn reset_step(w: &mut TestWorld) {
    w.display = 0;
    w.log.push("reset".to_string());
}

/// Cuke: Given I have a calculator with Memory (\d+)
async fn reset_step_with_memory(w: &mut TestWorld, memory: i32) {
    w.display = 0;
    w.memory = memory;
    w.log.push(format!("reset_calculator memory {}", memory));
}

/// Cuke: Given I have a calculator with No Memory
async fn reset_step_no_memory(w: &mut TestWorld) {
    w.display = 0;
    w.memory = 0;
    w.log.push("reset_calculator memory 0".to_string());
}

/// Cuke: Given I want to ensure a clean state before every scenario
async fn reset_step_background(w: &mut TestWorld) {
    w.display = 0;
    w.log.push("reset_background".to_string());
}

/// Cuke: Given I organize my scenarios with tags
async fn reset_step_tags(w: &mut TestWorld) {
    w.display = 0;
    w.log.push("reset_tags".to_string());
}

/// Cuke: When I set TxPower to (High|Medium|Low|Ultralow)
async fn set_tx_power(w: &mut TestWorld, power: TxPower) {
    w.tx_power = power;
    w.log.push(format!("tx_power {:?}", power));
}

/// Cuke: When I add (\d+)
async fn add_step(w: &mut TestWorld, val: i32) {
    w.display += val;
    w.log.push(format!("add {}", val));
}

/// Cuke: Then result is (\d+)
async fn check_step(w: &mut TestWorld, val: i32) {
    // A real test step should panic/assert on failure so the test framework catches
    // it.
    assert_eq!(w.display, val, "Check failed: expected {}, got {}", val, w.display);
    w.log.push(format!("check {}", val));
}

/// Cuke: Given system is (true|false)
async fn set_system_enabled(w: &mut TestWorld, val: bool) {
    w.enabled = val;
    w.log.push(format!("system is {}", val));
}

/// Cuke: When I set temperature to (\d+\.\d+)
async fn set_temperature(w: &mut TestWorld, val: f64) {
    w.temperature = val;
    w.log.push(format!("temperature set to {}", val));
}

/// Cuke: Then system should be (true|false)
async fn check_system_enabled(w: &mut TestWorld, val: bool) {
    assert_eq!(w.enabled, val);
    w.log.push(format!("check system is {}", val));
}

/// Cuke: Then temperature should be (\d+\.\d+)
async fn check_temperature(w: &mut TestWorld, val: f64) {
    assert_eq!(w.temperature, val);
    w.log.push(format!("check temperature is {}", val));
}

/// Cuke: Before
async fn before_hook(w: &mut TestWorld) {
    w.log.push("before".to_string());
}

/// Cuke: After
async fn after_hook(w: &mut TestWorld) {
    w.log.push("after".to_string());
}

fn setup_cuke_world() -> (Cuke<TestWorld>, TestWorld) {
    let mut cuke = Cuke::<TestWorld>::new();
    // The glue code is generated by `cuke_codegen` from the doc comments above.
    mod glue {
        use super::*;
        // This include works because the generated file is in the same directory
        // (tests/) during build.
        include!("cuke_world_glue.rs");
    }
    glue::register_steps(&mut cuke);
    let world = TestWorld {
        display: 0,
        log: Vec::new(),
        users: std::collections::HashMap::new(),
        tx_power: TxPower::Low,
        enabled: false,
        temperature: 0.0,
        memory: 0,
        received_packets: Vec::new(),
    };
    (cuke, world)
}

#[tokio::test]
async fn test_cuke_methods_success() {
    let (cuke, mut world) = setup_cuke_world();
    world.display = 999;

    cuke.run("Given I reset the counter", &mut world).await;
    cuke.run("When I add 10", &mut world).await;
    cuke.run("Then result is 10", &mut world).await;

    assert_eq!(world.log, vec!["reset", "add 10", "check 10"]);
}

#[tokio::test]
async fn test_cuke_background() {
    netsim_testing::logger::setup(None);
    let (cuke, mut world) = setup_cuke_world();

    cuke.execute_from_memory(include_str!("features/background.feature"), &mut world).await;

    // Feature: Background Support
    // Background: reset_background
    // Scenario: Incremental Add (add 5, check 5)
    //
    // Sequence:
    // Before -> Background(reset_background) -> Steps(add 5, check 5) -> After

    assert_eq!(world.log, vec!["before", "reset_background", "add 5", "check 5", "after"]);
}

#[tokio::test]
async fn test_cuke_outline() {
    netsim_testing::logger::setup(None);
    let (cuke, mut world) = setup_cuke_world();

    cuke.execute_from_memory(include_str!("features/outline.feature"), &mut world).await;

    // Feature: Scenario Outline Support
    // Background: reset_outline
    // Scenario Outline: Add multiple numbers
    //   Ex 1: 10, 20 -> 30
    //   Ex 2: 1, 2 -> 3
    //
    // Sequence:
    // Before -> Background(reset_outline) -> Steps(add 10, add 20, check 30) ->
    // After Before -> Background(reset_outline) -> Steps(add 1, add 2, check 3)
    // -> After

    assert_eq!(
        world.log,
        vec![
            "before",
            "reset_calculator memory 0",
            "add 10",
            "add 20",
            "check 30",
            "after",
            "before",
            "reset_calculator memory 0",
            "add 1",
            "add 2",
            "check 3",
            "after"
        ]
    );
}

#[tokio::test]
#[should_panic(expected = "Check failed: expected 9999, got 10")]
async fn test_cuke_assertion_failure() {
    let (cuke, mut world) = setup_cuke_world();

    cuke.run("Given I reset the counter", &mut world).await;
    cuke.run("When I add 10", &mut world).await;
    // This should panic
    cuke.run("Then result is 9999", &mut world).await;
}

#[tokio::test]
#[should_panic(expected = "No step definition found for: I do not exist")]
async fn test_cuke_missing_step() {
    let (cuke, mut world) = setup_cuke_world();
    cuke.run("I do not exist", &mut world).await;
}

#[tokio::test]
async fn test_cuke_tags_filtering() {
    netsim_testing::logger::setup(None);
    let (mut cuke, mut world) = setup_cuke_world();

    // Set filter to @wip
    cuke.filter("@wip");

    cuke.execute_from_memory(include_str!("features/tags.feature"), &mut world).await;

    // Filtered execution (only Tagged scenario)
    // Before -> Background(reset_tags) -> Steps(add 100, check 100) -> After

    assert_eq!(world.log, vec!["before", "reset_tags", "add 100", "check 100", "after"]);
}

/// Cuke: Given the following users:
async fn given_users(w: &mut TestWorld, table: netsim_testing::cuke::DataTable) {
    // Skip header row
    for row in table.iter().skip(1) {
        let name = row[0].clone();
        let age: i32 = row[1].parse().expect("Age must be a number");
        w.users.insert(name.clone(), age);
        w.log.push(format!("user {} age {}", name, age));
    }
}

/// Cuke: Then lookup (\w+) is (\d+)
async fn check_user_age(w: &mut TestWorld, name: String, age: i32) {
    let actual = w.users.get(&name).expect("User not found");
    assert_eq!(*actual, age, "Age mismatch for {}", name);
    w.log.push(format!("lookup {} is {}", name, age));
}

#[tokio::test]
async fn test_cuke_data_table() {
    netsim_testing::logger::setup(None);
    let (cuke, mut world) = setup_cuke_world();

    let feature = include_str!("features/data_table.feature");

    cuke.execute_from_memory(feature, &mut world).await;

    assert_eq!(
        world.log,
        vec![
            "before",
            "user Alice age 30",
            "user Bob age 25",
            "lookup Alice is 30",
            "lookup Bob is 25",
            "after"
        ]
    );
}

#[tokio::test]
async fn test_cuke_types() {
    netsim_testing::logger::setup(None);
    let (cuke, mut world) = setup_cuke_world();

    let feature = include_str!("features/types.feature");

    cuke.execute_from_memory(feature, &mut world).await;

    // Feature: Type Support
    // Scenario: Boolean and Float types
    //   Given system is true
    //   When I set temperature to 98.6
    //   Then system should be true
    //   And temperature should be 98.6
    //
    // Scenario: Disable system
    //   Given system is false
    //   Then system should be false

    assert_eq!(
        world.log,
        vec![
            "before",
            "system is true",
            "temperature set to 98.6",
            "check system is true",
            "check temperature is 98.6",
            "after",
            "before",
            "system is false",
            "check system is false",
            "after"
        ]
    );
}

#[tokio::test]
async fn test_cuke_enum() {
    netsim_testing::logger::setup(None);
    let (mut cuke, mut world) = setup_cuke_world();

    let feature_content = include_str!("features/enum.feature");

    cuke.execute_from_memory(feature_content, &mut world).await;

    assert_eq!(world.log, vec!["before", "tx_power High", "tx_power Ultralow", "after"]);
    assert_eq!(world.tx_power, TxPower::Ultralow);
}

/// Cuke: Given I have a UDP Echo Server on Port (\d+)
async fn given_udp_echo_server(w: &mut TestWorld, _port: u16) {
    w.received_packets.clear();
    w.log.push("udp_echo_server_init".to_string());
}

/// Cuke: When I send a UDP packet with:
async fn when_send_packet(w: &mut TestWorld, table: DataTable) {
    let json_header: netsim_packets::transport::udp_json::JsonUdpHeader =
        netsim_testing::cuke::table_to_struct(&table).expect("Failed to parse UdpHeader");
    let header: UdpHeader =
        json_header.try_into().expect("Failed to convert JsonUdpHeader to UdpHeader");

    // Simulate sending by pushing to received_packets
    w.received_packets.push(header.as_bytes().to_vec());
    w.log.push("send_udp".to_string());
}

/// Cuke: Then I receive a UDP packet matching:
async fn then_receive_packet(w: &mut TestWorld, table: DataTable) {
    assert!(!w.received_packets.is_empty(), "No packets received");
    let last_packet = w.received_packets.last().unwrap();

    // Parse the packet
    let (header, _payload) =
        UdpHeader::parse(last_packet.as_slice()).expect("Failed to parse UDP header");
    let packet_json = netsim_packets::transport::udp_json::to_json(&header);

    netsim_testing::cuke::assert_json_matches_table(&packet_json, &table);

    w.log.push("check_udp".to_string());
}

#[tokio::test]
async fn test_cuke_network() {
    netsim_testing::logger::setup(None);
    let (cuke, mut world) = setup_cuke_world();
    cuke.execute_from_memory(include_str!("features/network.feature"), &mut world).await;

    assert_eq!(
        world.log,
        vec!["before", "udp_echo_server_init", "send_udp", "check_udp", "after",]
    );
}
