[package]
version = "0.1.0"
edition = "2021"
name = "netsim-proto"

[dependencies]
grpcio = { version = "0.13.0", default-features = false, features = [
  "protobufv3-codec",
] }
protobuf = "=3.7.2"

[build-dependencies]
protobuf = "=3.7.2"
protobuf-codegen = "3.7.2"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
doctest = false
