[package]
name = "device-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
actor-framework = { path = "../actor-framework" }
device-api = { path = "../device-api" }
capture-api = { path = "../capture-api" }
netsim-model = { path = "../model" }
link-actor = { path = "../link-actor" }
link-api = { path = "../link-api" }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
async-trait = "0.1"
thiserror = "1.0"
[dev-dependencies]
client = { path = "../client" }
