// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/access_point.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:netsim.access_point.ExecuteAccessPointRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ExecuteAccessPointRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.ExecuteAccessPointRequest.id)
    pub id: u32,
    // message oneof groups
    pub action: ::std::option::Option<execute_access_point_request::Action>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.ExecuteAccessPointRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ExecuteAccessPointRequest {
    fn default() -> &'a ExecuteAccessPointRequest {
        <ExecuteAccessPointRequest as ::protobuf::Message>::default_instance()
    }
}

impl ExecuteAccessPointRequest {
    pub fn new() -> ExecuteAccessPointRequest {
        ::std::default::Default::default()
    }

    // .netsim.access_point.DisconnectRequest disconnect = 2;

    pub fn disconnect(&self) -> &DisconnectRequest {
        match self.action {
            ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(ref v)) => v,
            _ => <DisconnectRequest as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_disconnect(&mut self) {
        self.action = ::std::option::Option::None;
    }

    pub fn has_disconnect(&self) -> bool {
        match self.action {
            ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_disconnect(&mut self, v: DisconnectRequest) {
        self.action = ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(v))
    }

    // Mutable pointer to the field.
    pub fn mut_disconnect(&mut self) -> &mut DisconnectRequest {
        if let ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(_)) = self.action {
        } else {
            self.action = ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(DisconnectRequest::new()));
        }
        match self.action {
            ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_disconnect(&mut self) -> DisconnectRequest {
        if self.has_disconnect() {
            match self.action.take() {
                ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(v)) => v,
                _ => panic!(),
            }
        } else {
            DisconnectRequest::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &ExecuteAccessPointRequest| { &m.id },
            |m: &mut ExecuteAccessPointRequest| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, DisconnectRequest>(
            "disconnect",
            ExecuteAccessPointRequest::has_disconnect,
            ExecuteAccessPointRequest::disconnect,
            ExecuteAccessPointRequest::mut_disconnect,
            ExecuteAccessPointRequest::set_disconnect,
        ));
        oneofs.push(execute_access_point_request::Action::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ExecuteAccessPointRequest>(
            "ExecuteAccessPointRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ExecuteAccessPointRequest {
    const NAME: &'static str = "ExecuteAccessPointRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                18 => {
                    self.action = ::std::option::Option::Some(execute_access_point_request::Action::Disconnect(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        if let ::std::option::Option::Some(ref v) = self.action {
            match v {
                &execute_access_point_request::Action::Disconnect(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        if let ::std::option::Option::Some(ref v) = self.action {
            match v {
                &execute_access_point_request::Action::Disconnect(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ExecuteAccessPointRequest {
        ExecuteAccessPointRequest::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.action = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ExecuteAccessPointRequest {
        static instance: ExecuteAccessPointRequest = ExecuteAccessPointRequest {
            id: 0,
            action: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ExecuteAccessPointRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ExecuteAccessPointRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ExecuteAccessPointRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExecuteAccessPointRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ExecuteAccessPointRequest`
pub mod execute_access_point_request {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:netsim.access_point.ExecuteAccessPointRequest.action)
    pub enum Action {
        // @@protoc_insertion_point(oneof_field:netsim.access_point.ExecuteAccessPointRequest.disconnect)
        Disconnect(super::DisconnectRequest),
    }

    impl ::protobuf::Oneof for Action {
    }

    impl ::protobuf::OneofFull for Action {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::ExecuteAccessPointRequest as ::protobuf::MessageFull>::descriptor().oneof_by_name("action").unwrap()).clone()
        }
    }

    impl Action {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Action>("action")
        }
    }
}

// @@protoc_insertion_point(message:netsim.access_point.AccessPoint)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AccessPoint {
    // message fields
    ///  ID is the Chip ID in netsim architecture.
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.id)
    pub id: u32,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.ssid)
    pub ssid: ::std::string::String,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.bssid)
    pub bssid: ::std::string::String,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.channel)
    pub channel: u32,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.hw_mode)
    pub hw_mode: ::std::string::String,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.wpa_passphrase)
    pub wpa_passphrase: ::std::string::String,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.beacon_interval)
    pub beacon_interval: u32,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.country_code)
    pub country_code: ::std::string::String,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.dtim_period)
    pub dtim_period: u32,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.hidden_ssid)
    pub hidden_ssid: bool,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.sae)
    pub sae: bool,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.wmm_enabled)
    pub wmm_enabled: bool,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.enterprise_enabled)
    pub enterprise_enabled: bool,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.mac_acl_mode)
    pub mac_acl_mode: u32,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.mac_acl_list)
    pub mac_acl_list: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.ftm_responder_enabled)
    pub ftm_responder_enabled: bool,
    // @@protoc_insertion_point(field:netsim.access_point.AccessPoint.connected_devices)
    pub connected_devices: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.AccessPoint.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AccessPoint {
    fn default() -> &'a AccessPoint {
        <AccessPoint as ::protobuf::Message>::default_instance()
    }
}

impl AccessPoint {
    pub fn new() -> AccessPoint {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(17);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &AccessPoint| { &m.id },
            |m: &mut AccessPoint| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ssid",
            |m: &AccessPoint| { &m.ssid },
            |m: &mut AccessPoint| { &mut m.ssid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bssid",
            |m: &AccessPoint| { &m.bssid },
            |m: &mut AccessPoint| { &mut m.bssid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "channel",
            |m: &AccessPoint| { &m.channel },
            |m: &mut AccessPoint| { &mut m.channel },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "hw_mode",
            |m: &AccessPoint| { &m.hw_mode },
            |m: &mut AccessPoint| { &mut m.hw_mode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "wpa_passphrase",
            |m: &AccessPoint| { &m.wpa_passphrase },
            |m: &mut AccessPoint| { &mut m.wpa_passphrase },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "beacon_interval",
            |m: &AccessPoint| { &m.beacon_interval },
            |m: &mut AccessPoint| { &mut m.beacon_interval },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "country_code",
            |m: &AccessPoint| { &m.country_code },
            |m: &mut AccessPoint| { &mut m.country_code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "dtim_period",
            |m: &AccessPoint| { &m.dtim_period },
            |m: &mut AccessPoint| { &mut m.dtim_period },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "hidden_ssid",
            |m: &AccessPoint| { &m.hidden_ssid },
            |m: &mut AccessPoint| { &mut m.hidden_ssid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sae",
            |m: &AccessPoint| { &m.sae },
            |m: &mut AccessPoint| { &mut m.sae },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "wmm_enabled",
            |m: &AccessPoint| { &m.wmm_enabled },
            |m: &mut AccessPoint| { &mut m.wmm_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "enterprise_enabled",
            |m: &AccessPoint| { &m.enterprise_enabled },
            |m: &mut AccessPoint| { &mut m.enterprise_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mac_acl_mode",
            |m: &AccessPoint| { &m.mac_acl_mode },
            |m: &mut AccessPoint| { &mut m.mac_acl_mode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "mac_acl_list",
            |m: &AccessPoint| { &m.mac_acl_list },
            |m: &mut AccessPoint| { &mut m.mac_acl_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ftm_responder_enabled",
            |m: &AccessPoint| { &m.ftm_responder_enabled },
            |m: &mut AccessPoint| { &mut m.ftm_responder_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "connected_devices",
            |m: &AccessPoint| { &m.connected_devices },
            |m: &mut AccessPoint| { &mut m.connected_devices },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AccessPoint>(
            "AccessPoint",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AccessPoint {
    const NAME: &'static str = "AccessPoint";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                18 => {
                    self.ssid = is.read_string()?;
                },
                26 => {
                    self.bssid = is.read_string()?;
                },
                32 => {
                    self.channel = is.read_uint32()?;
                },
                42 => {
                    self.hw_mode = is.read_string()?;
                },
                50 => {
                    self.wpa_passphrase = is.read_string()?;
                },
                56 => {
                    self.beacon_interval = is.read_uint32()?;
                },
                66 => {
                    self.country_code = is.read_string()?;
                },
                72 => {
                    self.dtim_period = is.read_uint32()?;
                },
                80 => {
                    self.hidden_ssid = is.read_bool()?;
                },
                88 => {
                    self.sae = is.read_bool()?;
                },
                96 => {
                    self.wmm_enabled = is.read_bool()?;
                },
                104 => {
                    self.enterprise_enabled = is.read_bool()?;
                },
                112 => {
                    self.mac_acl_mode = is.read_uint32()?;
                },
                122 => {
                    self.mac_acl_list.push(is.read_string()?);
                },
                128 => {
                    self.ftm_responder_enabled = is.read_bool()?;
                },
                138 => {
                    self.connected_devices.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        if !self.ssid.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.ssid);
        }
        if !self.bssid.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.bssid);
        }
        if self.channel != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.channel);
        }
        if !self.hw_mode.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.hw_mode);
        }
        if !self.wpa_passphrase.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.wpa_passphrase);
        }
        if self.beacon_interval != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.beacon_interval);
        }
        if !self.country_code.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.country_code);
        }
        if self.dtim_period != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.dtim_period);
        }
        if self.hidden_ssid != false {
            my_size += 1 + 1;
        }
        if self.sae != false {
            my_size += 1 + 1;
        }
        if self.wmm_enabled != false {
            my_size += 1 + 1;
        }
        if self.enterprise_enabled != false {
            my_size += 1 + 1;
        }
        if self.mac_acl_mode != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.mac_acl_mode);
        }
        for value in &self.mac_acl_list {
            my_size += ::protobuf::rt::string_size(15, &value);
        };
        if self.ftm_responder_enabled != false {
            my_size += 2 + 1;
        }
        for value in &self.connected_devices {
            my_size += ::protobuf::rt::string_size(17, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        if !self.ssid.is_empty() {
            os.write_string(2, &self.ssid)?;
        }
        if !self.bssid.is_empty() {
            os.write_string(3, &self.bssid)?;
        }
        if self.channel != 0 {
            os.write_uint32(4, self.channel)?;
        }
        if !self.hw_mode.is_empty() {
            os.write_string(5, &self.hw_mode)?;
        }
        if !self.wpa_passphrase.is_empty() {
            os.write_string(6, &self.wpa_passphrase)?;
        }
        if self.beacon_interval != 0 {
            os.write_uint32(7, self.beacon_interval)?;
        }
        if !self.country_code.is_empty() {
            os.write_string(8, &self.country_code)?;
        }
        if self.dtim_period != 0 {
            os.write_uint32(9, self.dtim_period)?;
        }
        if self.hidden_ssid != false {
            os.write_bool(10, self.hidden_ssid)?;
        }
        if self.sae != false {
            os.write_bool(11, self.sae)?;
        }
        if self.wmm_enabled != false {
            os.write_bool(12, self.wmm_enabled)?;
        }
        if self.enterprise_enabled != false {
            os.write_bool(13, self.enterprise_enabled)?;
        }
        if self.mac_acl_mode != 0 {
            os.write_uint32(14, self.mac_acl_mode)?;
        }
        for v in &self.mac_acl_list {
            os.write_string(15, &v)?;
        };
        if self.ftm_responder_enabled != false {
            os.write_bool(16, self.ftm_responder_enabled)?;
        }
        for v in &self.connected_devices {
            os.write_string(17, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AccessPoint {
        AccessPoint::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.ssid.clear();
        self.bssid.clear();
        self.channel = 0;
        self.hw_mode.clear();
        self.wpa_passphrase.clear();
        self.beacon_interval = 0;
        self.country_code.clear();
        self.dtim_period = 0;
        self.hidden_ssid = false;
        self.sae = false;
        self.wmm_enabled = false;
        self.enterprise_enabled = false;
        self.mac_acl_mode = 0;
        self.mac_acl_list.clear();
        self.ftm_responder_enabled = false;
        self.connected_devices.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AccessPoint {
        static instance: AccessPoint = AccessPoint {
            id: 0,
            ssid: ::std::string::String::new(),
            bssid: ::std::string::String::new(),
            channel: 0,
            hw_mode: ::std::string::String::new(),
            wpa_passphrase: ::std::string::String::new(),
            beacon_interval: 0,
            country_code: ::std::string::String::new(),
            dtim_period: 0,
            hidden_ssid: false,
            sae: false,
            wmm_enabled: false,
            enterprise_enabled: false,
            mac_acl_mode: 0,
            mac_acl_list: ::std::vec::Vec::new(),
            ftm_responder_enabled: false,
            connected_devices: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AccessPoint {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AccessPoint").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AccessPoint {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AccessPoint {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.CreateAccessPointRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CreateAccessPointRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.CreateAccessPointRequest.access_point)
    pub access_point: ::protobuf::MessageField<AccessPoint>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.CreateAccessPointRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreateAccessPointRequest {
    fn default() -> &'a CreateAccessPointRequest {
        <CreateAccessPointRequest as ::protobuf::Message>::default_instance()
    }
}

impl CreateAccessPointRequest {
    pub fn new() -> CreateAccessPointRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, AccessPoint>(
            "access_point",
            |m: &CreateAccessPointRequest| { &m.access_point },
            |m: &mut CreateAccessPointRequest| { &mut m.access_point },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreateAccessPointRequest>(
            "CreateAccessPointRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreateAccessPointRequest {
    const NAME: &'static str = "CreateAccessPointRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.access_point)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.access_point.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.access_point.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreateAccessPointRequest {
        CreateAccessPointRequest::new()
    }

    fn clear(&mut self) {
        self.access_point.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreateAccessPointRequest {
        static instance: CreateAccessPointRequest = CreateAccessPointRequest {
            access_point: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreateAccessPointRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreateAccessPointRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreateAccessPointRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateAccessPointRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.GetAccessPointRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetAccessPointRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.GetAccessPointRequest.id)
    pub id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.GetAccessPointRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetAccessPointRequest {
    fn default() -> &'a GetAccessPointRequest {
        <GetAccessPointRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetAccessPointRequest {
    pub fn new() -> GetAccessPointRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &GetAccessPointRequest| { &m.id },
            |m: &mut GetAccessPointRequest| { &mut m.id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetAccessPointRequest>(
            "GetAccessPointRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetAccessPointRequest {
    const NAME: &'static str = "GetAccessPointRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetAccessPointRequest {
        GetAccessPointRequest::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetAccessPointRequest {
        static instance: GetAccessPointRequest = GetAccessPointRequest {
            id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetAccessPointRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetAccessPointRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetAccessPointRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetAccessPointRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.UpdateAccessPointRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UpdateAccessPointRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.UpdateAccessPointRequest.id)
    pub id: u32,
    ///  Fields to update.
    // @@protoc_insertion_point(field:netsim.access_point.UpdateAccessPointRequest.ssid)
    pub ssid: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:netsim.access_point.UpdateAccessPointRequest.channel)
    pub channel: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.UpdateAccessPointRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UpdateAccessPointRequest {
    fn default() -> &'a UpdateAccessPointRequest {
        <UpdateAccessPointRequest as ::protobuf::Message>::default_instance()
    }
}

impl UpdateAccessPointRequest {
    pub fn new() -> UpdateAccessPointRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &UpdateAccessPointRequest| { &m.id },
            |m: &mut UpdateAccessPointRequest| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "ssid",
            |m: &UpdateAccessPointRequest| { &m.ssid },
            |m: &mut UpdateAccessPointRequest| { &mut m.ssid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "channel",
            |m: &UpdateAccessPointRequest| { &m.channel },
            |m: &mut UpdateAccessPointRequest| { &mut m.channel },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UpdateAccessPointRequest>(
            "UpdateAccessPointRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UpdateAccessPointRequest {
    const NAME: &'static str = "UpdateAccessPointRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                18 => {
                    self.ssid = ::std::option::Option::Some(is.read_string()?);
                },
                24 => {
                    self.channel = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        if let Some(v) = self.ssid.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.channel {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        if let Some(v) = self.ssid.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.channel {
            os.write_uint32(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UpdateAccessPointRequest {
        UpdateAccessPointRequest::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.ssid = ::std::option::Option::None;
        self.channel = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UpdateAccessPointRequest {
        static instance: UpdateAccessPointRequest = UpdateAccessPointRequest {
            id: 0,
            ssid: ::std::option::Option::None,
            channel: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UpdateAccessPointRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UpdateAccessPointRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UpdateAccessPointRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateAccessPointRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.DisconnectRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DisconnectRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.DisconnectRequest.mac_address)
    pub mac_address: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.DisconnectRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DisconnectRequest {
    fn default() -> &'a DisconnectRequest {
        <DisconnectRequest as ::protobuf::Message>::default_instance()
    }
}

impl DisconnectRequest {
    pub fn new() -> DisconnectRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mac_address",
            |m: &DisconnectRequest| { &m.mac_address },
            |m: &mut DisconnectRequest| { &mut m.mac_address },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DisconnectRequest>(
            "DisconnectRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DisconnectRequest {
    const NAME: &'static str = "DisconnectRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.mac_address = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.mac_address.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.mac_address);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.mac_address.is_empty() {
            os.write_string(1, &self.mac_address)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DisconnectRequest {
        DisconnectRequest::new()
    }

    fn clear(&mut self) {
        self.mac_address.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DisconnectRequest {
        static instance: DisconnectRequest = DisconnectRequest {
            mac_address: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DisconnectRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DisconnectRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DisconnectRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DisconnectRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.DeleteAccessPointRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DeleteAccessPointRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.DeleteAccessPointRequest.id)
    pub id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.DeleteAccessPointRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DeleteAccessPointRequest {
    fn default() -> &'a DeleteAccessPointRequest {
        <DeleteAccessPointRequest as ::protobuf::Message>::default_instance()
    }
}

impl DeleteAccessPointRequest {
    pub fn new() -> DeleteAccessPointRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &DeleteAccessPointRequest| { &m.id },
            |m: &mut DeleteAccessPointRequest| { &mut m.id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DeleteAccessPointRequest>(
            "DeleteAccessPointRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DeleteAccessPointRequest {
    const NAME: &'static str = "DeleteAccessPointRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DeleteAccessPointRequest {
        DeleteAccessPointRequest::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DeleteAccessPointRequest {
        static instance: DeleteAccessPointRequest = DeleteAccessPointRequest {
            id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DeleteAccessPointRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DeleteAccessPointRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DeleteAccessPointRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteAccessPointRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.ListAccessPointsRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListAccessPointsRequest {
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.ListAccessPointsRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListAccessPointsRequest {
    fn default() -> &'a ListAccessPointsRequest {
        <ListAccessPointsRequest as ::protobuf::Message>::default_instance()
    }
}

impl ListAccessPointsRequest {
    pub fn new() -> ListAccessPointsRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListAccessPointsRequest>(
            "ListAccessPointsRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListAccessPointsRequest {
    const NAME: &'static str = "ListAccessPointsRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListAccessPointsRequest {
        ListAccessPointsRequest::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListAccessPointsRequest {
        static instance: ListAccessPointsRequest = ListAccessPointsRequest {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListAccessPointsRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListAccessPointsRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListAccessPointsRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListAccessPointsRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.access_point.ListAccessPointsResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListAccessPointsResponse {
    // message fields
    // @@protoc_insertion_point(field:netsim.access_point.ListAccessPointsResponse.access_points)
    pub access_points: ::std::vec::Vec<AccessPoint>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.access_point.ListAccessPointsResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListAccessPointsResponse {
    fn default() -> &'a ListAccessPointsResponse {
        <ListAccessPointsResponse as ::protobuf::Message>::default_instance()
    }
}

impl ListAccessPointsResponse {
    pub fn new() -> ListAccessPointsResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "access_points",
            |m: &ListAccessPointsResponse| { &m.access_points },
            |m: &mut ListAccessPointsResponse| { &mut m.access_points },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListAccessPointsResponse>(
            "ListAccessPointsResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListAccessPointsResponse {
    const NAME: &'static str = "ListAccessPointsResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.access_points.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.access_points {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.access_points {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListAccessPointsResponse {
        ListAccessPointsResponse::new()
    }

    fn clear(&mut self) {
        self.access_points.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListAccessPointsResponse {
        static instance: ListAccessPointsResponse = ListAccessPointsResponse {
            access_points: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListAccessPointsResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListAccessPointsResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListAccessPointsResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListAccessPointsResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19netsim/access_point.proto\x12\x13netsim.access_point\x1a\x1bgoogle\
    /protobuf/empty.proto\"\x7f\n\x19ExecuteAccessPointRequest\x12\x0e\n\x02\
    id\x18\x01\x20\x01(\rR\x02id\x12H\n\ndisconnect\x18\x02\x20\x01(\x0b2&.n\
    etsim.access_point.DisconnectRequestH\0R\ndisconnectB\x08\n\x06action\"\
    \xb6\x04\n\x0bAccessPoint\x12\x0e\n\x02id\x18\x01\x20\x01(\rR\x02id\x12\
    \x12\n\x04ssid\x18\x02\x20\x01(\tR\x04ssid\x12\x14\n\x05bssid\x18\x03\
    \x20\x01(\tR\x05bssid\x12\x18\n\x07channel\x18\x04\x20\x01(\rR\x07channe\
    l\x12\x17\n\x07hw_mode\x18\x05\x20\x01(\tR\x06hwMode\x12%\n\x0ewpa_passp\
    hrase\x18\x06\x20\x01(\tR\rwpaPassphrase\x12'\n\x0fbeacon_interval\x18\
    \x07\x20\x01(\rR\x0ebeaconInterval\x12!\n\x0ccountry_code\x18\x08\x20\
    \x01(\tR\x0bcountryCode\x12\x1f\n\x0bdtim_period\x18\t\x20\x01(\rR\ndtim\
    Period\x12\x1f\n\x0bhidden_ssid\x18\n\x20\x01(\x08R\nhiddenSsid\x12\x10\
    \n\x03sae\x18\x0b\x20\x01(\x08R\x03sae\x12\x1f\n\x0bwmm_enabled\x18\x0c\
    \x20\x01(\x08R\nwmmEnabled\x12-\n\x12enterprise_enabled\x18\r\x20\x01(\
    \x08R\x11enterpriseEnabled\x12\x20\n\x0cmac_acl_mode\x18\x0e\x20\x01(\rR\
    \nmacAclMode\x12\x20\n\x0cmac_acl_list\x18\x0f\x20\x03(\tR\nmacAclList\
    \x122\n\x15ftm_responder_enabled\x18\x10\x20\x01(\x08R\x13ftmResponderEn\
    abled\x12+\n\x11connected_devices\x18\x11\x20\x03(\tR\x10connectedDevice\
    s\"_\n\x18CreateAccessPointRequest\x12C\n\x0caccess_point\x18\x01\x20\
    \x01(\x0b2\x20.netsim.access_point.AccessPointR\x0baccessPoint\"'\n\x15G\
    etAccessPointRequest\x12\x0e\n\x02id\x18\x01\x20\x01(\rR\x02id\"w\n\x18U\
    pdateAccessPointRequest\x12\x0e\n\x02id\x18\x01\x20\x01(\rR\x02id\x12\
    \x17\n\x04ssid\x18\x02\x20\x01(\tH\0R\x04ssid\x88\x01\x01\x12\x1d\n\x07c\
    hannel\x18\x03\x20\x01(\rH\x01R\x07channel\x88\x01\x01B\x07\n\x05_ssidB\
    \n\n\x08_channel\"4\n\x11DisconnectRequest\x12\x1f\n\x0bmac_address\x18\
    \x01\x20\x01(\tR\nmacAddress\"*\n\x18DeleteAccessPointRequest\x12\x0e\n\
    \x02id\x18\x01\x20\x01(\rR\x02id\"\x19\n\x17ListAccessPointsRequest\"a\n\
    \x18ListAccessPointsResponse\x12E\n\raccess_points\x18\x01\x20\x03(\x0b2\
    \x20.netsim.access_point.AccessPointR\x0caccessPoints2\xa8\x04\n\x12Acce\
    ssPointService\x12Y\n\x06Create\x12-.netsim.access_point.CreateAccessPoi\
    ntRequest\x1a\x20.netsim.access_point.AccessPoint\x12S\n\x03Get\x12*.net\
    sim.access_point.GetAccessPointRequest\x1a\x20.netsim.access_point.Acces\
    sPoint\x12Y\n\x06Update\x12-.netsim.access_point.UpdateAccessPointReques\
    t\x1a\x20.netsim.access_point.AccessPoint\x12O\n\x06Delete\x12-.netsim.a\
    ccess_point.DeleteAccessPointRequest\x1a\x16.google.protobuf.Empty\x12c\
    \n\x04List\x12,.netsim.access_point.ListAccessPointsRequest\x1a-.netsim.\
    access_point.ListAccessPointsResponse\x12Q\n\x07Execute\x12..netsim.acce\
    ss_point.ExecuteAccessPointRequest\x1a\x16.google.protobuf.EmptyJ\xd8\
    \x14\n\x06\x12\x04\x03\0S\x01\n_\n\x01\x0c\x12\x03\x03\0\x122U\x20Copyri\
    ght\x202026\x20The\x20Android\x20Open\x20Source\x20Project\n\x20SPDX-Lic\
    ense-Identifier:\x20Apache-2.0\n\n\x08\n\x01\x02\x12\x03\x04\0\x1c\n\t\n\
    \x02\x03\0\x12\x03\x06\0%\n\n\n\x02\x06\0\x12\x04\x08\0\x1a\x01\n\n\n\
    \x03\x06\0\x01\x12\x03\x08\x08\x1a\n)\n\x04\x06\0\x02\0\x12\x03\n\x02=\
    \x1a\x1c\x20Create\x20a\x20new\x20Access\x20Point.\n\n\x0c\n\x05\x06\0\
    \x02\0\x01\x12\x03\n\x06\x0c\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\n\r%\n\
    \x0c\n\x05\x06\0\x02\0\x03\x12\x03\n0;\n,\n\x04\x06\0\x02\x01\x12\x03\r\
    \x027\x1a\x1f\x20Get\x20an\x20existing\x20Access\x20Point.\n\n\x0c\n\x05\
    \x06\0\x02\x01\x01\x12\x03\r\x06\t\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\
    \r\n\x1f\n\x0c\n\x05\x06\0\x02\x01\x03\x12\x03\r*5\n/\n\x04\x06\0\x02\
    \x02\x12\x03\x10\x02=\x1a\"\x20Update\x20an\x20existing\x20Access\x20Poi\
    nt.\n\n\x0c\n\x05\x06\0\x02\x02\x01\x12\x03\x10\x06\x0c\n\x0c\n\x05\x06\
    \0\x02\x02\x02\x12\x03\x10\r%\n\x0c\n\x05\x06\0\x02\x02\x03\x12\x03\x100\
    ;\n/\n\x04\x06\0\x02\x03\x12\x03\x13\x02G\x1a\"\x20Delete\x20an\x20exist\
    ing\x20Access\x20Point.\n\n\x0c\n\x05\x06\0\x02\x03\x01\x12\x03\x13\x06\
    \x0c\n\x0c\n\x05\x06\0\x02\x03\x02\x12\x03\x13\r%\n\x0c\n\x05\x06\0\x02\
    \x03\x03\x12\x03\x130E\n&\n\x04\x06\0\x02\x04\x12\x03\x16\x02G\x1a\x19\
    \x20List\x20all\x20Access\x20Points.\n\n\x0c\n\x05\x06\0\x02\x04\x01\x12\
    \x03\x16\x06\n\n\x0c\n\x05\x06\0\x02\x04\x02\x12\x03\x16\x0b\"\n\x0c\n\
    \x05\x06\0\x02\x04\x03\x12\x03\x16-E\n4\n\x04\x06\0\x02\x05\x12\x03\x19\
    \x02I\x1a'\x20Execute\x20an\x20action\x20on\x20an\x20Access\x20Point.\n\
    \n\x0c\n\x05\x06\0\x02\x05\x01\x12\x03\x19\x06\r\n\x0c\n\x05\x06\0\x02\
    \x05\x02\x12\x03\x19\x0e'\n\x0c\n\x05\x06\0\x02\x05\x03\x12\x03\x192G\n\
    \n\n\x02\x04\0\x12\x04\x1c\0!\x01\n\n\n\x03\x04\0\x01\x12\x03\x1c\x08!\n\
    \x0b\n\x04\x04\0\x02\0\x12\x03\x1d\x02\x10\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x1d\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x1d\t\x0b\n\x0c\
    \n\x05\x04\0\x02\0\x03\x12\x03\x1d\x0e\x0f\n\x0c\n\x04\x04\0\x08\0\x12\
    \x04\x1e\x02\x20\x03\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x1e\x08\x0e\n\
    \x0b\n\x04\x04\0\x02\x01\x12\x03\x1f\x04%\n\x0c\n\x05\x04\0\x02\x01\x06\
    \x12\x03\x1f\x04\x15\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x1f\x16\x20\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x1f#$\n\n\n\x02\x04\x01\x12\x04#\06\
    \x01\n\n\n\x03\x04\x01\x01\x12\x03#\x08\x13\n8\n\x04\x04\x01\x02\0\x12\
    \x03%\x02\x10\x1a+\x20ID\x20is\x20the\x20Chip\x20ID\x20in\x20netsim\x20a\
    rchitecture.\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03%\x02\x08\n\x0c\n\
    \x05\x04\x01\x02\0\x01\x12\x03%\t\x0b\n\x0c\n\x05\x04\x01\x02\0\x03\x12\
    \x03%\x0e\x0f\n\x0b\n\x04\x04\x01\x02\x01\x12\x03&\x02\x12\n\x0c\n\x05\
    \x04\x01\x02\x01\x05\x12\x03&\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\
    \x12\x03&\t\r\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03&\x10\x11\n$\n\x04\
    \x04\x01\x02\x02\x12\x03'\x02\x13\"\x17\x20formatted\x20MAC\x20address\n\
    \n\x0c\n\x05\x04\x01\x02\x02\x05\x12\x03'\x02\x08\n\x0c\n\x05\x04\x01\
    \x02\x02\x01\x12\x03'\t\x0e\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03'\x11\
    \x12\n\x0b\n\x04\x04\x01\x02\x03\x12\x03(\x02\x15\n\x0c\n\x05\x04\x01\
    \x02\x03\x05\x12\x03(\x02\x08\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03(\t\
    \x10\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03(\x13\x14\n-\n\x04\x04\x01\
    \x02\x04\x12\x03)\x02\x15\"\x20\x20\"a\",\x20\"b\",\x20\"g\",\x20\"n\",\
    \x20\"ac\",\x20\"ax\"\n\n\x0c\n\x05\x04\x01\x02\x04\x05\x12\x03)\x02\x08\
    \n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x03)\t\x10\n\x0c\n\x05\x04\x01\x02\
    \x04\x03\x12\x03)\x13\x14\n\x17\n\x04\x04\x01\x02\x05\x12\x03*\x02\x1c\"\
    \n\x20optional\n\n\x0c\n\x05\x04\x01\x02\x05\x05\x12\x03*\x02\x08\n\x0c\
    \n\x05\x04\x01\x02\x05\x01\x12\x03*\t\x17\n\x0c\n\x05\x04\x01\x02\x05\
    \x03\x12\x03*\x1a\x1b\n\x0b\n\x04\x04\x01\x02\x06\x12\x03+\x02\x1d\n\x0c\
    \n\x05\x04\x01\x02\x06\x05\x12\x03+\x02\x08\n\x0c\n\x05\x04\x01\x02\x06\
    \x01\x12\x03+\t\x18\n\x0c\n\x05\x04\x01\x02\x06\x03\x12\x03+\x1b\x1c\n\
    \x0b\n\x04\x04\x01\x02\x07\x12\x03,\x02\x1a\n\x0c\n\x05\x04\x01\x02\x07\
    \x05\x12\x03,\x02\x08\n\x0c\n\x05\x04\x01\x02\x07\x01\x12\x03,\t\x15\n\
    \x0c\n\x05\x04\x01\x02\x07\x03\x12\x03,\x18\x19\n\x0b\n\x04\x04\x01\x02\
    \x08\x12\x03-\x02\x19\n\x0c\n\x05\x04\x01\x02\x08\x05\x12\x03-\x02\x08\n\
    \x0c\n\x05\x04\x01\x02\x08\x01\x12\x03-\t\x14\n\x0c\n\x05\x04\x01\x02\
    \x08\x03\x12\x03-\x17\x18\n\x0b\n\x04\x04\x01\x02\t\x12\x03.\x02\x18\n\
    \x0c\n\x05\x04\x01\x02\t\x05\x12\x03.\x02\x06\n\x0c\n\x05\x04\x01\x02\t\
    \x01\x12\x03.\x07\x12\n\x0c\n\x05\x04\x01\x02\t\x03\x12\x03.\x15\x17\n\
    \x0b\n\x04\x04\x01\x02\n\x12\x03/\x02\x10\n\x0c\n\x05\x04\x01\x02\n\x05\
    \x12\x03/\x02\x06\n\x0c\n\x05\x04\x01\x02\n\x01\x12\x03/\x07\n\n\x0c\n\
    \x05\x04\x01\x02\n\x03\x12\x03/\r\x0f\n\x0b\n\x04\x04\x01\x02\x0b\x12\
    \x030\x02\x18\n\x0c\n\x05\x04\x01\x02\x0b\x05\x12\x030\x02\x06\n\x0c\n\
    \x05\x04\x01\x02\x0b\x01\x12\x030\x07\x12\n\x0c\n\x05\x04\x01\x02\x0b\
    \x03\x12\x030\x15\x17\n\x0b\n\x04\x04\x01\x02\x0c\x12\x031\x02\x1f\n\x0c\
    \n\x05\x04\x01\x02\x0c\x05\x12\x031\x02\x06\n\x0c\n\x05\x04\x01\x02\x0c\
    \x01\x12\x031\x07\x19\n\x0c\n\x05\x04\x01\x02\x0c\x03\x12\x031\x1c\x1e\n\
    )\n\x04\x04\x01\x02\r\x12\x032\x02\x1b\"\x1c\x200=Disable,\x201=Deny,\
    \x202=Allow\n\n\x0c\n\x05\x04\x01\x02\r\x05\x12\x032\x02\x08\n\x0c\n\x05\
    \x04\x01\x02\r\x01\x12\x032\t\x15\n\x0c\n\x05\x04\x01\x02\r\x03\x12\x032\
    \x18\x1a\n\x0b\n\x04\x04\x01\x02\x0e\x12\x033\x02$\n\x0c\n\x05\x04\x01\
    \x02\x0e\x04\x12\x033\x02\n\n\x0c\n\x05\x04\x01\x02\x0e\x05\x12\x033\x0b\
    \x11\n\x0c\n\x05\x04\x01\x02\x0e\x01\x12\x033\x12\x1e\n\x0c\n\x05\x04\
    \x01\x02\x0e\x03\x12\x033!#\n\x0b\n\x04\x04\x01\x02\x0f\x12\x034\x02\"\n\
    \x0c\n\x05\x04\x01\x02\x0f\x05\x12\x034\x02\x06\n\x0c\n\x05\x04\x01\x02\
    \x0f\x01\x12\x034\x07\x1c\n\x0c\n\x05\x04\x01\x02\x0f\x03\x12\x034\x1f!\
    \n\x0b\n\x04\x04\x01\x02\x10\x12\x035\x02)\n\x0c\n\x05\x04\x01\x02\x10\
    \x04\x12\x035\x02\n\n\x0c\n\x05\x04\x01\x02\x10\x05\x12\x035\x0b\x11\n\
    \x0c\n\x05\x04\x01\x02\x10\x01\x12\x035\x12#\n\x0c\n\x05\x04\x01\x02\x10\
    \x03\x12\x035&(\n\n\n\x02\x04\x02\x12\x048\0:\x01\n\n\n\x03\x04\x02\x01\
    \x12\x038\x08\x20\n\x0b\n\x04\x04\x02\x02\0\x12\x039\x02\x1f\n\x0c\n\x05\
    \x04\x02\x02\0\x06\x12\x039\x02\r\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x039\
    \x0e\x1a\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x039\x1d\x1e\n\n\n\x02\x04\
    \x03\x12\x04<\0>\x01\n\n\n\x03\x04\x03\x01\x12\x03<\x08\x1d\n\x0b\n\x04\
    \x04\x03\x02\0\x12\x03=\x02\x10\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03=\
    \x02\x08\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03=\t\x0b\n\x0c\n\x05\x04\
    \x03\x02\0\x03\x12\x03=\x0e\x0f\n\n\n\x02\x04\x04\x12\x04@\0E\x01\n\n\n\
    \x03\x04\x04\x01\x12\x03@\x08\x20\n\x0b\n\x04\x04\x04\x02\0\x12\x03A\x02\
    \x10\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03A\x02\x08\n\x0c\n\x05\x04\x04\
    \x02\0\x01\x12\x03A\t\x0b\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03A\x0e\x0f\
    \n\x20\n\x04\x04\x04\x02\x01\x12\x03C\x02\x1b\x1a\x13\x20Fields\x20to\
    \x20update.\n\n\x0c\n\x05\x04\x04\x02\x01\x04\x12\x03C\x02\n\n\x0c\n\x05\
    \x04\x04\x02\x01\x05\x12\x03C\x0b\x11\n\x0c\n\x05\x04\x04\x02\x01\x01\
    \x12\x03C\x12\x16\n\x0c\n\x05\x04\x04\x02\x01\x03\x12\x03C\x19\x1a\n\x0b\
    \n\x04\x04\x04\x02\x02\x12\x03D\x02\x1e\n\x0c\n\x05\x04\x04\x02\x02\x04\
    \x12\x03D\x02\n\n\x0c\n\x05\x04\x04\x02\x02\x05\x12\x03D\x0b\x11\n\x0c\n\
    \x05\x04\x04\x02\x02\x01\x12\x03D\x12\x19\n\x0c\n\x05\x04\x04\x02\x02\
    \x03\x12\x03D\x1c\x1d\n\n\n\x02\x04\x05\x12\x04G\0I\x01\n\n\n\x03\x04\
    \x05\x01\x12\x03G\x08\x19\n\x0b\n\x04\x04\x05\x02\0\x12\x03H\x02\x19\n\
    \x0c\n\x05\x04\x05\x02\0\x05\x12\x03H\x02\x08\n\x0c\n\x05\x04\x05\x02\0\
    \x01\x12\x03H\t\x14\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03H\x17\x18\n\n\n\
    \x02\x04\x06\x12\x04K\0M\x01\n\n\n\x03\x04\x06\x01\x12\x03K\x08\x20\n\
    \x0b\n\x04\x04\x06\x02\0\x12\x03L\x02\x10\n\x0c\n\x05\x04\x06\x02\0\x05\
    \x12\x03L\x02\x08\n\x0c\n\x05\x04\x06\x02\0\x01\x12\x03L\t\x0b\n\x0c\n\
    \x05\x04\x06\x02\0\x03\x12\x03L\x0e\x0f\n\t\n\x02\x04\x07\x12\x03O\0\"\n\
    \n\n\x03\x04\x07\x01\x12\x03O\x08\x1f\n\n\n\x02\x04\x08\x12\x04Q\0S\x01\
    \n\n\n\x03\x04\x08\x01\x12\x03Q\x08\x20\n\x0b\n\x04\x04\x08\x02\0\x12\
    \x03R\x02)\n\x0c\n\x05\x04\x08\x02\0\x04\x12\x03R\x02\n\n\x0c\n\x05\x04\
    \x08\x02\0\x06\x12\x03R\x0b\x16\n\x0c\n\x05\x04\x08\x02\0\x01\x12\x03R\
    \x17$\n\x0c\n\x05\x04\x08\x02\0\x03\x12\x03R'(b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::well_known_types::empty::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(9);
            messages.push(ExecuteAccessPointRequest::generated_message_descriptor_data());
            messages.push(AccessPoint::generated_message_descriptor_data());
            messages.push(CreateAccessPointRequest::generated_message_descriptor_data());
            messages.push(GetAccessPointRequest::generated_message_descriptor_data());
            messages.push(UpdateAccessPointRequest::generated_message_descriptor_data());
            messages.push(DisconnectRequest::generated_message_descriptor_data());
            messages.push(DeleteAccessPointRequest::generated_message_descriptor_data());
            messages.push(ListAccessPointsRequest::generated_message_descriptor_data());
            messages.push(ListAccessPointsResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
