// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/ble_service.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:netsim.ble_service.ScanRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ScanRequest {
    // message fields
    ///  Initial physical position of the scanner in the simulation.
    // @@protoc_insertion_point(field:netsim.ble_service.ScanRequest.position)
    pub position: ::protobuf::MessageField<super::model::Position>,
    ///  Set to true to use Active Scanning (0x01) instead of Passive Scanning
    ///  (0x00). Active Scanning will trigger Scan Responses from nearby devices.
    // @@protoc_insertion_point(field:netsim.ble_service.ScanRequest.active)
    pub active: bool,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.ble_service.ScanRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ScanRequest {
    fn default() -> &'a ScanRequest {
        <ScanRequest as ::protobuf::Message>::default_instance()
    }
}

impl ScanRequest {
    pub fn new() -> ScanRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::model::Position>(
            "position",
            |m: &ScanRequest| { &m.position },
            |m: &mut ScanRequest| { &mut m.position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "active",
            |m: &ScanRequest| { &m.active },
            |m: &mut ScanRequest| { &mut m.active },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ScanRequest>(
            "ScanRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ScanRequest {
    const NAME: &'static str = "ScanRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.position)?;
                },
                16 => {
                    self.active = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.position.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.active != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.position.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.active != false {
            os.write_bool(2, self.active)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ScanRequest {
        ScanRequest::new()
    }

    fn clear(&mut self) {
        self.position.clear();
        self.active = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ScanRequest {
        static instance: ScanRequest = ScanRequest {
            position: ::protobuf::MessageField::none(),
            active: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ScanRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ScanRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ScanRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ScanRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.ble_service.ScanResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ScanResponse {
    // message fields
    ///  Raw HCI event packet
    // @@protoc_insertion_point(field:netsim.ble_service.ScanResponse.packet)
    pub packet: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.ble_service.ScanResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ScanResponse {
    fn default() -> &'a ScanResponse {
        <ScanResponse as ::protobuf::Message>::default_instance()
    }
}

impl ScanResponse {
    pub fn new() -> ScanResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "packet",
            |m: &ScanResponse| { &m.packet },
            |m: &mut ScanResponse| { &mut m.packet },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ScanResponse>(
            "ScanResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ScanResponse {
    const NAME: &'static str = "ScanResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.packet = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.packet.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.packet);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.packet.is_empty() {
            os.write_bytes(1, &self.packet)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ScanResponse {
        ScanResponse::new()
    }

    fn clear(&mut self) {
        self.packet.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ScanResponse {
        static instance: ScanResponse = ScanResponse {
            packet: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ScanResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ScanResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ScanResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ScanResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.ble_service.SniffRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SniffRequest {
    // message fields
    ///  Initial physical position of the sniffer in the simulation.
    // @@protoc_insertion_point(field:netsim.ble_service.SniffRequest.position)
    pub position: ::protobuf::MessageField<super::model::Position>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.ble_service.SniffRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SniffRequest {
    fn default() -> &'a SniffRequest {
        <SniffRequest as ::protobuf::Message>::default_instance()
    }
}

impl SniffRequest {
    pub fn new() -> SniffRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::model::Position>(
            "position",
            |m: &SniffRequest| { &m.position },
            |m: &mut SniffRequest| { &mut m.position },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SniffRequest>(
            "SniffRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SniffRequest {
    const NAME: &'static str = "SniffRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.position)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.position.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.position.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SniffRequest {
        SniffRequest::new()
    }

    fn clear(&mut self) {
        self.position.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SniffRequest {
        static instance: SniffRequest = SniffRequest {
            position: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SniffRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SniffRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SniffRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SniffRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.ble_service.SniffResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SniffResponse {
    // message fields
    ///  Raw link-layer packet (Baseband trace)
    // @@protoc_insertion_point(field:netsim.ble_service.SniffResponse.packet)
    pub packet: ::std::vec::Vec<u8>,
    ///  Timestamp of the packet in microseconds since the UNIX epoch.
    // @@protoc_insertion_point(field:netsim.ble_service.SniffResponse.timestamp)
    pub timestamp: i64,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.ble_service.SniffResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SniffResponse {
    fn default() -> &'a SniffResponse {
        <SniffResponse as ::protobuf::Message>::default_instance()
    }
}

impl SniffResponse {
    pub fn new() -> SniffResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "packet",
            |m: &SniffResponse| { &m.packet },
            |m: &mut SniffResponse| { &mut m.packet },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "timestamp",
            |m: &SniffResponse| { &m.timestamp },
            |m: &mut SniffResponse| { &mut m.timestamp },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SniffResponse>(
            "SniffResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SniffResponse {
    const NAME: &'static str = "SniffResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.packet = is.read_bytes()?;
                },
                16 => {
                    self.timestamp = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.packet.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.packet);
        }
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.timestamp);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.packet.is_empty() {
            os.write_bytes(1, &self.packet)?;
        }
        if self.timestamp != 0 {
            os.write_int64(2, self.timestamp)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SniffResponse {
        SniffResponse::new()
    }

    fn clear(&mut self) {
        self.packet.clear();
        self.timestamp = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SniffResponse {
        static instance: SniffResponse = SniffResponse {
            packet: ::std::vec::Vec::new(),
            timestamp: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SniffResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SniffResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SniffResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SniffResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18netsim/ble_service.proto\x12\x12netsim.ble_service\x1a\x12netsim/m\
    odel.proto\"Y\n\x0bScanRequest\x122\n\x08position\x18\x01\x20\x01(\x0b2\
    \x16.netsim.model.PositionR\x08position\x12\x16\n\x06active\x18\x02\x20\
    \x01(\x08R\x06active\"&\n\x0cScanResponse\x12\x16\n\x06packet\x18\x01\
    \x20\x01(\x0cR\x06packet\"B\n\x0cSniffRequest\x122\n\x08position\x18\x01\
    \x20\x01(\x0b2\x16.netsim.model.PositionR\x08position\"E\n\rSniffRespons\
    e\x12\x16\n\x06packet\x18\x01\x20\x01(\x0cR\x06packet\x12\x1c\n\ttimesta\
    mp\x18\x02\x20\x01(\x03R\ttimestamp2\xa9\x01\n\nBleService\x12K\n\x04Sca\
    n\x12\x1f.netsim.ble_service.ScanRequest\x1a\x20.netsim.ble_service.Scan\
    Response0\x01\x12N\n\x05Sniff\x12\x20.netsim.ble_service.SniffRequest\
    \x1a!.netsim.ble_service.SniffResponse0\x01J\xff\t\n\x06\x12\x04\x03\0,\
    \x01\n_\n\x01\x0c\x12\x03\x03\0\x122U\x20Copyright\x202026\x20The\x20And\
    roid\x20Open\x20Source\x20Project\n\x20SPDX-License-Identifier:\x20Apach\
    e-2.0\n\n\x08\n\x01\x02\x12\x03\x05\0\x1b\n\t\n\x02\x03\0\x12\x03\x07\0\
    \x1c\nM\n\x02\x06\0\x12\x04\n\0\x0f\x01\x1aA\x20Service\x20to\x20manage\
    \x20Bluetooth\x20test\x20capabilities\x20in\x20the\x20simulation\n\n\n\n\
    \x03\x06\0\x01\x12\x03\n\x08\x12\n>\n\x04\x06\0\x02\0\x12\x03\x0c\x026\
    \x1a1\x20Initiates\x20a\x20Bluetooth\x20scan\x20at\x20a\x20given\x20posi\
    tion.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x0c\x06\n\n\x0c\n\x05\x06\0\
    \x02\0\x02\x12\x03\x0c\x0b\x16\n\x0c\n\x05\x06\0\x02\0\x06\x12\x03\x0c!'\
    \n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x0c(4\n4\n\x04\x06\0\x02\x01\x12\
    \x03\x0e\x029\x1a'\x20Initiates\x20a\x20baseband\x20sniffer\x20capture.\
    \n\n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03\x0e\x06\x0b\n\x0c\n\x05\x06\0\
    \x02\x01\x02\x12\x03\x0e\x0c\x18\n\x0c\n\x05\x06\0\x02\x01\x06\x12\x03\
    \x0e#)\n\x0c\n\x05\x06\0\x02\x01\x03\x12\x03\x0e*7\n\n\n\x02\x04\0\x12\
    \x04\x11\0\x18\x01\n\n\n\x03\x04\0\x01\x12\x03\x11\x08\x13\nJ\n\x04\x04\
    \0\x02\0\x12\x03\x13\x02%\x1a=\x20Initial\x20physical\x20position\x20of\
    \x20the\x20scanner\x20in\x20the\x20simulation.\n\n\x0c\n\x05\x04\0\x02\0\
    \x06\x12\x03\x13\x02\x17\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x13\x18\x20\
    \n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x13#$\n\x9f\x01\n\x04\x04\0\x02\x01\
    \x12\x03\x17\x02\x12\x1a\x91\x01\x20Set\x20to\x20true\x20to\x20use\x20Ac\
    tive\x20Scanning\x20(0x01)\x20instead\x20of\x20Passive\x20Scanning\n\x20\
    (0x00).\x20Active\x20Scanning\x20will\x20trigger\x20Scan\x20Responses\
    \x20from\x20nearby\x20devices.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\
    \x17\x02\x06\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x17\x07\r\n\x0c\n\x05\
    \x04\0\x02\x01\x03\x12\x03\x17\x10\x11\n\n\n\x02\x04\x01\x12\x04\x1a\0\
    \x1d\x01\n\n\n\x03\x04\x01\x01\x12\x03\x1a\x08\x14\n#\n\x04\x04\x01\x02\
    \0\x12\x03\x1c\x02\x13\x1a\x16\x20Raw\x20HCI\x20event\x20packet\n\n\x0c\
    \n\x05\x04\x01\x02\0\x05\x12\x03\x1c\x02\x07\n\x0c\n\x05\x04\x01\x02\0\
    \x01\x12\x03\x1c\x08\x0e\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x1c\x11\
    \x12\n\n\n\x02\x04\x02\x12\x04\x1f\0$\x01\n\n\n\x03\x04\x02\x01\x12\x03\
    \x1f\x08\x14\nJ\n\x04\x04\x02\x02\0\x12\x03!\x02%\x1a=\x20Initial\x20phy\
    sical\x20position\x20of\x20the\x20sniffer\x20in\x20the\x20simulation.\n\
    \n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03!\x02\x17\n\x0c\n\x05\x04\x02\x02\
    \0\x01\x12\x03!\x18\x20\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03!#$\n\n\n\
    \x02\x04\x03\x12\x04&\0,\x01\n\n\n\x03\x04\x03\x01\x12\x03&\x08\x15\n5\n\
    \x04\x04\x03\x02\0\x12\x03(\x02\x13\x1a(\x20Raw\x20link-layer\x20packet\
    \x20(Baseband\x20trace)\n\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03(\x02\x07\
    \n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03(\x08\x0e\n\x0c\n\x05\x04\x03\x02\
    \0\x03\x12\x03(\x11\x12\nL\n\x04\x04\x03\x02\x01\x12\x03+\x02\x16\x1a?\
    \x20Timestamp\x20of\x20the\x20packet\x20in\x20microseconds\x20since\x20t\
    he\x20UNIX\x20epoch.\n\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x03+\x02\x07\
    \n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03+\x08\x11\n\x0c\n\x05\x04\x03\
    \x02\x01\x03\x12\x03+\x14\x15b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::model::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(ScanRequest::generated_message_descriptor_data());
            messages.push(ScanResponse::generated_message_descriptor_data());
            messages.push(SniffRequest::generated_message_descriptor_data());
            messages.push(SniffResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
