// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/casimir_control.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:casimircontrolserver.SendApduRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendApduRequest {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.SendApduRequest.apdu_hex_strings)
    pub apdu_hex_strings: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:casimircontrolserver.SendApduRequest.sender_id)
    pub sender_id: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.SendApduRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendApduRequest {
    fn default() -> &'a SendApduRequest {
        <SendApduRequest as ::protobuf::Message>::default_instance()
    }
}

impl SendApduRequest {
    pub fn new() -> SendApduRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "apdu_hex_strings",
            |m: &SendApduRequest| { &m.apdu_hex_strings },
            |m: &mut SendApduRequest| { &mut m.apdu_hex_strings },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "sender_id",
            |m: &SendApduRequest| { &m.sender_id },
            |m: &mut SendApduRequest| { &mut m.sender_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendApduRequest>(
            "SendApduRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendApduRequest {
    const NAME: &'static str = "SendApduRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.apdu_hex_strings.push(is.read_string()?);
                },
                16 => {
                    self.sender_id = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.apdu_hex_strings {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.sender_id {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.apdu_hex_strings {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.sender_id {
            os.write_uint32(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendApduRequest {
        SendApduRequest::new()
    }

    fn clear(&mut self) {
        self.apdu_hex_strings.clear();
        self.sender_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendApduRequest {
        static instance: SendApduRequest = SendApduRequest {
            apdu_hex_strings: ::std::vec::Vec::new(),
            sender_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendApduRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendApduRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendApduRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendApduRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.SendApduReply)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendApduReply {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.SendApduReply.response_hex_strings)
    pub response_hex_strings: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.SendApduReply.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendApduReply {
    fn default() -> &'a SendApduReply {
        <SendApduReply as ::protobuf::Message>::default_instance()
    }
}

impl SendApduReply {
    pub fn new() -> SendApduReply {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "response_hex_strings",
            |m: &SendApduReply| { &m.response_hex_strings },
            |m: &mut SendApduReply| { &mut m.response_hex_strings },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendApduReply>(
            "SendApduReply",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendApduReply {
    const NAME: &'static str = "SendApduReply";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.response_hex_strings.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.response_hex_strings {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.response_hex_strings {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendApduReply {
        SendApduReply::new()
    }

    fn clear(&mut self) {
        self.response_hex_strings.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendApduReply {
        static instance: SendApduReply = SendApduReply {
            response_hex_strings: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendApduReply {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendApduReply").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendApduReply {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendApduReply {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.SenderId)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SenderId {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.SenderId.sender_id)
    pub sender_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.SenderId.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SenderId {
    fn default() -> &'a SenderId {
        <SenderId as ::protobuf::Message>::default_instance()
    }
}

impl SenderId {
    pub fn new() -> SenderId {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sender_id",
            |m: &SenderId| { &m.sender_id },
            |m: &mut SenderId| { &mut m.sender_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SenderId>(
            "SenderId",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SenderId {
    const NAME: &'static str = "SenderId";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.sender_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.sender_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.sender_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.sender_id != 0 {
            os.write_uint32(1, self.sender_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SenderId {
        SenderId::new()
    }

    fn clear(&mut self) {
        self.sender_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SenderId {
        static instance: SenderId = SenderId {
            sender_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SenderId {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SenderId").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SenderId {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SenderId {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.Void)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Void {
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.Void.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Void {
    fn default() -> &'a Void {
        <Void as ::protobuf::Message>::default_instance()
    }
}

impl Void {
    pub fn new() -> Void {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Void>(
            "Void",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Void {
    const NAME: &'static str = "Void";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Void {
        Void::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Void {
        static instance: Void = Void {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Void {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Void").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Void {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Void {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.RadioState)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RadioState {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.RadioState.radio_on)
    pub radio_on: bool,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.RadioState.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RadioState {
    fn default() -> &'a RadioState {
        <RadioState as ::protobuf::Message>::default_instance()
    }
}

impl RadioState {
    pub fn new() -> RadioState {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "radio_on",
            |m: &RadioState| { &m.radio_on },
            |m: &mut RadioState| { &mut m.radio_on },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RadioState>(
            "RadioState",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RadioState {
    const NAME: &'static str = "RadioState";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.radio_on = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.radio_on != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.radio_on != false {
            os.write_bool(1, self.radio_on)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RadioState {
        RadioState::new()
    }

    fn clear(&mut self) {
        self.radio_on = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RadioState {
        static instance: RadioState = RadioState {
            radio_on: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RadioState {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RadioState").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RadioState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RadioState {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.PowerLevel)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PowerLevel {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.PowerLevel.power_level)
    pub power_level: u32,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.PowerLevel.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PowerLevel {
    fn default() -> &'a PowerLevel {
        <PowerLevel as ::protobuf::Message>::default_instance()
    }
}

impl PowerLevel {
    pub fn new() -> PowerLevel {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "power_level",
            |m: &PowerLevel| { &m.power_level },
            |m: &mut PowerLevel| { &mut m.power_level },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PowerLevel>(
            "PowerLevel",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PowerLevel {
    const NAME: &'static str = "PowerLevel";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.power_level = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.power_level != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.power_level);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.power_level != 0 {
            os.write_uint32(1, self.power_level)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PowerLevel {
        PowerLevel::new()
    }

    fn clear(&mut self) {
        self.power_level = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PowerLevel {
        static instance: PowerLevel = PowerLevel {
            power_level: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PowerLevel {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PowerLevel").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PowerLevel {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PowerLevel {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.TransceiveConfiguration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TransceiveConfiguration {
    // message fields
    ///  A, B, F, V
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.type)
    pub type_: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.crc)
    pub crc: ::std::option::Option<bool>,
    ///  0 to 8
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.bits)
    pub bits: ::std::option::Option<u32>,
    ///  106, 212, 424, 848, 53, 26
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.bitrate)
    pub bitrate: ::std::option::Option<u32>,
    ///  value in microseconds
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.timeout)
    pub timeout: ::std::option::Option<u32>,
    ///  0 to 100
    // @@protoc_insertion_point(field:casimircontrolserver.TransceiveConfiguration.power)
    pub power: ::std::option::Option<f64>,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.TransceiveConfiguration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TransceiveConfiguration {
    fn default() -> &'a TransceiveConfiguration {
        <TransceiveConfiguration as ::protobuf::Message>::default_instance()
    }
}

impl TransceiveConfiguration {
    pub fn new() -> TransceiveConfiguration {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "type",
            |m: &TransceiveConfiguration| { &m.type_ },
            |m: &mut TransceiveConfiguration| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "crc",
            |m: &TransceiveConfiguration| { &m.crc },
            |m: &mut TransceiveConfiguration| { &mut m.crc },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "bits",
            |m: &TransceiveConfiguration| { &m.bits },
            |m: &mut TransceiveConfiguration| { &mut m.bits },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "bitrate",
            |m: &TransceiveConfiguration| { &m.bitrate },
            |m: &mut TransceiveConfiguration| { &mut m.bitrate },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "timeout",
            |m: &TransceiveConfiguration| { &m.timeout },
            |m: &mut TransceiveConfiguration| { &mut m.timeout },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "power",
            |m: &TransceiveConfiguration| { &m.power },
            |m: &mut TransceiveConfiguration| { &mut m.power },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TransceiveConfiguration>(
            "TransceiveConfiguration",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TransceiveConfiguration {
    const NAME: &'static str = "TransceiveConfiguration";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.type_ = ::std::option::Option::Some(is.read_string()?);
                },
                16 => {
                    self.crc = ::std::option::Option::Some(is.read_bool()?);
                },
                24 => {
                    self.bits = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.bitrate = ::std::option::Option::Some(is.read_uint32()?);
                },
                40 => {
                    self.timeout = ::std::option::Option::Some(is.read_uint32()?);
                },
                49 => {
                    self.power = ::std::option::Option::Some(is.read_double()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.type_.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.crc {
            my_size += 1 + 1;
        }
        if let Some(v) = self.bits {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.bitrate {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        if let Some(v) = self.timeout {
            my_size += ::protobuf::rt::uint32_size(5, v);
        }
        if let Some(v) = self.power {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.type_.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.crc {
            os.write_bool(2, v)?;
        }
        if let Some(v) = self.bits {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.bitrate {
            os.write_uint32(4, v)?;
        }
        if let Some(v) = self.timeout {
            os.write_uint32(5, v)?;
        }
        if let Some(v) = self.power {
            os.write_double(6, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TransceiveConfiguration {
        TransceiveConfiguration::new()
    }

    fn clear(&mut self) {
        self.type_ = ::std::option::Option::None;
        self.crc = ::std::option::Option::None;
        self.bits = ::std::option::Option::None;
        self.bitrate = ::std::option::Option::None;
        self.timeout = ::std::option::Option::None;
        self.power = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TransceiveConfiguration {
        static instance: TransceiveConfiguration = TransceiveConfiguration {
            type_: ::std::option::Option::None,
            crc: ::std::option::Option::None,
            bits: ::std::option::Option::None,
            bitrate: ::std::option::Option::None,
            timeout: ::std::option::Option::None,
            power: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TransceiveConfiguration {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TransceiveConfiguration").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TransceiveConfiguration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TransceiveConfiguration {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.SendBroadcastRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendBroadcastRequest {
    // message fields
    // @@protoc_insertion_point(field:casimircontrolserver.SendBroadcastRequest.data)
    pub data: ::std::string::String,
    // @@protoc_insertion_point(field:casimircontrolserver.SendBroadcastRequest.configuration)
    pub configuration: ::protobuf::MessageField<TransceiveConfiguration>,
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.SendBroadcastRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendBroadcastRequest {
    fn default() -> &'a SendBroadcastRequest {
        <SendBroadcastRequest as ::protobuf::Message>::default_instance()
    }
}

impl SendBroadcastRequest {
    pub fn new() -> SendBroadcastRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &SendBroadcastRequest| { &m.data },
            |m: &mut SendBroadcastRequest| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, TransceiveConfiguration>(
            "configuration",
            |m: &SendBroadcastRequest| { &m.configuration },
            |m: &mut SendBroadcastRequest| { &mut m.configuration },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendBroadcastRequest>(
            "SendBroadcastRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendBroadcastRequest {
    const NAME: &'static str = "SendBroadcastRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.data = is.read_string()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.configuration)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.data);
        }
        if let Some(v) = self.configuration.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.data.is_empty() {
            os.write_string(1, &self.data)?;
        }
        if let Some(v) = self.configuration.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendBroadcastRequest {
        SendBroadcastRequest::new()
    }

    fn clear(&mut self) {
        self.data.clear();
        self.configuration.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendBroadcastRequest {
        static instance: SendBroadcastRequest = SendBroadcastRequest {
            data: ::std::string::String::new(),
            configuration: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendBroadcastRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendBroadcastRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendBroadcastRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendBroadcastRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:casimircontrolserver.SendBroadcastResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendBroadcastResponse {
    // special fields
    // @@protoc_insertion_point(special_field:casimircontrolserver.SendBroadcastResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendBroadcastResponse {
    fn default() -> &'a SendBroadcastResponse {
        <SendBroadcastResponse as ::protobuf::Message>::default_instance()
    }
}

impl SendBroadcastResponse {
    pub fn new() -> SendBroadcastResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendBroadcastResponse>(
            "SendBroadcastResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendBroadcastResponse {
    const NAME: &'static str = "SendBroadcastResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendBroadcastResponse {
        SendBroadcastResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendBroadcastResponse {
        static instance: SendBroadcastResponse = SendBroadcastResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendBroadcastResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendBroadcastResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendBroadcastResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendBroadcastResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1cnetsim/casimir_control.proto\x12\x14casimircontrolserver\"k\n\x0fS\
    endApduRequest\x12(\n\x10apdu_hex_strings\x18\x01\x20\x03(\tR\x0eapduHex\
    Strings\x12\x20\n\tsender_id\x18\x02\x20\x01(\rH\0R\x08senderId\x88\x01\
    \x01B\x0c\n\n_sender_id\"A\n\rSendApduReply\x120\n\x14response_hex_strin\
    gs\x18\x01\x20\x03(\tR\x12responseHexStrings\"'\n\x08SenderId\x12\x1b\n\
    \tsender_id\x18\x01\x20\x01(\rR\x08senderId\"\x06\n\x04Void\"'\n\nRadioS\
    tate\x12\x19\n\x08radio_on\x18\x01\x20\x01(\x08R\x07radioOn\"-\n\nPowerL\
    evel\x12\x1f\n\x0bpower_level\x18\x01\x20\x01(\rR\npowerLevel\"\xf7\x01\
    \n\x17TransceiveConfiguration\x12\x17\n\x04type\x18\x01\x20\x01(\tH\0R\
    \x04type\x88\x01\x01\x12\x15\n\x03crc\x18\x02\x20\x01(\x08H\x01R\x03crc\
    \x88\x01\x01\x12\x17\n\x04bits\x18\x03\x20\x01(\rH\x02R\x04bits\x88\x01\
    \x01\x12\x1d\n\x07bitrate\x18\x04\x20\x01(\rH\x03R\x07bitrate\x88\x01\
    \x01\x12\x1d\n\x07timeout\x18\x05\x20\x01(\rH\x04R\x07timeout\x88\x01\
    \x01\x12\x19\n\x05power\x18\x06\x20\x01(\x01H\x05R\x05power\x88\x01\x01B\
    \x07\n\x05_typeB\x06\n\x04_crcB\x07\n\x05_bitsB\n\n\x08_bitrateB\n\n\x08\
    _timeoutB\x08\n\x06_power\"\x96\x01\n\x14SendBroadcastRequest\x12\x12\n\
    \x04data\x18\x01\x20\x01(\tR\x04data\x12X\n\rconfiguration\x18\x02\x20\
    \x01(\x0b2-.casimircontrolserver.TransceiveConfigurationH\0R\rconfigurat\
    ion\x88\x01\x01B\x10\n\x0e_configuration\"\x17\n\x15SendBroadcastRespons\
    e2\xcb\x04\n\x15CasimirControlService\x12X\n\x08SendApdu\x12%.casimircon\
    trolserver.SendApduRequest\x1a#.casimircontrolserver.SendApduReply\"\0\
    \x12E\n\x05PollA\x12\x1a.casimircontrolserver.Void\x1a\x1e.casimircontro\
    lserver.SenderId\"\0\x12O\n\rSetRadioState\x12\x20.casimircontrolserver.\
    RadioState\x1a\x1a.casimircontrolserver.Void\"\0\x12O\n\rSetPowerLevel\
    \x12\x20.casimircontrolserver.PowerLevel\x1a\x1a.casimircontrolserver.Vo\
    id\"\0\x12j\n\rSendBroadcast\x12*.casimircontrolserver.SendBroadcastRequ\
    est\x1a+.casimircontrolserver.SendBroadcastResponse\"\0\x12@\n\x04Init\
    \x12\x1a.casimircontrolserver.Void\x1a\x1a.casimircontrolserver.Void\"\0\
    \x12A\n\x05Close\x12\x1a.casimircontrolserver.Void\x1a\x1a.casimircontro\
    lserver.Void\"\0J\xcb\r\n\x06\x12\x04\x03\0;\x20\n_\n\x01\x0c\x12\x03\
    \x03\0\x122U\x20Copyright\x202026\x20The\x20Android\x20Open\x20Source\
    \x20Project\n\x20SPDX-License-Identifier:\x20Apache-2.0\n\n\x08\n\x01\
    \x02\x12\x03\x05\0\x1d\n\n\n\x02\x06\0\x12\x04\x07\0\x0f\x01\n\n\n\x03\
    \x06\0\x01\x12\x03\x07\x08\x1d\n\x0b\n\x04\x06\0\x02\0\x12\x03\x08\x02:\
    \n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x08\x06\x0e\n\x0c\n\x05\x06\0\x02\0\
    \x02\x12\x03\x08\x0f\x1e\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x08)6\n\x0b\
    \n\x04\x06\0\x02\x01\x12\x03\t\x02'\n\x0c\n\x05\x06\0\x02\x01\x01\x12\
    \x03\t\x06\x0b\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\t\x0c\x10\n\x0c\n\
    \x05\x06\0\x02\x01\x03\x12\x03\t\x1b#\n\x0b\n\x04\x06\0\x02\x02\x12\x03\
    \n\x021\n\x0c\n\x05\x06\0\x02\x02\x01\x12\x03\n\x06\x13\n\x0c\n\x05\x06\
    \0\x02\x02\x02\x12\x03\n\x14\x1e\n\x0c\n\x05\x06\0\x02\x02\x03\x12\x03\n\
    )-\n\x0b\n\x04\x06\0\x02\x03\x12\x03\x0b\x021\n\x0c\n\x05\x06\0\x02\x03\
    \x01\x12\x03\x0b\x06\x13\n\x0c\n\x05\x06\0\x02\x03\x02\x12\x03\x0b\x14\
    \x1e\n\x0c\n\x05\x06\0\x02\x03\x03\x12\x03\x0b)-\n\x0b\n\x04\x06\0\x02\
    \x04\x12\x03\x0c\x02L\n\x0c\n\x05\x06\0\x02\x04\x01\x12\x03\x0c\x06\x13\
    \n\x0c\n\x05\x06\0\x02\x04\x02\x12\x03\x0c\x14(\n\x0c\n\x05\x06\0\x02\
    \x04\x03\x12\x03\x0c3H\n\x0b\n\x04\x06\0\x02\x05\x12\x03\r\x02\"\n\x0c\n\
    \x05\x06\0\x02\x05\x01\x12\x03\r\x06\n\n\x0c\n\x05\x06\0\x02\x05\x02\x12\
    \x03\r\x0b\x0f\n\x0c\n\x05\x06\0\x02\x05\x03\x12\x03\r\x1a\x1e\n\x0b\n\
    \x04\x06\0\x02\x06\x12\x03\x0e\x02#\n\x0c\n\x05\x06\0\x02\x06\x01\x12\
    \x03\x0e\x06\x0b\n\x0c\n\x05\x06\0\x02\x06\x02\x12\x03\x0e\x0c\x10\n\x0c\
    \n\x05\x06\0\x02\x06\x03\x12\x03\x0e\x1b\x1f\n\n\n\x02\x04\0\x12\x04\x11\
    \0\x14\x01\n\n\n\x03\x04\0\x01\x12\x03\x11\x08\x17\n\x0b\n\x04\x04\0\x02\
    \0\x12\x03\x12\x02'\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x12\x02\n\n\x0c\
    \n\x05\x04\0\x02\0\x05\x12\x03\x12\x0b\x11\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03\x12\x12\"\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x12%&\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\x13\x02\x20\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03\
    \x13\x02\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x13\x0b\x11\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03\x13\x12\x1b\n\x0c\n\x05\x04\0\x02\x01\x03\x12\
    \x03\x13\x1e\x1f\n\n\n\x02\x04\x01\x12\x04\x16\0\x18\x01\n\n\n\x03\x04\
    \x01\x01\x12\x03\x16\x08\x15\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x17\x02+\
    \n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03\x17\x02\n\n\x0c\n\x05\x04\x01\x02\
    \0\x05\x12\x03\x17\x0b\x11\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x17\x12\
    &\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x17)*\n\n\n\x02\x04\x02\x12\x04\
    \x1a\0\x1c\x01\n\n\n\x03\x04\x02\x01\x12\x03\x1a\x08\x10\n\x0b\n\x04\x04\
    \x02\x02\0\x12\x03\x1b\x02\x17\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x1b\
    \x02\x08\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x1b\t\x12\n\x0c\n\x05\x04\
    \x02\x02\0\x03\x12\x03\x1b\x15\x16\n\t\n\x02\x04\x03\x12\x03\x1e\0\x0f\n\
    \n\n\x03\x04\x03\x01\x12\x03\x1e\x08\x0c\n\n\n\x02\x04\x04\x12\x04\x20\0\
    \"\x01\n\n\n\x03\x04\x04\x01\x12\x03\x20\x08\x12\n\x0b\n\x04\x04\x04\x02\
    \0\x12\x03!\x02\x14\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03!\x02\x06\n\x0c\
    \n\x05\x04\x04\x02\0\x01\x12\x03!\x07\x0f\n\x0c\n\x05\x04\x04\x02\0\x03\
    \x12\x03!\x12\x13\n\n\n\x02\x04\x05\x12\x04$\0&\x01\n\n\n\x03\x04\x05\
    \x01\x12\x03$\x08\x12\n\x0b\n\x04\x04\x05\x02\0\x12\x03%\x02\x19\n\x0c\n\
    \x05\x04\x05\x02\0\x05\x12\x03%\x02\x08\n\x0c\n\x05\x04\x05\x02\0\x01\
    \x12\x03%\t\x14\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03%\x17\x18\n\n\n\x02\
    \x04\x06\x12\x04(\04\x01\n\n\n\x03\x04\x06\x01\x12\x03(\x08\x1f\n\x19\n\
    \x04\x04\x06\x02\0\x12\x03*\x02\x1b\x1a\x0c\x20A,\x20B,\x20F,\x20V\n\n\
    \x0c\n\x05\x04\x06\x02\0\x04\x12\x03*\x02\n\n\x0c\n\x05\x04\x06\x02\0\
    \x05\x12\x03*\x0b\x11\n\x0c\n\x05\x04\x06\x02\0\x01\x12\x03*\x12\x16\n\
    \x0c\n\x05\x04\x06\x02\0\x03\x12\x03*\x19\x1a\n\x0b\n\x04\x04\x06\x02\
    \x01\x12\x03+\x02\x18\n\x0c\n\x05\x04\x06\x02\x01\x04\x12\x03+\x02\n\n\
    \x0c\n\x05\x04\x06\x02\x01\x05\x12\x03+\x0b\x0f\n\x0c\n\x05\x04\x06\x02\
    \x01\x01\x12\x03+\x10\x13\n\x0c\n\x05\x04\x06\x02\x01\x03\x12\x03+\x16\
    \x17\n\x15\n\x04\x04\x06\x02\x02\x12\x03-\x02\x1b\x1a\x08\x200\x20to\x20\
    8\n\n\x0c\n\x05\x04\x06\x02\x02\x04\x12\x03-\x02\n\n\x0c\n\x05\x04\x06\
    \x02\x02\x05\x12\x03-\x0b\x11\n\x0c\n\x05\x04\x06\x02\x02\x01\x12\x03-\
    \x12\x16\n\x0c\n\x05\x04\x06\x02\x02\x03\x12\x03-\x19\x1a\n)\n\x04\x04\
    \x06\x02\x03\x12\x03/\x02\x1e\x1a\x1c\x20106,\x20212,\x20424,\x20848,\
    \x2053,\x2026\n\n\x0c\n\x05\x04\x06\x02\x03\x04\x12\x03/\x02\n\n\x0c\n\
    \x05\x04\x06\x02\x03\x05\x12\x03/\x0b\x11\n\x0c\n\x05\x04\x06\x02\x03\
    \x01\x12\x03/\x12\x19\n\x0c\n\x05\x04\x06\x02\x03\x03\x12\x03/\x1c\x1d\n\
    $\n\x04\x04\x06\x02\x04\x12\x031\x02\x1e\x1a\x17\x20value\x20in\x20micro\
    seconds\n\n\x0c\n\x05\x04\x06\x02\x04\x04\x12\x031\x02\n\n\x0c\n\x05\x04\
    \x06\x02\x04\x05\x12\x031\x0b\x11\n\x0c\n\x05\x04\x06\x02\x04\x01\x12\
    \x031\x12\x19\n\x0c\n\x05\x04\x06\x02\x04\x03\x12\x031\x1c\x1d\n\x17\n\
    \x04\x04\x06\x02\x05\x12\x033\x02\x1c\x1a\n\x200\x20to\x20100\n\n\x0c\n\
    \x05\x04\x06\x02\x05\x04\x12\x033\x02\n\n\x0c\n\x05\x04\x06\x02\x05\x05\
    \x12\x033\x0b\x11\n\x0c\n\x05\x04\x06\x02\x05\x01\x12\x033\x12\x17\n\x0c\
    \n\x05\x04\x06\x02\x05\x03\x12\x033\x1a\x1b\n\n\n\x02\x04\x07\x12\x046\0\
    9\x01\n\n\n\x03\x04\x07\x01\x12\x036\x08\x1c\n\x0b\n\x04\x04\x07\x02\0\
    \x12\x037\x02\x12\n\x0c\n\x05\x04\x07\x02\0\x05\x12\x037\x02\x08\n\x0c\n\
    \x05\x04\x07\x02\0\x01\x12\x037\t\r\n\x0c\n\x05\x04\x07\x02\0\x03\x12\
    \x037\x10\x11\n\x0b\n\x04\x04\x07\x02\x01\x12\x038\x025\n\x0c\n\x05\x04\
    \x07\x02\x01\x04\x12\x038\x02\n\n\x0c\n\x05\x04\x07\x02\x01\x06\x12\x038\
    \x0b\"\n\x0c\n\x05\x04\x07\x02\x01\x01\x12\x038#0\n\x0c\n\x05\x04\x07\
    \x02\x01\x03\x12\x03834\n\t\n\x02\x04\x08\x12\x03;\0\x20\n\n\n\x03\x04\
    \x08\x01\x12\x03;\x08\x1db\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(9);
            messages.push(SendApduRequest::generated_message_descriptor_data());
            messages.push(SendApduReply::generated_message_descriptor_data());
            messages.push(SenderId::generated_message_descriptor_data());
            messages.push(Void::generated_message_descriptor_data());
            messages.push(RadioState::generated_message_descriptor_data());
            messages.push(PowerLevel::generated_message_descriptor_data());
            messages.push(TransceiveConfiguration::generated_message_descriptor_data());
            messages.push(SendBroadcastRequest::generated_message_descriptor_data());
            messages.push(SendBroadcastResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
