// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  Radio Type (BT, WIFI, UWB, NFC, CELLULAR, CELLULAR_DATA, ETHERNET)
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:netsim.common.ChipKind)
pub enum ChipKind {
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.UNSPECIFIED)
    UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.BLUETOOTH)
    BLUETOOTH = 1,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.WIFI)
    WIFI = 2,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.UWB)
    UWB = 3,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.BLUETOOTH_BEACON)
    BLUETOOTH_BEACON = 4,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.NFC)
    NFC = 5,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.CELLULAR)
    CELLULAR = 6,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.CELLULAR_DATA)
    CELLULAR_DATA = 7,
    // @@protoc_insertion_point(enum_value:netsim.common.ChipKind.ETHERNET)
    ETHERNET = 8,
}

impl ::protobuf::Enum for ChipKind {
    const NAME: &'static str = "ChipKind";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ChipKind> {
        match value {
            0 => ::std::option::Option::Some(ChipKind::UNSPECIFIED),
            1 => ::std::option::Option::Some(ChipKind::BLUETOOTH),
            2 => ::std::option::Option::Some(ChipKind::WIFI),
            3 => ::std::option::Option::Some(ChipKind::UWB),
            4 => ::std::option::Option::Some(ChipKind::BLUETOOTH_BEACON),
            5 => ::std::option::Option::Some(ChipKind::NFC),
            6 => ::std::option::Option::Some(ChipKind::CELLULAR),
            7 => ::std::option::Option::Some(ChipKind::CELLULAR_DATA),
            8 => ::std::option::Option::Some(ChipKind::ETHERNET),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ChipKind> {
        match str {
            "UNSPECIFIED" => ::std::option::Option::Some(ChipKind::UNSPECIFIED),
            "BLUETOOTH" => ::std::option::Option::Some(ChipKind::BLUETOOTH),
            "WIFI" => ::std::option::Option::Some(ChipKind::WIFI),
            "UWB" => ::std::option::Option::Some(ChipKind::UWB),
            "BLUETOOTH_BEACON" => ::std::option::Option::Some(ChipKind::BLUETOOTH_BEACON),
            "NFC" => ::std::option::Option::Some(ChipKind::NFC),
            "CELLULAR" => ::std::option::Option::Some(ChipKind::CELLULAR),
            "CELLULAR_DATA" => ::std::option::Option::Some(ChipKind::CELLULAR_DATA),
            "ETHERNET" => ::std::option::Option::Some(ChipKind::ETHERNET),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ChipKind] = &[
        ChipKind::UNSPECIFIED,
        ChipKind::BLUETOOTH,
        ChipKind::WIFI,
        ChipKind::UWB,
        ChipKind::BLUETOOTH_BEACON,
        ChipKind::NFC,
        ChipKind::CELLULAR,
        ChipKind::CELLULAR_DATA,
        ChipKind::ETHERNET,
    ];
}

impl ::protobuf::EnumFull for ChipKind {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ChipKind").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ChipKind {
    fn default() -> Self {
        ChipKind::UNSPECIFIED
    }
}

impl ChipKind {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ChipKind>("ChipKind")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13netsim/common.proto\x12\rnetsim.common*\x8f\x01\n\x08ChipKind\x12\
    \x0f\n\x0bUNSPECIFIED\x10\0\x12\r\n\tBLUETOOTH\x10\x01\x12\x08\n\x04WIFI\
    \x10\x02\x12\x07\n\x03UWB\x10\x03\x12\x18\n\x10BLUETOOTH_BEACON\x10\x04\
    \x1a\x02\x08\x01\x12\x07\n\x03NFC\x10\x05\x12\x0c\n\x08CELLULAR\x10\x06\
    \x12\x11\n\rCELLULAR_DATA\x10\x07\x12\x0c\n\x08ETHERNET\x10\x08B#\n\x1fc\
    om.android.emulation.bluetoothP\x01J\xa3\x05\n\x06\x12\x04\x03\0\x16\x01\
    \n_\n\x01\x0c\x12\x03\x03\0\x122U\x20Copyright\x202022\x20The\x20Android\
    \x20Open\x20Source\x20Project\n\x20SPDX-License-Identifier:\x20Apache-2.\
    0\n\n\x08\n\x01\x02\x12\x03\x05\0\x16\n\x08\n\x01\x08\x12\x03\x07\0\"\n\
    \t\n\x02\x08\n\x12\x03\x07\0\"\n\x08\n\x01\x08\x12\x03\x08\08\n\t\n\x02\
    \x08\x01\x12\x03\x08\08\nP\n\x02\x05\0\x12\x04\x0b\0\x16\x01\x1aD\x20Rad\
    io\x20Type\x20(BT,\x20WIFI,\x20UWB,\x20NFC,\x20CELLULAR,\x20CELLULAR_DAT\
    A,\x20ETHERNET)\n\n\n\n\x03\x05\0\x01\x12\x03\x0b\x05\r\n%\n\x04\x05\0\
    \x02\0\x12\x03\r\x02\x12\x1a\x18\x20Default\x20to\x20UNSPECIFIED\n\n\x0c\
    \n\x05\x05\0\x02\0\x01\x12\x03\r\x02\r\n\x0c\n\x05\x05\0\x02\0\x02\x12\
    \x03\r\x10\x11\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x0e\x02\x10\n\x0c\n\x05\
    \x05\0\x02\x01\x01\x12\x03\x0e\x02\x0b\n\x0c\n\x05\x05\0\x02\x01\x02\x12\
    \x03\x0e\x0e\x0f\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x0f\x02\x0b\n\x0c\n\
    \x05\x05\0\x02\x02\x01\x12\x03\x0f\x02\x06\n\x0c\n\x05\x05\0\x02\x02\x02\
    \x12\x03\x0f\t\n\n\x0b\n\x04\x05\0\x02\x03\x12\x03\x10\x02\n\n\x0c\n\x05\
    \x05\0\x02\x03\x01\x12\x03\x10\x02\x05\n\x0c\n\x05\x05\0\x02\x03\x02\x12\
    \x03\x10\x08\t\n\x0b\n\x04\x05\0\x02\x04\x12\x03\x11\x02+\n\x0c\n\x05\
    \x05\0\x02\x04\x01\x12\x03\x11\x02\x12\n\x0c\n\x05\x05\0\x02\x04\x02\x12\
    \x03\x11\x15\x16\n\x0c\n\x05\x05\0\x02\x04\x03\x12\x03\x11\x17*\n\r\n\
    \x06\x05\0\x02\x04\x03\x01\x12\x03\x11\x18)\n\x0b\n\x04\x05\0\x02\x05\
    \x12\x03\x12\x02\n\n\x0c\n\x05\x05\0\x02\x05\x01\x12\x03\x12\x02\x05\n\
    \x0c\n\x05\x05\0\x02\x05\x02\x12\x03\x12\x08\t\n\x0b\n\x04\x05\0\x02\x06\
    \x12\x03\x13\x02\x0f\n\x0c\n\x05\x05\0\x02\x06\x01\x12\x03\x13\x02\n\n\
    \x0c\n\x05\x05\0\x02\x06\x02\x12\x03\x13\r\x0e\n\x0b\n\x04\x05\0\x02\x07\
    \x12\x03\x14\x02\x14\n\x0c\n\x05\x05\0\x02\x07\x01\x12\x03\x14\x02\x0f\n\
    \x0c\n\x05\x05\0\x02\x07\x02\x12\x03\x14\x12\x13\n\x0b\n\x04\x05\0\x02\
    \x08\x12\x03\x15\x02\x0f\n\x0c\n\x05\x05\0\x02\x08\x01\x12\x03\x15\x02\n\
    \n\x0c\n\x05\x05\0\x02\x08\x02\x12\x03\x15\r\x0eb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ChipKind::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
