// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/hci_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  A packet that is exchanged between the bluetooth chip and higher layers.
// @@protoc_insertion_point(message:netsim.packet.HCIPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HCIPacket {
    // message fields
    ///  Indicates the type of packet contained in the packet bytes.
    // @@protoc_insertion_point(field:netsim.packet.HCIPacket.packet_type)
    pub packet_type: ::protobuf::EnumOrUnknown<hcipacket::PacketType>,
    ///  The actual data that was transferred.
    // @@protoc_insertion_point(field:netsim.packet.HCIPacket.packet)
    pub packet: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.packet.HCIPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HCIPacket {
    fn default() -> &'a HCIPacket {
        <HCIPacket as ::protobuf::Message>::default_instance()
    }
}

impl HCIPacket {
    pub fn new() -> HCIPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "packet_type",
            |m: &HCIPacket| { &m.packet_type },
            |m: &mut HCIPacket| { &mut m.packet_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "packet",
            |m: &HCIPacket| { &m.packet },
            |m: &mut HCIPacket| { &mut m.packet },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HCIPacket>(
            "HCIPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HCIPacket {
    const NAME: &'static str = "HCIPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.packet_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.packet = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.packet_type != ::protobuf::EnumOrUnknown::new(hcipacket::PacketType::HCI_PACKET_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.packet_type.value());
        }
        if !self.packet.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.packet);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.packet_type != ::protobuf::EnumOrUnknown::new(hcipacket::PacketType::HCI_PACKET_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.packet_type))?;
        }
        if !self.packet.is_empty() {
            os.write_bytes(2, &self.packet)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HCIPacket {
        HCIPacket::new()
    }

    fn clear(&mut self) {
        self.packet_type = ::protobuf::EnumOrUnknown::new(hcipacket::PacketType::HCI_PACKET_UNSPECIFIED);
        self.packet.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HCIPacket {
        static instance: HCIPacket = HCIPacket {
            packet_type: ::protobuf::EnumOrUnknown::from_i32(0),
            packet: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HCIPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HCIPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HCIPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HCIPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `HCIPacket`
pub mod hcipacket {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:netsim.packet.HCIPacket.PacketType)
    pub enum PacketType {
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.HCI_PACKET_UNSPECIFIED)
        HCI_PACKET_UNSPECIFIED = 0,
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.COMMAND)
        COMMAND = 1,
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.ACL)
        ACL = 2,
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.SCO)
        SCO = 3,
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.EVENT)
        EVENT = 4,
        // @@protoc_insertion_point(enum_value:netsim.packet.HCIPacket.PacketType.ISO)
        ISO = 5,
    }

    impl ::protobuf::Enum for PacketType {
        const NAME: &'static str = "PacketType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<PacketType> {
            match value {
                0 => ::std::option::Option::Some(PacketType::HCI_PACKET_UNSPECIFIED),
                1 => ::std::option::Option::Some(PacketType::COMMAND),
                2 => ::std::option::Option::Some(PacketType::ACL),
                3 => ::std::option::Option::Some(PacketType::SCO),
                4 => ::std::option::Option::Some(PacketType::EVENT),
                5 => ::std::option::Option::Some(PacketType::ISO),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<PacketType> {
            match str {
                "HCI_PACKET_UNSPECIFIED" => ::std::option::Option::Some(PacketType::HCI_PACKET_UNSPECIFIED),
                "COMMAND" => ::std::option::Option::Some(PacketType::COMMAND),
                "ACL" => ::std::option::Option::Some(PacketType::ACL),
                "SCO" => ::std::option::Option::Some(PacketType::SCO),
                "EVENT" => ::std::option::Option::Some(PacketType::EVENT),
                "ISO" => ::std::option::Option::Some(PacketType::ISO),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [PacketType] = &[
            PacketType::HCI_PACKET_UNSPECIFIED,
            PacketType::COMMAND,
            PacketType::ACL,
            PacketType::SCO,
            PacketType::EVENT,
            PacketType::ISO,
        ];
    }

    impl ::protobuf::EnumFull for PacketType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("HCIPacket.PacketType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for PacketType {
        fn default() -> Self {
            PacketType::HCI_PACKET_UNSPECIFIED
        }
    }

    impl PacketType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<PacketType>("HCIPacket.PacketType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17netsim/hci_packet.proto\x12\rnetsim.packet\"\xc6\x01\n\tHCIPacket\
    \x12D\n\x0bpacket_type\x18\x01\x20\x01(\x0e2#.netsim.packet.HCIPacket.Pa\
    cketTypeR\npacketType\x12\x16\n\x06packet\x18\x02\x20\x01(\x0cR\x06packe\
    t\"[\n\nPacketType\x12\x1a\n\x16HCI_PACKET_UNSPECIFIED\x10\0\x12\x0b\n\
    \x07COMMAND\x10\x01\x12\x07\n\x03ACL\x10\x02\x12\x07\n\x03SCO\x10\x03\
    \x12\t\n\x05EVENT\x10\x04\x12\x07\n\x03ISO\x10\x05BG\n\x1fcom.android.em\
    ulation.bluetoothP\x01\xa2\x02\x03AEB\xaa\x02\x1bAndroid.Emulation.Bluet\
    oothJ\xf0\x0b\n\x06\x12\x04\x02\0.\x01\nc\n\x01\x0c\x12\x03\x02\0\x12\
    \x1aY\x20Copyright\x20(C)\x202021\x20The\x20Android\x20Open\x20Source\
    \x20Project\n\x20SPDX-License-Identifier:\x20Apache-2.0\n\n\x08\n\x01\
    \x02\x12\x03\x04\0\x16\n\x08\n\x01\x08\x12\x03\x06\0\"\n\t\n\x02\x08\n\
    \x12\x03\x06\0\"\n\x08\n\x01\x08\x12\x03\x07\08\n\t\n\x02\x08\x01\x12\
    \x03\x07\08\n\x08\n\x01\x08\x12\x03\x08\08\n\t\n\x02\x08%\x12\x03\x08\08\
    \n\x08\n\x01\x08\x12\x03\t\0!\n\t\n\x02\x08$\x12\x03\t\0!\nV\n\x02\x04\0\
    \x12\x04\x0c\0.\x01\x1aJ\x20A\x20packet\x20that\x20is\x20exchanged\x20be\
    tween\x20the\x20bluetooth\x20chip\x20and\x20higher\x20layers.\n\n\n\n\
    \x03\x04\0\x01\x12\x03\x0c\x08\x11\n\x0c\n\x04\x04\0\x04\0\x12\x04\r\x02\
    '\x03\n\x0c\n\x05\x04\0\x04\0\x01\x12\x03\r\x07\x11\n\xff\x01\n\x06\x04\
    \0\x04\0\x02\0\x12\x03\x12\x04\x1f\x1a\xef\x01\x20The\x20packet\x20is\
    \x20unspecified,\x20and\x20contains\x20raw\x20bytes.\n\x20This\x20is\x20\
    mainly\x20here\x20to\x20protect\x20against\x20compatibility\x20issues\
    \x20that\x20can\n\x20arise\x20if\x20new\x20enum\x20fields\x20are\x20ever\
    \x20introduced.\n\x20See:\x20https://developers.google.com/protocol-buff\
    ers/docs/style#enums\n\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x12\x04\
    \x1a\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x12\x1d\x1e\nd\n\x06\x04\
    \0\x04\0\x02\x01\x12\x03\x16\x04\x10\x1aU\x20HCI\x20Command\x20Packets:\
    \x20commands\x20are\x20issued\x20by\x20the\x20HCI\x20Driver\x20to\x20the\
    \n\x20Host\x20Controller:\n\n\x0e\n\x07\x04\0\x04\0\x02\x01\x01\x12\x03\
    \x16\x04\x0b\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\x12\x03\x16\x0e\x0f\n:\
    \n\x06\x04\0\x04\0\x02\x02\x12\x03\x19\x04\x0c\x1a+\x20ACL\x20(asynchron\
    ous\x20connectionless)\x20packet.\n\n\x0e\n\x07\x04\0\x04\0\x02\x02\x01\
    \x12\x03\x19\x04\x07\n\x0e\n\x07\x04\0\x04\0\x02\x02\x02\x12\x03\x19\n\
    \x0b\n@\n\x06\x04\0\x04\0\x02\x03\x12\x03\x1c\x04\x0c\x1a1\x20SCO\x20(sy\
    nchronous\x20connection\x20orientated)\x20packet.\n\n\x0e\n\x07\x04\0\
    \x04\0\x02\x03\x01\x12\x03\x1c\x04\x07\n\x0e\n\x07\x04\0\x04\0\x02\x03\
    \x02\x12\x03\x1c\n\x0b\n#\n\x06\x04\0\x04\0\x02\x04\x12\x03\x1f\x04\x0e\
    \x1a\x14\x20HCI\x20Event\x20Packets.\n\n\x0e\n\x07\x04\0\x04\0\x02\x04\
    \x01\x12\x03\x1f\x04\t\n\x0e\n\x07\x04\0\x04\0\x02\x04\x02\x12\x03\x1f\
    \x0c\r\n\x81\x02\n\x06\x04\0\x04\0\x02\x05\x12\x03&\x04\x0c\x1a\xf1\x01\
    \x20Isochronous\x20Channel,\x20a\x20data\x20transmissions\x20that\x20are\
    \x20time-sensitive\n\x20and\x20synchronized\x20rendering\x20of\x20these\
    \x20data\x20streams\x20across\x20multiple\n\x20receivers.\x20See\n\x20ht\
    tps://www.novelbits.io/bluetooth-version-5-2-le-audio/\x20for\x20an\n\
    \x20overview\x20of\x20ISO\x20channels.\n\n\x0e\n\x07\x04\0\x04\0\x02\x05\
    \x01\x12\x03&\x04\x07\n\x0e\n\x07\x04\0\x04\0\x02\x05\x02\x12\x03&\n\x0b\
    \nJ\n\x04\x04\0\x02\0\x12\x03*\x02\x1d\x1a=\x20Indicates\x20the\x20type\
    \x20of\x20packet\x20contained\x20in\x20the\x20packet\x20bytes.\n\n\x0c\n\
    \x05\x04\0\x02\0\x06\x12\x03*\x02\x0c\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03*\r\x18\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03*\x1b\x1c\n4\n\x04\x04\0\
    \x02\x01\x12\x03-\x02\x13\x1a'\x20The\x20actual\x20data\x20that\x20was\
    \x20transferred.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03-\x02\x07\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03-\x08\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03-\x11\x12b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(HCIPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(hcipacket::PacketType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
