// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/nfc_service.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:netsim.nfc_service.GetStatusRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetStatusRequest {
    // message fields
    ///  Optional ID of the specific chip to get status for. If 0, returns all NFC
    ///  chips.
    // @@protoc_insertion_point(field:netsim.nfc_service.GetStatusRequest.chip_id)
    pub chip_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.GetStatusRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetStatusRequest {
    fn default() -> &'a GetStatusRequest {
        <GetStatusRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetStatusRequest {
    pub fn new() -> GetStatusRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "chip_id",
            |m: &GetStatusRequest| { &m.chip_id },
            |m: &mut GetStatusRequest| { &mut m.chip_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetStatusRequest>(
            "GetStatusRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetStatusRequest {
    const NAME: &'static str = "GetStatusRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.chip_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.chip_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.chip_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.chip_id != 0 {
            os.write_uint32(1, self.chip_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetStatusRequest {
        GetStatusRequest::new()
    }

    fn clear(&mut self) {
        self.chip_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetStatusRequest {
        static instance: GetStatusRequest = GetStatusRequest {
            chip_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetStatusRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetStatusRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetStatusRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetStatusRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.GetStatusResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetStatusResponse {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.GetStatusResponse.chips)
    pub chips: ::std::vec::Vec<super::model::Chip>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.GetStatusResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetStatusResponse {
    fn default() -> &'a GetStatusResponse {
        <GetStatusResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetStatusResponse {
    pub fn new() -> GetStatusResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "chips",
            |m: &GetStatusResponse| { &m.chips },
            |m: &mut GetStatusResponse| { &mut m.chips },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetStatusResponse>(
            "GetStatusResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetStatusResponse {
    const NAME: &'static str = "GetStatusResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.chips.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.chips {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.chips {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetStatusResponse {
        GetStatusResponse::new()
    }

    fn clear(&mut self) {
        self.chips.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetStatusResponse {
        static instance: GetStatusResponse = GetStatusResponse {
            chips: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetStatusResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetStatusResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetStatusResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetStatusResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.SetPowerRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SetPowerRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.SetPowerRequest.chip_id)
    pub chip_id: u32,
    // @@protoc_insertion_point(field:netsim.nfc_service.SetPowerRequest.power_on)
    pub power_on: bool,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.SetPowerRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SetPowerRequest {
    fn default() -> &'a SetPowerRequest {
        <SetPowerRequest as ::protobuf::Message>::default_instance()
    }
}

impl SetPowerRequest {
    pub fn new() -> SetPowerRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "chip_id",
            |m: &SetPowerRequest| { &m.chip_id },
            |m: &mut SetPowerRequest| { &mut m.chip_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "power_on",
            |m: &SetPowerRequest| { &m.power_on },
            |m: &mut SetPowerRequest| { &mut m.power_on },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SetPowerRequest>(
            "SetPowerRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SetPowerRequest {
    const NAME: &'static str = "SetPowerRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.chip_id = is.read_uint32()?;
                },
                16 => {
                    self.power_on = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.chip_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.chip_id);
        }
        if self.power_on != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.chip_id != 0 {
            os.write_uint32(1, self.chip_id)?;
        }
        if self.power_on != false {
            os.write_bool(2, self.power_on)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SetPowerRequest {
        SetPowerRequest::new()
    }

    fn clear(&mut self) {
        self.chip_id = 0;
        self.power_on = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SetPowerRequest {
        static instance: SetPowerRequest = SetPowerRequest {
            chip_id: 0,
            power_on: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SetPowerRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SetPowerRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SetPowerRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetPowerRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.SetPowerResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SetPowerResponse {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.SetPowerResponse.chip)
    pub chip: ::protobuf::MessageField<super::model::Chip>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.SetPowerResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SetPowerResponse {
    fn default() -> &'a SetPowerResponse {
        <SetPowerResponse as ::protobuf::Message>::default_instance()
    }
}

impl SetPowerResponse {
    pub fn new() -> SetPowerResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::model::Chip>(
            "chip",
            |m: &SetPowerResponse| { &m.chip },
            |m: &mut SetPowerResponse| { &mut m.chip },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SetPowerResponse>(
            "SetPowerResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SetPowerResponse {
    const NAME: &'static str = "SetPowerResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.chip)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.chip.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.chip.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SetPowerResponse {
        SetPowerResponse::new()
    }

    fn clear(&mut self) {
        self.chip.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SetPowerResponse {
        static instance: SetPowerResponse = SetPowerResponse {
            chip: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SetPowerResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SetPowerResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SetPowerResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetPowerResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.PollRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PollRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.PollRequest.chip_id)
    pub chip_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.PollRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PollRequest {
    fn default() -> &'a PollRequest {
        <PollRequest as ::protobuf::Message>::default_instance()
    }
}

impl PollRequest {
    pub fn new() -> PollRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "chip_id",
            |m: &PollRequest| { &m.chip_id },
            |m: &mut PollRequest| { &mut m.chip_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PollRequest>(
            "PollRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PollRequest {
    const NAME: &'static str = "PollRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.chip_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.chip_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.chip_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.chip_id != 0 {
            os.write_uint32(1, self.chip_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PollRequest {
        PollRequest::new()
    }

    fn clear(&mut self) {
        self.chip_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PollRequest {
        static instance: PollRequest = PollRequest {
            chip_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PollRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PollRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PollRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PollRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.PollResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PollResponse {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.PollResponse.target_id)
    pub target_id: u32,
    // @@protoc_insertion_point(field:netsim.nfc_service.PollResponse.tag_data)
    pub tag_data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.PollResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PollResponse {
    fn default() -> &'a PollResponse {
        <PollResponse as ::protobuf::Message>::default_instance()
    }
}

impl PollResponse {
    pub fn new() -> PollResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "target_id",
            |m: &PollResponse| { &m.target_id },
            |m: &mut PollResponse| { &mut m.target_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tag_data",
            |m: &PollResponse| { &m.tag_data },
            |m: &mut PollResponse| { &mut m.tag_data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PollResponse>(
            "PollResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PollResponse {
    const NAME: &'static str = "PollResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.target_id = is.read_uint32()?;
                },
                18 => {
                    self.tag_data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.target_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.target_id);
        }
        if !self.tag_data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.tag_data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.target_id != 0 {
            os.write_uint32(1, self.target_id)?;
        }
        if !self.tag_data.is_empty() {
            os.write_bytes(2, &self.tag_data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PollResponse {
        PollResponse::new()
    }

    fn clear(&mut self) {
        self.target_id = 0;
        self.tag_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PollResponse {
        static instance: PollResponse = PollResponse {
            target_id: 0,
            tag_data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PollResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PollResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PollResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PollResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.SendApduRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendApduRequest {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.SendApduRequest.chip_id)
    pub chip_id: u32,
    // @@protoc_insertion_point(field:netsim.nfc_service.SendApduRequest.apdu)
    pub apdu: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.SendApduRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendApduRequest {
    fn default() -> &'a SendApduRequest {
        <SendApduRequest as ::protobuf::Message>::default_instance()
    }
}

impl SendApduRequest {
    pub fn new() -> SendApduRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "chip_id",
            |m: &SendApduRequest| { &m.chip_id },
            |m: &mut SendApduRequest| { &mut m.chip_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "apdu",
            |m: &SendApduRequest| { &m.apdu },
            |m: &mut SendApduRequest| { &mut m.apdu },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendApduRequest>(
            "SendApduRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendApduRequest {
    const NAME: &'static str = "SendApduRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.chip_id = is.read_uint32()?;
                },
                18 => {
                    self.apdu = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.chip_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.chip_id);
        }
        if !self.apdu.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.apdu);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.chip_id != 0 {
            os.write_uint32(1, self.chip_id)?;
        }
        if !self.apdu.is_empty() {
            os.write_bytes(2, &self.apdu)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendApduRequest {
        SendApduRequest::new()
    }

    fn clear(&mut self) {
        self.chip_id = 0;
        self.apdu.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendApduRequest {
        static instance: SendApduRequest = SendApduRequest {
            chip_id: 0,
            apdu: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendApduRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendApduRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendApduRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendApduRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.nfc_service.SendApduResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SendApduResponse {
    // message fields
    // @@protoc_insertion_point(field:netsim.nfc_service.SendApduResponse.response)
    pub response: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.nfc_service.SendApduResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SendApduResponse {
    fn default() -> &'a SendApduResponse {
        <SendApduResponse as ::protobuf::Message>::default_instance()
    }
}

impl SendApduResponse {
    pub fn new() -> SendApduResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "response",
            |m: &SendApduResponse| { &m.response },
            |m: &mut SendApduResponse| { &mut m.response },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SendApduResponse>(
            "SendApduResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SendApduResponse {
    const NAME: &'static str = "SendApduResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.response = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.response.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.response);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.response.is_empty() {
            os.write_bytes(1, &self.response)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SendApduResponse {
        SendApduResponse::new()
    }

    fn clear(&mut self) {
        self.response.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SendApduResponse {
        static instance: SendApduResponse = SendApduResponse {
            response: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SendApduResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SendApduResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SendApduResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SendApduResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18netsim/nfc_service.proto\x12\x12netsim.nfc_service\x1a\x12netsim/m\
    odel.proto\"+\n\x10GetStatusRequest\x12\x17\n\x07chip_id\x18\x01\x20\x01\
    (\rR\x06chipId\"=\n\x11GetStatusResponse\x12(\n\x05chips\x18\x01\x20\x03\
    (\x0b2\x12.netsim.model.ChipR\x05chips\"E\n\x0fSetPowerRequest\x12\x17\n\
    \x07chip_id\x18\x01\x20\x01(\rR\x06chipId\x12\x19\n\x08power_on\x18\x02\
    \x20\x01(\x08R\x07powerOn\":\n\x10SetPowerResponse\x12&\n\x04chip\x18\
    \x01\x20\x01(\x0b2\x12.netsim.model.ChipR\x04chip\"&\n\x0bPollRequest\
    \x12\x17\n\x07chip_id\x18\x01\x20\x01(\rR\x06chipId\"F\n\x0cPollResponse\
    \x12\x1b\n\ttarget_id\x18\x01\x20\x01(\rR\x08targetId\x12\x19\n\x08tag_d\
    ata\x18\x02\x20\x01(\x0cR\x07tagData\">\n\x0fSendApduRequest\x12\x17\n\
    \x07chip_id\x18\x01\x20\x01(\rR\x06chipId\x12\x12\n\x04apdu\x18\x02\x20\
    \x01(\x0cR\x04apdu\".\n\x10SendApduResponse\x12\x1a\n\x08response\x18\
    \x01\x20\x01(\x0cR\x08response2\xe1\x02\n\nNfcService\x12X\n\tGetStatus\
    \x12$.netsim.nfc_service.GetStatusRequest\x1a%.netsim.nfc_service.GetSta\
    tusResponse\x12U\n\x08SetPower\x12#.netsim.nfc_service.SetPowerRequest\
    \x1a$.netsim.nfc_service.SetPowerResponse\x12K\n\x04Poll\x12\x1f.netsim.\
    nfc_service.PollRequest\x1a\x20.netsim.nfc_service.PollResponse0\x01\x12\
    U\n\x08SendApdu\x12#.netsim.nfc_service.SendApduRequest\x1a$.netsim.nfc_\
    service.SendApduResponseJ\xfe\x0b\n\x06\x12\x04\x03\08\x01\n_\n\x01\x0c\
    \x12\x03\x03\0\x122U\x20Copyright\x202026\x20The\x20Android\x20Open\x20S\
    ource\x20Project\n\x20SPDX-License-Identifier:\x20Apache-2.0\n\n\x08\n\
    \x01\x02\x12\x03\x05\0\x1b\n\t\n\x02\x03\0\x12\x03\x07\0\x1c\nB\n\x02\
    \x06\0\x12\x04\n\0\x13\x01\x1a6\x20Service\x20to\x20manage\x20NFC\x20cap\
    abilities\x20in\x20the\x20simulation\n\n\n\n\x03\x06\0\x01\x12\x03\n\x08\
    \x12\n2\n\x04\x06\0\x02\0\x12\x03\x0c\x02>\x1a%\x20Get\x20status\x20of\
    \x20one\x20or\x20all\x20NFC\x20chips.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\
    \x03\x0c\x06\x0f\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\x0c\x10\x20\n\x0c\n\
    \x05\x06\0\x02\0\x03\x12\x03\x0c+<\n:\n\x04\x06\0\x02\x01\x12\x03\x0e\
    \x02;\x1a-\x20Set\x20RF\x20power\x20state\x20(on/off)\x20of\x20an\x20NFC\
    \x20chip.\n\n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03\x0e\x06\x0e\n\x0c\n\
    \x05\x06\0\x02\x01\x02\x12\x03\x0e\x0f\x1e\n\x0c\n\x05\x06\0\x02\x01\x03\
    \x12\x03\x0e)9\nI\n\x04\x06\0\x02\x02\x12\x03\x10\x026\x1a<\x20Execute\
    \x20NFC\x20polling\x20sequence\x20against\x20the\x20simulation\x20scene.\
    \n\n\x0c\n\x05\x06\0\x02\x02\x01\x12\x03\x10\x06\n\n\x0c\n\x05\x06\0\x02\
    \x02\x02\x12\x03\x10\x0b\x16\n\x0c\n\x05\x06\0\x02\x02\x06\x12\x03\x10!'\
    \n\x0c\n\x05\x06\0\x02\x02\x03\x12\x03\x10(4\n=\n\x04\x06\0\x02\x03\x12\
    \x03\x12\x02;\x1a0\x20Transmit\x20APDU\x20packet\x20to\x20an\x20NFC\x20t\
    arget\x20or\x20chip.\n\n\x0c\n\x05\x06\0\x02\x03\x01\x12\x03\x12\x06\x0e\
    \n\x0c\n\x05\x06\0\x02\x03\x02\x12\x03\x12\x0f\x1e\n\x0c\n\x05\x06\0\x02\
    \x03\x03\x12\x03\x12)9\n\n\n\x02\x04\0\x12\x04\x15\0\x19\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x15\x08\x18\n`\n\x04\x04\0\x02\0\x12\x03\x18\x02\x15\
    \x1aS\x20Optional\x20ID\x20of\x20the\x20specific\x20chip\x20to\x20get\
    \x20status\x20for.\x20If\x200,\x20returns\x20all\x20NFC\n\x20chips.\n\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x03\x18\x02\x08\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\x18\t\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x18\x13\x14\n\
    \n\n\x02\x04\x01\x12\x04\x1b\0\x1d\x01\n\n\n\x03\x04\x01\x01\x12\x03\x1b\
    \x08\x19\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x1c\x02'\n\x0c\n\x05\x04\x01\
    \x02\0\x04\x12\x03\x1c\x02\n\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x1c\
    \x0b\x1c\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1c\x1d\"\n\x0c\n\x05\x04\
    \x01\x02\0\x03\x12\x03\x1c%&\n\n\n\x02\x04\x02\x12\x04\x1f\0\"\x01\n\n\n\
    \x03\x04\x02\x01\x12\x03\x1f\x08\x17\n\x0b\n\x04\x04\x02\x02\0\x12\x03\
    \x20\x02\x15\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x20\x02\x08\n\x0c\n\
    \x05\x04\x02\x02\0\x01\x12\x03\x20\t\x10\n\x0c\n\x05\x04\x02\x02\0\x03\
    \x12\x03\x20\x13\x14\n\x0b\n\x04\x04\x02\x02\x01\x12\x03!\x02\x14\n\x0c\
    \n\x05\x04\x02\x02\x01\x05\x12\x03!\x02\x06\n\x0c\n\x05\x04\x02\x02\x01\
    \x01\x12\x03!\x07\x0f\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03!\x12\x13\n\
    \n\n\x02\x04\x03\x12\x04$\0&\x01\n\n\n\x03\x04\x03\x01\x12\x03$\x08\x18\
    \n\x0b\n\x04\x04\x03\x02\0\x12\x03%\x02\x1d\n\x0c\n\x05\x04\x03\x02\0\
    \x06\x12\x03%\x02\x13\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03%\x14\x18\n\
    \x0c\n\x05\x04\x03\x02\0\x03\x12\x03%\x1b\x1c\n\n\n\x02\x04\x04\x12\x04(\
    \0*\x01\n\n\n\x03\x04\x04\x01\x12\x03(\x08\x13\n\x0b\n\x04\x04\x04\x02\0\
    \x12\x03)\x02\x15\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03)\x02\x08\n\x0c\n\
    \x05\x04\x04\x02\0\x01\x12\x03)\t\x10\n\x0c\n\x05\x04\x04\x02\0\x03\x12\
    \x03)\x13\x14\n\n\n\x02\x04\x05\x12\x04,\0/\x01\n\n\n\x03\x04\x05\x01\
    \x12\x03,\x08\x14\n\x0b\n\x04\x04\x05\x02\0\x12\x03-\x02\x17\n\x0c\n\x05\
    \x04\x05\x02\0\x05\x12\x03-\x02\x08\n\x0c\n\x05\x04\x05\x02\0\x01\x12\
    \x03-\t\x12\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03-\x15\x16\n\x0b\n\x04\
    \x04\x05\x02\x01\x12\x03.\x02\x15\n\x0c\n\x05\x04\x05\x02\x01\x05\x12\
    \x03.\x02\x07\n\x0c\n\x05\x04\x05\x02\x01\x01\x12\x03.\x08\x10\n\x0c\n\
    \x05\x04\x05\x02\x01\x03\x12\x03.\x13\x14\n\n\n\x02\x04\x06\x12\x041\04\
    \x01\n\n\n\x03\x04\x06\x01\x12\x031\x08\x17\n\x0b\n\x04\x04\x06\x02\0\
    \x12\x032\x02\x15\n\x0c\n\x05\x04\x06\x02\0\x05\x12\x032\x02\x08\n\x0c\n\
    \x05\x04\x06\x02\0\x01\x12\x032\t\x10\n\x0c\n\x05\x04\x06\x02\0\x03\x12\
    \x032\x13\x14\n\x0b\n\x04\x04\x06\x02\x01\x12\x033\x02\x11\n\x0c\n\x05\
    \x04\x06\x02\x01\x05\x12\x033\x02\x07\n\x0c\n\x05\x04\x06\x02\x01\x01\
    \x12\x033\x08\x0c\n\x0c\n\x05\x04\x06\x02\x01\x03\x12\x033\x0f\x10\n\n\n\
    \x02\x04\x07\x12\x046\08\x01\n\n\n\x03\x04\x07\x01\x12\x036\x08\x18\n\
    \x0b\n\x04\x04\x07\x02\0\x12\x037\x02\x15\n\x0c\n\x05\x04\x07\x02\0\x05\
    \x12\x037\x02\x07\n\x0c\n\x05\x04\x07\x02\0\x01\x12\x037\x08\x10\n\x0c\n\
    \x05\x04\x07\x02\0\x03\x12\x037\x13\x14b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::model::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(GetStatusRequest::generated_message_descriptor_data());
            messages.push(GetStatusResponse::generated_message_descriptor_data());
            messages.push(SetPowerRequest::generated_message_descriptor_data());
            messages.push(SetPowerResponse::generated_message_descriptor_data());
            messages.push(PollRequest::generated_message_descriptor_data());
            messages.push(PollResponse::generated_message_descriptor_data());
            messages.push(SendApduRequest::generated_message_descriptor_data());
            messages.push(SendApduResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
