// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `netsim/startup.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:netsim.startup.StartupInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StartupInfo {
    // message fields
    // @@protoc_insertion_point(field:netsim.startup.StartupInfo.devices)
    pub devices: ::std::vec::Vec<startup_info::Device>,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.startup.StartupInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StartupInfo {
    fn default() -> &'a StartupInfo {
        <StartupInfo as ::protobuf::Message>::default_instance()
    }
}

impl StartupInfo {
    pub fn new() -> StartupInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "devices",
            |m: &StartupInfo| { &m.devices },
            |m: &mut StartupInfo| { &mut m.devices },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StartupInfo>(
            "StartupInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StartupInfo {
    const NAME: &'static str = "StartupInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.devices.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.devices {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.devices {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StartupInfo {
        StartupInfo::new()
    }

    fn clear(&mut self) {
        self.devices.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StartupInfo {
        static instance: StartupInfo = StartupInfo {
            devices: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StartupInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StartupInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StartupInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StartupInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `StartupInfo`
pub mod startup_info {
    // @@protoc_insertion_point(message:netsim.startup.StartupInfo.Device)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Device {
        // message fields
        ///  Deprecated. Field moved into DeviceInfo. Please use device_info instead.
        // @@protoc_insertion_point(field:netsim.startup.StartupInfo.Device.name)
        pub name: ::std::string::String,
        ///  list of SoCs associated with device
        // @@protoc_insertion_point(field:netsim.startup.StartupInfo.Device.chips)
        pub chips: ::std::vec::Vec<super::Chip>,
        ///  additional device information
        // @@protoc_insertion_point(field:netsim.startup.StartupInfo.Device.device_info)
        pub device_info: ::protobuf::MessageField<super::DeviceInfo>,
        // special fields
        // @@protoc_insertion_point(special_field:netsim.startup.StartupInfo.Device.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Device {
        fn default() -> &'a Device {
            <Device as ::protobuf::Message>::default_instance()
        }
    }

    impl Device {
        pub fn new() -> Device {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(3);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "name",
                |m: &Device| { &m.name },
                |m: &mut Device| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "chips",
                |m: &Device| { &m.chips },
                |m: &mut Device| { &mut m.chips },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::DeviceInfo>(
                "device_info",
                |m: &Device| { &m.device_info },
                |m: &mut Device| { &mut m.device_info },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Device>(
                "StartupInfo.Device",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Device {
        const NAME: &'static str = "Device";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.name = is.read_string()?;
                    },
                    18 => {
                        self.chips.push(is.read_message()?);
                    },
                    26 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.device_info)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.name.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.name);
            }
            for value in &self.chips {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            if let Some(v) = self.device_info.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.name.is_empty() {
                os.write_string(1, &self.name)?;
            }
            for v in &self.chips {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            };
            if let Some(v) = self.device_info.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Device {
            Device::new()
        }

        fn clear(&mut self) {
            self.name.clear();
            self.chips.clear();
            self.device_info.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Device {
            static instance: Device = Device {
                name: ::std::string::String::new(),
                chips: ::std::vec::Vec::new(),
                device_info: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Device {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("StartupInfo.Device").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Device {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Device {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

///  TODO: rename to InitialInfo
///  InitialInfo over gRPC
// @@protoc_insertion_point(message:netsim.startup.ChipInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ChipInfo {
    // message fields
    ///  Deprecated. Field moved into DeviceInfo. Please use device_info instead.
    // @@protoc_insertion_point(field:netsim.startup.ChipInfo.name)
    pub name: ::std::string::String,
    ///  single chip
    // @@protoc_insertion_point(field:netsim.startup.ChipInfo.chip)
    pub chip: ::protobuf::MessageField<Chip>,
    ///  additional device information
    // @@protoc_insertion_point(field:netsim.startup.ChipInfo.device_info)
    pub device_info: ::protobuf::MessageField<DeviceInfo>,
    ///  True if this connection is a result of a host reconnect event.
    // @@protoc_insertion_point(field:netsim.startup.ChipInfo.is_host_reconnect)
    pub is_host_reconnect: bool,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.startup.ChipInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ChipInfo {
    fn default() -> &'a ChipInfo {
        <ChipInfo as ::protobuf::Message>::default_instance()
    }
}

impl ChipInfo {
    pub fn new() -> ChipInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &ChipInfo| { &m.name },
            |m: &mut ChipInfo| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Chip>(
            "chip",
            |m: &ChipInfo| { &m.chip },
            |m: &mut ChipInfo| { &mut m.chip },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, DeviceInfo>(
            "device_info",
            |m: &ChipInfo| { &m.device_info },
            |m: &mut ChipInfo| { &mut m.device_info },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_host_reconnect",
            |m: &ChipInfo| { &m.is_host_reconnect },
            |m: &mut ChipInfo| { &mut m.is_host_reconnect },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ChipInfo>(
            "ChipInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ChipInfo {
    const NAME: &'static str = "ChipInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.chip)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.device_info)?;
                },
                32 => {
                    self.is_host_reconnect = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if let Some(v) = self.chip.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.device_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.is_host_reconnect != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if let Some(v) = self.chip.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.device_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.is_host_reconnect != false {
            os.write_bool(4, self.is_host_reconnect)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ChipInfo {
        ChipInfo::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.chip.clear();
        self.device_info.clear();
        self.is_host_reconnect = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ChipInfo {
        static instance: ChipInfo = ChipInfo {
            name: ::std::string::String::new(),
            chip: ::protobuf::MessageField::none(),
            device_info: ::protobuf::MessageField::none(),
            is_host_reconnect: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ChipInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ChipInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ChipInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChipInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.startup.DeviceInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DeviceInfo {
    // message fields
    ///  Name of device
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.name)
    pub name: ::std::string::String,
    ///  Identifier for device kind e.g. EMULATOR, CUTTLEFISH, BUMBLE, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.kind)
    pub kind: ::std::string::String,
    ///  Version info as applicable e.g. Android emulator version 34.1.15.0, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.version)
    pub version: ::std::string::String,
    ///  SDK version info as applicable e.g. 33, 34, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.sdk_version)
    pub sdk_version: ::std::string::String,
    ///  Build ID e.g. TE1A.220922.034, UQ1A.231205.015, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.build_id)
    pub build_id: ::std::string::String,
    ///  Model/variant e.g. sdk_gphone_x86_64-userdebug, cf_x86_64_phone-user, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.variant)
    pub variant: ::std::string::String,
    ///  CPU architecture e.g. x86_64, arm64-v8a, etc
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.arch)
    pub arch: ::std::string::String,
    ///  AVD ini filepath
    // @@protoc_insertion_point(field:netsim.startup.DeviceInfo.avd_path)
    pub avd_path: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.startup.DeviceInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DeviceInfo {
    fn default() -> &'a DeviceInfo {
        <DeviceInfo as ::protobuf::Message>::default_instance()
    }
}

impl DeviceInfo {
    pub fn new() -> DeviceInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &DeviceInfo| { &m.name },
            |m: &mut DeviceInfo| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "kind",
            |m: &DeviceInfo| { &m.kind },
            |m: &mut DeviceInfo| { &mut m.kind },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "version",
            |m: &DeviceInfo| { &m.version },
            |m: &mut DeviceInfo| { &mut m.version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sdk_version",
            |m: &DeviceInfo| { &m.sdk_version },
            |m: &mut DeviceInfo| { &mut m.sdk_version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "build_id",
            |m: &DeviceInfo| { &m.build_id },
            |m: &mut DeviceInfo| { &mut m.build_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "variant",
            |m: &DeviceInfo| { &m.variant },
            |m: &mut DeviceInfo| { &mut m.variant },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "arch",
            |m: &DeviceInfo| { &m.arch },
            |m: &mut DeviceInfo| { &mut m.arch },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "avd_path",
            |m: &DeviceInfo| { &m.avd_path },
            |m: &mut DeviceInfo| { &mut m.avd_path },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DeviceInfo>(
            "DeviceInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DeviceInfo {
    const NAME: &'static str = "DeviceInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.kind = is.read_string()?;
                },
                26 => {
                    self.version = is.read_string()?;
                },
                34 => {
                    self.sdk_version = is.read_string()?;
                },
                42 => {
                    self.build_id = is.read_string()?;
                },
                50 => {
                    self.variant = is.read_string()?;
                },
                58 => {
                    self.arch = is.read_string()?;
                },
                66 => {
                    self.avd_path = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.kind.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.kind);
        }
        if !self.version.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.version);
        }
        if !self.sdk_version.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.sdk_version);
        }
        if !self.build_id.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.build_id);
        }
        if !self.variant.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.variant);
        }
        if !self.arch.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.arch);
        }
        if !self.avd_path.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.avd_path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.kind.is_empty() {
            os.write_string(2, &self.kind)?;
        }
        if !self.version.is_empty() {
            os.write_string(3, &self.version)?;
        }
        if !self.sdk_version.is_empty() {
            os.write_string(4, &self.sdk_version)?;
        }
        if !self.build_id.is_empty() {
            os.write_string(5, &self.build_id)?;
        }
        if !self.variant.is_empty() {
            os.write_string(6, &self.variant)?;
        }
        if !self.arch.is_empty() {
            os.write_string(7, &self.arch)?;
        }
        if !self.avd_path.is_empty() {
            os.write_string(8, &self.avd_path)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DeviceInfo {
        DeviceInfo::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.kind.clear();
        self.version.clear();
        self.sdk_version.clear();
        self.build_id.clear();
        self.variant.clear();
        self.arch.clear();
        self.avd_path.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DeviceInfo {
        static instance: DeviceInfo = DeviceInfo {
            name: ::std::string::String::new(),
            kind: ::std::string::String::new(),
            version: ::std::string::String::new(),
            sdk_version: ::std::string::String::new(),
            build_id: ::std::string::String::new(),
            variant: ::std::string::String::new(),
            arch: ::std::string::String::new(),
            avd_path: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DeviceInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DeviceInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DeviceInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeviceInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:netsim.startup.Chip)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Chip {
    // message fields
    ///  the kind of chip
    // @@protoc_insertion_point(field:netsim.startup.Chip.kind)
    pub kind: ::protobuf::EnumOrUnknown<super::common::ChipKind>,
    ///  optional like "rear-right"
    // @@protoc_insertion_point(field:netsim.startup.Chip.id)
    pub id: ::std::string::String,
    ///  optional like Quorvo
    // @@protoc_insertion_point(field:netsim.startup.Chip.manufacturer)
    pub manufacturer: ::std::string::String,
    ///  optional like DW300
    // @@protoc_insertion_point(field:netsim.startup.Chip.product_name)
    pub product_name: ::std::string::String,
    ///  optional guest os input
    // @@protoc_insertion_point(field:netsim.startup.Chip.fd_in)
    pub fd_in: i32,
    ///  optional guest os output
    // @@protoc_insertion_point(field:netsim.startup.Chip.fd_out)
    pub fd_out: i32,
    ///  optional for testing
    // @@protoc_insertion_point(field:netsim.startup.Chip.loopback)
    pub loopback: bool,
    ///  optional for bluetooth chipsets
    // @@protoc_insertion_point(field:netsim.startup.Chip.bt_properties)
    pub bt_properties: ::protobuf::MessageField<super::configuration::Controller>,
    ///  address in format xx:xx:xx:xx:xx:xx
    ///  optional for bluetooth chipsets
    // @@protoc_insertion_point(field:netsim.startup.Chip.address)
    pub address: ::std::string::String,
    ///  Offset of the chip position from center of device
    // @@protoc_insertion_point(field:netsim.startup.Chip.offset)
    pub offset: ::protobuf::MessageField<super::model::Position>,
    ///  Sim type for modem simulator (1 for normal, 2 for CtsCarrierApiTestCases)
    // @@protoc_insertion_point(field:netsim.startup.Chip.sim_type)
    pub sim_type: i32,
    // special fields
    // @@protoc_insertion_point(special_field:netsim.startup.Chip.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Chip {
    fn default() -> &'a Chip {
        <Chip as ::protobuf::Message>::default_instance()
    }
}

impl Chip {
    pub fn new() -> Chip {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(11);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "kind",
            |m: &Chip| { &m.kind },
            |m: &mut Chip| { &mut m.kind },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Chip| { &m.id },
            |m: &mut Chip| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "manufacturer",
            |m: &Chip| { &m.manufacturer },
            |m: &mut Chip| { &mut m.manufacturer },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "product_name",
            |m: &Chip| { &m.product_name },
            |m: &mut Chip| { &mut m.product_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "fd_in",
            |m: &Chip| { &m.fd_in },
            |m: &mut Chip| { &mut m.fd_in },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "fd_out",
            |m: &Chip| { &m.fd_out },
            |m: &mut Chip| { &mut m.fd_out },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "loopback",
            |m: &Chip| { &m.loopback },
            |m: &mut Chip| { &mut m.loopback },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::configuration::Controller>(
            "bt_properties",
            |m: &Chip| { &m.bt_properties },
            |m: &mut Chip| { &mut m.bt_properties },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "address",
            |m: &Chip| { &m.address },
            |m: &mut Chip| { &mut m.address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::model::Position>(
            "offset",
            |m: &Chip| { &m.offset },
            |m: &mut Chip| { &mut m.offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sim_type",
            |m: &Chip| { &m.sim_type },
            |m: &mut Chip| { &mut m.sim_type },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Chip>(
            "Chip",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Chip {
    const NAME: &'static str = "Chip";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.kind = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.id = is.read_string()?;
                },
                26 => {
                    self.manufacturer = is.read_string()?;
                },
                34 => {
                    self.product_name = is.read_string()?;
                },
                40 => {
                    self.fd_in = is.read_int32()?;
                },
                48 => {
                    self.fd_out = is.read_int32()?;
                },
                56 => {
                    self.loopback = is.read_bool()?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.bt_properties)?;
                },
                74 => {
                    self.address = is.read_string()?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.offset)?;
                },
                88 => {
                    self.sim_type = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.kind != ::protobuf::EnumOrUnknown::new(super::common::ChipKind::UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.kind.value());
        }
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.id);
        }
        if !self.manufacturer.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.manufacturer);
        }
        if !self.product_name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.product_name);
        }
        if self.fd_in != 0 {
            my_size += ::protobuf::rt::int32_size(5, self.fd_in);
        }
        if self.fd_out != 0 {
            my_size += ::protobuf::rt::int32_size(6, self.fd_out);
        }
        if self.loopback != false {
            my_size += 1 + 1;
        }
        if let Some(v) = self.bt_properties.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.address);
        }
        if let Some(v) = self.offset.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.sim_type != 0 {
            my_size += ::protobuf::rt::int32_size(11, self.sim_type);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.kind != ::protobuf::EnumOrUnknown::new(super::common::ChipKind::UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.kind))?;
        }
        if !self.id.is_empty() {
            os.write_string(2, &self.id)?;
        }
        if !self.manufacturer.is_empty() {
            os.write_string(3, &self.manufacturer)?;
        }
        if !self.product_name.is_empty() {
            os.write_string(4, &self.product_name)?;
        }
        if self.fd_in != 0 {
            os.write_int32(5, self.fd_in)?;
        }
        if self.fd_out != 0 {
            os.write_int32(6, self.fd_out)?;
        }
        if self.loopback != false {
            os.write_bool(7, self.loopback)?;
        }
        if let Some(v) = self.bt_properties.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if !self.address.is_empty() {
            os.write_string(9, &self.address)?;
        }
        if let Some(v) = self.offset.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if self.sim_type != 0 {
            os.write_int32(11, self.sim_type)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Chip {
        Chip::new()
    }

    fn clear(&mut self) {
        self.kind = ::protobuf::EnumOrUnknown::new(super::common::ChipKind::UNSPECIFIED);
        self.id.clear();
        self.manufacturer.clear();
        self.product_name.clear();
        self.fd_in = 0;
        self.fd_out = 0;
        self.loopback = false;
        self.bt_properties.clear();
        self.address.clear();
        self.offset.clear();
        self.sim_type = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Chip {
        static instance: Chip = Chip {
            kind: ::protobuf::EnumOrUnknown::from_i32(0),
            id: ::std::string::String::new(),
            manufacturer: ::std::string::String::new(),
            product_name: ::std::string::String::new(),
            fd_in: 0,
            fd_out: 0,
            loopback: false,
            bt_properties: ::protobuf::MessageField::none(),
            address: ::std::string::String::new(),
            offset: ::protobuf::MessageField::none(),
            sim_type: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Chip {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Chip").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Chip {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Chip {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14netsim/startup.proto\x12\x0enetsim.startup\x1a\x13netsim/common.pr\
    oto\x1a\x12netsim/model.proto\x1a\x1drootcanal/configuration.proto\"\xd7\
    \x01\n\x0bStartupInfo\x12<\n\x07devices\x18\x01\x20\x03(\x0b2\".netsim.s\
    tartup.StartupInfo.DeviceR\x07devices\x1a\x89\x01\n\x06Device\x12\x16\n\
    \x04name\x18\x01\x20\x01(\tR\x04nameB\x02\x18\x01\x12*\n\x05chips\x18\
    \x02\x20\x03(\x0b2\x14.netsim.startup.ChipR\x05chips\x12;\n\x0bdevice_in\
    fo\x18\x03\x20\x01(\x0b2\x1a.netsim.startup.DeviceInfoR\ndeviceInfo\"\
    \xb5\x01\n\x08ChipInfo\x12\x16\n\x04name\x18\x01\x20\x01(\tR\x04nameB\
    \x02\x18\x01\x12(\n\x04chip\x18\x02\x20\x01(\x0b2\x14.netsim.startup.Chi\
    pR\x04chip\x12;\n\x0bdevice_info\x18\x03\x20\x01(\x0b2\x1a.netsim.startu\
    p.DeviceInfoR\ndeviceInfo\x12*\n\x11is_host_reconnect\x18\x04\x20\x01(\
    \x08R\x0fisHostReconnect\"\xd3\x01\n\nDeviceInfo\x12\x12\n\x04name\x18\
    \x01\x20\x01(\tR\x04name\x12\x12\n\x04kind\x18\x02\x20\x01(\tR\x04kind\
    \x12\x18\n\x07version\x18\x03\x20\x01(\tR\x07version\x12\x1f\n\x0bsdk_ve\
    rsion\x18\x04\x20\x01(\tR\nsdkVersion\x12\x19\n\x08build_id\x18\x05\x20\
    \x01(\tR\x07buildId\x12\x18\n\x07variant\x18\x06\x20\x01(\tR\x07variant\
    \x12\x12\n\x04arch\x18\x07\x20\x01(\tR\x04arch\x12\x19\n\x08avd_path\x18\
    \x08\x20\x01(\tR\x07avdPath\"\x91\x03\n\x04Chip\x12+\n\x04kind\x18\x01\
    \x20\x01(\x0e2\x17.netsim.common.ChipKindR\x04kind\x12\x0e\n\x02id\x18\
    \x02\x20\x01(\tR\x02id\x12\"\n\x0cmanufacturer\x18\x03\x20\x01(\tR\x0cma\
    nufacturer\x12!\n\x0cproduct_name\x18\x04\x20\x01(\tR\x0bproductName\x12\
    \x13\n\x05fd_in\x18\x05\x20\x01(\x05R\x04fdIn\x12\x15\n\x06fd_out\x18\
    \x06\x20\x01(\x05R\x05fdOut\x12\x1a\n\x08loopback\x18\x07\x20\x01(\x08R\
    \x08loopback\x12H\n\rbt_properties\x18\x08\x20\x01(\x0b2#.rootcanal.conf\
    iguration.ControllerR\x0cbtProperties\x12\x18\n\x07address\x18\t\x20\x01\
    (\tR\x07address\x123\n\x06offset\x18\n\x20\x01(\x0b2\x16.netsim.model.Po\
    sitionH\0R\x06offset\x88\x01\x01\x12\x19\n\x08sim_type\x18\x0b\x20\x01(\
    \x05R\x07simTypeB\t\n\x07_offsetB#\n\x1fcom.android.emulation.bluetoothP\
    \x01J\xd8\x1c\n\x06\x12\x04\x03\0i\x01\n_\n\x01\x0c\x12\x03\x03\0\x122U\
    \x20Copyright\x202022\x20The\x20Android\x20Open\x20Source\x20Project\n\
    \x20SPDX-License-Identifier:\x20Apache-2.0\n\n\x08\n\x01\x02\x12\x03\x05\
    \0\x17\n\t\n\x02\x03\0\x12\x03\x07\0\x1d\n\t\n\x02\x03\x01\x12\x03\x08\0\
    \x1c\n\t\n\x02\x03\x02\x12\x03\t\0'\n\x08\n\x01\x08\x12\x03\x0b\0\"\n\t\
    \n\x02\x08\n\x12\x03\x0b\0\"\n\x08\n\x01\x08\x12\x03\x0c\08\n\t\n\x02\
    \x08\x01\x12\x03\x0c\08\n\x96\x04\n\x02\x04\0\x12\x04%\0/\x012\x89\x04*\
    \n\x20The\x20startup\x20info\x20proto.\n\n\x20When\x20netsim\x20is\x20fo\
    rked\x20from\x20a\x20parent\x20that\x20owns\x20all\x20fds\x20for\x20HAL\
    \x20communication\n\x20(like\x20launch_cvd)\x20it\x20uses\x20json\x20for\
    mat\x20of\x20this\x20proto.\n\n\x20Example:\n\n\x20netsim\x20-s\x20'\n\
    \x20\x20\x20{\"devices\":\x20[\n\x20\x20\x20\x20\x20\x20{serial:\x20\"em\
    ulator-5554\",\n\x20\x20\x20\x20\x20\x20\x20chips:\x20[{kind:\x20\"WIFI\
    \",\x20fdIn:\x201,\x20fdOut:\x202},\n\x20\x20\x20\x20\x20\x20\x20\x20\
    \x20\x20\x20\x20\x20\x20\x20{kind:\x20\"BLUETOOTH\",\x20fdIn:\x2020,\x20\
    fdOut:21}]\n\x20\x20\x20\x20\x20\x20},\n\x20\x20\x20\x20\x20\x20{serial:\
    \x20\"emulator-5555\",\n\x20\x20\x20\x20\x20\x20\x20chips:\x20[{kind:\
    \x20\"BLUETOOTH\",\x20fdIn:\x203,\x20fdOut:\x204},\n\x20\x20\x20\x20\x20\
    \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20{kind:\x20\"UWB\",\x20fdIn:\x205\
    ,\x20fdOut:\x206,\x20model:\x20\"DW300\"}]\n\x20\x20\x20\x20\x20\x20}\n\
    \x20\x20\x20\x20]\n\x20\x20\x20}'\n\n\n\n\n\x03\x04\0\x01\x12\x03%\x08\
    \x13\n\x0c\n\x04\x04\0\x03\0\x12\x04&\x02-\x03\n\x0c\n\x05\x04\0\x03\0\
    \x01\x12\x03&\n\x10\nY\n\x06\x04\0\x03\0\x02\0\x12\x03(\x04(\x1aJ\x20Dep\
    recated.\x20Field\x20moved\x20into\x20DeviceInfo.\x20Please\x20use\x20de\
    vice_info\x20instead.\n\n\x0e\n\x07\x04\0\x03\0\x02\0\x05\x12\x03(\x04\n\
    \n\x0e\n\x07\x04\0\x03\0\x02\0\x01\x12\x03(\x0b\x0f\n\x0e\n\x07\x04\0\
    \x03\0\x02\0\x03\x12\x03(\x12\x13\n\x0e\n\x07\x04\0\x03\0\x02\0\x08\x12\
    \x03(\x14'\n\x0f\n\x08\x04\0\x03\0\x02\0\x08\x03\x12\x03(\x15&\n4\n\x06\
    \x04\0\x03\0\x02\x01\x12\x03*\x04\x1c\x1a%\x20list\x20of\x20SoCs\x20asso\
    ciated\x20with\x20device\n\n\x0e\n\x07\x04\0\x03\0\x02\x01\x04\x12\x03*\
    \x04\x0c\n\x0e\n\x07\x04\0\x03\0\x02\x01\x06\x12\x03*\r\x11\n\x0e\n\x07\
    \x04\0\x03\0\x02\x01\x01\x12\x03*\x12\x17\n\x0e\n\x07\x04\0\x03\0\x02\
    \x01\x03\x12\x03*\x1a\x1b\n.\n\x06\x04\0\x03\0\x02\x02\x12\x03,\x04\x1f\
    \x1a\x1f\x20additional\x20device\x20information\n\n\x0e\n\x07\x04\0\x03\
    \0\x02\x02\x06\x12\x03,\x04\x0e\n\x0e\n\x07\x04\0\x03\0\x02\x02\x01\x12\
    \x03,\x0f\x1a\n\x0e\n\x07\x04\0\x03\0\x02\x02\x03\x12\x03,\x1d\x1e\n\x0b\
    \n\x04\x04\0\x02\0\x12\x03.\x02\x1e\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03.\
    \x02\n\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03.\x0b\x11\n\x0c\n\x05\x04\0\
    \x02\0\x01\x12\x03.\x12\x19\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03.\x1c\x1d\
    \n@\n\x02\x04\x01\x12\x043\0<\x01\x1a4\x20TODO:\x20rename\x20to\x20Initi\
    alInfo\n\x20InitialInfo\x20over\x20gRPC\n\n\n\n\x03\x04\x01\x01\x12\x033\
    \x08\x10\nW\n\x04\x04\x01\x02\0\x12\x035\x02&\x1aJ\x20Deprecated.\x20Fie\
    ld\x20moved\x20into\x20DeviceInfo.\x20Please\x20use\x20device_info\x20in\
    stead.\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x035\x02\x08\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x035\t\r\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x035\x10\
    \x11\n\x0c\n\x05\x04\x01\x02\0\x08\x12\x035\x12%\n\r\n\x06\x04\x01\x02\0\
    \x08\x03\x12\x035\x13$\n\x1a\n\x04\x04\x01\x02\x01\x12\x037\x02\x10\x1a\
    \r\x20single\x20chip\n\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x037\x02\x06\
    \n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x037\x07\x0b\n\x0c\n\x05\x04\x01\
    \x02\x01\x03\x12\x037\x0e\x0f\n,\n\x04\x04\x01\x02\x02\x12\x039\x02\x1d\
    \x1a\x1f\x20additional\x20device\x20information\n\n\x0c\n\x05\x04\x01\
    \x02\x02\x06\x12\x039\x02\x0c\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x039\r\
    \x18\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x039\x1b\x1c\nM\n\x04\x04\x01\
    \x02\x03\x12\x03;\x02\x1d\x1a@\x20True\x20if\x20this\x20connection\x20is\
    \x20a\x20result\x20of\x20a\x20host\x20reconnect\x20event.\n\n\x0c\n\x05\
    \x04\x01\x02\x03\x05\x12\x03;\x02\x06\n\x0c\n\x05\x04\x01\x02\x03\x01\
    \x12\x03;\x07\x18\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03;\x1b\x1c\n\n\n\
    \x02\x04\x02\x12\x04>\0O\x01\n\n\n\x03\x04\x02\x01\x12\x03>\x08\x12\n\
    \x1d\n\x04\x04\x02\x02\0\x12\x03@\x02\x12\x1a\x10\x20Name\x20of\x20devic\
    e\n\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03@\x02\x08\n\x0c\n\x05\x04\x02\
    \x02\0\x01\x12\x03@\t\r\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03@\x10\x11\n\
    P\n\x04\x04\x02\x02\x01\x12\x03B\x02\x12\x1aC\x20Identifier\x20for\x20de\
    vice\x20kind\x20e.g.\x20EMULATOR,\x20CUTTLEFISH,\x20BUMBLE,\x20etc\n\n\
    \x0c\n\x05\x04\x02\x02\x01\x05\x12\x03B\x02\x08\n\x0c\n\x05\x04\x02\x02\
    \x01\x01\x12\x03B\t\r\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03B\x10\x11\n\
    V\n\x04\x04\x02\x02\x02\x12\x03D\x02\x15\x1aI\x20Version\x20info\x20as\
    \x20applicable\x20e.g.\x20Android\x20emulator\x20version\x2034.1.15.0,\
    \x20etc\n\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x03D\x02\x08\n\x0c\n\x05\
    \x04\x02\x02\x02\x01\x12\x03D\t\x10\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\
    \x03D\x13\x14\n>\n\x04\x04\x02\x02\x03\x12\x03F\x02\x19\x1a1\x20SDK\x20v\
    ersion\x20info\x20as\x20applicable\x20e.g.\x2033,\x2034,\x20etc\n\n\x0c\
    \n\x05\x04\x02\x02\x03\x05\x12\x03F\x02\x08\n\x0c\n\x05\x04\x02\x02\x03\
    \x01\x12\x03F\t\x14\n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x03F\x17\x18\nB\
    \n\x04\x04\x02\x02\x04\x12\x03H\x02\x16\x1a5\x20Build\x20ID\x20e.g.\x20T\
    E1A.220922.034,\x20UQ1A.231205.015,\x20etc\n\n\x0c\n\x05\x04\x02\x02\x04\
    \x05\x12\x03H\x02\x08\n\x0c\n\x05\x04\x02\x02\x04\x01\x12\x03H\t\x11\n\
    \x0c\n\x05\x04\x02\x02\x04\x03\x12\x03H\x14\x15\nX\n\x04\x04\x02\x02\x05\
    \x12\x03J\x02\x15\x1aK\x20Model/variant\x20e.g.\x20sdk_gphone_x86_64-use\
    rdebug,\x20cf_x86_64_phone-user,\x20etc\n\n\x0c\n\x05\x04\x02\x02\x05\
    \x05\x12\x03J\x02\x08\n\x0c\n\x05\x04\x02\x02\x05\x01\x12\x03J\t\x10\n\
    \x0c\n\x05\x04\x02\x02\x05\x03\x12\x03J\x13\x14\n;\n\x04\x04\x02\x02\x06\
    \x12\x03L\x02\x12\x1a.\x20CPU\x20architecture\x20e.g.\x20x86_64,\x20arm6\
    4-v8a,\x20etc\n\n\x0c\n\x05\x04\x02\x02\x06\x05\x12\x03L\x02\x08\n\x0c\n\
    \x05\x04\x02\x02\x06\x01\x12\x03L\t\r\n\x0c\n\x05\x04\x02\x02\x06\x03\
    \x12\x03L\x10\x11\n\x1f\n\x04\x04\x02\x02\x07\x12\x03N\x02\x16\x1a\x12\
    \x20AVD\x20ini\x20filepath\n\n\x0c\n\x05\x04\x02\x02\x07\x05\x12\x03N\
    \x02\x08\n\x0c\n\x05\x04\x02\x02\x07\x01\x12\x03N\t\x11\n\x0c\n\x05\x04\
    \x02\x02\x07\x03\x12\x03N\x14\x15\n\n\n\x02\x04\x03\x12\x04Q\0i\x01\n\n\
    \n\x03\x04\x03\x01\x12\x03Q\x08\x0c\n\x1f\n\x04\x04\x03\x02\0\x12\x03S\
    \x02\x1b\x1a\x12\x20the\x20kind\x20of\x20chip\n\n\x0c\n\x05\x04\x03\x02\
    \0\x06\x12\x03S\x02\x11\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03S\x12\x16\n\
    \x0c\n\x05\x04\x03\x02\0\x03\x12\x03S\x19\x1a\n)\n\x04\x04\x03\x02\x01\
    \x12\x03U\x02\x10\x1a\x1c\x20optional\x20like\x20\"rear-right\"\n\n\x0c\
    \n\x05\x04\x03\x02\x01\x05\x12\x03U\x02\x08\n\x0c\n\x05\x04\x03\x02\x01\
    \x01\x12\x03U\t\x0b\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03U\x0e\x0f\n#\
    \n\x04\x04\x03\x02\x02\x12\x03W\x02\x1a\x1a\x16\x20optional\x20like\x20Q\
    uorvo\n\n\x0c\n\x05\x04\x03\x02\x02\x05\x12\x03W\x02\x08\n\x0c\n\x05\x04\
    \x03\x02\x02\x01\x12\x03W\t\x15\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03W\
    \x18\x19\n\"\n\x04\x04\x03\x02\x03\x12\x03Y\x02\x1a\x1a\x15\x20optional\
    \x20like\x20DW300\n\n\x0c\n\x05\x04\x03\x02\x03\x05\x12\x03Y\x02\x08\n\
    \x0c\n\x05\x04\x03\x02\x03\x01\x12\x03Y\t\x15\n\x0c\n\x05\x04\x03\x02\
    \x03\x03\x12\x03Y\x18\x19\n&\n\x04\x04\x03\x02\x04\x12\x03[\x02\x12\x1a\
    \x19\x20optional\x20guest\x20os\x20input\n\n\x0c\n\x05\x04\x03\x02\x04\
    \x05\x12\x03[\x02\x07\n\x0c\n\x05\x04\x03\x02\x04\x01\x12\x03[\x08\r\n\
    \x0c\n\x05\x04\x03\x02\x04\x03\x12\x03[\x10\x11\n'\n\x04\x04\x03\x02\x05\
    \x12\x03]\x02\x13\x1a\x1a\x20optional\x20guest\x20os\x20output\n\n\x0c\n\
    \x05\x04\x03\x02\x05\x05\x12\x03]\x02\x07\n\x0c\n\x05\x04\x03\x02\x05\
    \x01\x12\x03]\x08\x0e\n\x0c\n\x05\x04\x03\x02\x05\x03\x12\x03]\x11\x12\n\
    #\n\x04\x04\x03\x02\x06\x12\x03_\x02\x14\x1a\x16\x20optional\x20for\x20t\
    esting\n\n\x0c\n\x05\x04\x03\x02\x06\x05\x12\x03_\x02\x06\n\x0c\n\x05\
    \x04\x03\x02\x06\x01\x12\x03_\x07\x0f\n\x0c\n\x05\x04\x03\x02\x06\x03\
    \x12\x03_\x12\x13\n.\n\x04\x04\x03\x02\x07\x12\x03a\x027\x1a!\x20optiona\
    l\x20for\x20bluetooth\x20chipsets\n\n\x0c\n\x05\x04\x03\x02\x07\x06\x12\
    \x03a\x02$\n\x0c\n\x05\x04\x03\x02\x07\x01\x12\x03a%2\n\x0c\n\x05\x04\
    \x03\x02\x07\x03\x12\x03a56\nS\n\x04\x04\x03\x02\x08\x12\x03d\x02\x15\
    \x1aF\x20address\x20in\x20format\x20xx:xx:xx:xx:xx:xx\n\x20optional\x20f\
    or\x20bluetooth\x20chipsets\n\n\x0c\n\x05\x04\x03\x02\x08\x05\x12\x03d\
    \x02\x08\n\x0c\n\x05\x04\x03\x02\x08\x01\x12\x03d\t\x10\n\x0c\n\x05\x04\
    \x03\x02\x08\x03\x12\x03d\x13\x14\n@\n\x04\x04\x03\x02\t\x12\x03f\x02&\
    \x1a3\x20Offset\x20of\x20the\x20chip\x20position\x20from\x20center\x20of\
    \x20device\n\n\x0c\n\x05\x04\x03\x02\t\x04\x12\x03f\x02\n\n\x0c\n\x05\
    \x04\x03\x02\t\x06\x12\x03f\x0b\x19\n\x0c\n\x05\x04\x03\x02\t\x01\x12\
    \x03f\x1a\x20\n\x0c\n\x05\x04\x03\x02\t\x03\x12\x03f#%\nX\n\x04\x04\x03\
    \x02\n\x12\x03h\x02\x16\x1aK\x20Sim\x20type\x20for\x20modem\x20simulator\
    \x20(1\x20for\x20normal,\x202\x20for\x20CtsCarrierApiTestCases)\n\n\x0c\
    \n\x05\x04\x03\x02\n\x05\x12\x03h\x02\x07\n\x0c\n\x05\x04\x03\x02\n\x01\
    \x12\x03h\x08\x10\n\x0c\n\x05\x04\x03\x02\n\x03\x12\x03h\x13\x15b\x06pro\
    to3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::common::file_descriptor().clone());
            deps.push(super::model::file_descriptor().clone());
            deps.push(super::configuration::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(StartupInfo::generated_message_descriptor_data());
            messages.push(ChipInfo::generated_message_descriptor_data());
            messages.push(DeviceInfo::generated_message_descriptor_data());
            messages.push(Chip::generated_message_descriptor_data());
            messages.push(startup_info::Device::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
