[package]
name = "uwb"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
futures = "0.3"
log = "0.4"
device-api = { path = "../device-api" }
netsim-model = { path = "../model" }
client = { path = "../client" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
async-trait = "0.1"
