# Copyright 2025 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""grpcio-sys bazel build rule"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "grpc_wrap_deps",
    deps = [
        "@grpc//:grpc++",
    ],
    srcs = ["grpc_wrap.cc"],
)

rust_library(
    name = "grpcio-sys",
    srcs = glob(["**/*.rs"]),
    crate_name = "grpcio_sys",
    edition = "2018",
    crate_root = "src/lib.rs",
    rustc_env = {
        "BINDING_PATH": "../bindings/bindings.rs",
    },
    deps = [
        ":grpc_wrap_deps",
        "@libc",
        "@libz-sys",
    ],
    rustc_flags = [
        "--cfg=feature=\"_libz-sys\"",
        "--cfg=feature=\"_secure\"",
        "--cfg=feature=\"boringssl\"",
        "--cfg=feature=\"boringssl-src\"",
        "--cfg=feature=\"libz-sys\"",
    ],
)
