# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

exports_files(["rustfmt_stable.toml"])

filegroup(
    name = "features",
    srcs = glob(["reqs/bdd/**/*.feature"]),
    visibility = ["//visibility:public"],
)
