# Copyright 2022 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "3"
members = [
  "actor-framework",
  "ap-actor",
  "slirp-actor",
  "capture-actor",
  "capture-api",
  "bluetooth-actor",
  "model",
  "cell-actor",
  "nfc-actor",
  "daemon",
  "hci-server",
  "packets",
  "packet-stream",
  "link-actor",
  "link-api",
  "modem-rs",
  "modem-rs-derive",
  "uwb-actor",
  "types",
  "device-actor",
  "device-api",

  "rootcanal",
  "rootcanal-server",
  "testing",
  "cli",
]

[workspace.doc]
default-members = ["daemon"]
