# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

# Derived from Android Format Style
#
# Any changes here _must not_ conflict with the upstream in
# build/soong/scripts/rustfmt.toml

edition = "2021"
use_small_heuristics = "Max"
newline_style = "Unix"

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comment formatting
wrap_comments = true
format_code_in_doc_comments = true
