// Copyright 2026 The Android Open Source Project

//! # Cuke Engine
//!
//! This module provides the runtime support for executing Cuke-like tests in
//! Rust. It defines the `Cuke` struct, which holds registered steps, and the
//! logic to match regex patterns against test input.
//!
//! ## Usage
//!
//! Steps are registered via `cuke_codegen` generated glue codes.
//! The `Cuke::run` method is used to execute lines of Gherkin text.

use std::{future::Future, path::Path, pin::Pin};

use gherkin::Feature;
use regex::Regex;
use serde::{de::DeserializeOwned, Serialize};
use serde_json;

pub type DataTable = Vec<Vec<String>>;

pub struct StepContext {
    pub table: Option<DataTable>,
}

impl Default for StepContext {
    fn default() -> Self {
        Self { table: None }
    }
}

/// A trait for async steps that can be executed by the Cuke engine.
///
/// This trait is automatically implemented for any function that matches the
/// signature: `fn(&mut W, Vec<String>, StepContext) -> Pin<Box<dyn
/// Future<Output = ()> + Send>>`.
///
/// The `cuke_codegen` macro generates wrapper functions that implement this
/// signature, handling argument parsing and calling the actual step definition.
pub trait AsyncStep<W>: Send + Sync {
    fn call<'a>(
        &'a self,
        world: &'a mut W,
        args: Vec<String>,
        ctx: StepContext,
    ) -> Pin<Box<dyn Future<Output = ()> + Send + 'a>>;
}

impl<W, F> AsyncStep<W> for F
where
    F: for<'a> Fn(
            &'a mut W,
            Vec<String>,
            StepContext,
        ) -> Pin<Box<dyn Future<Output = ()> + Send + 'a>>
        + Send
        + Sync,
{
    fn call<'a>(
        &'a self,
        world: &'a mut W,
        args: Vec<String>,
        ctx: StepContext,
    ) -> Pin<Box<dyn Future<Output = ()> + Send + 'a>> {
        self(world, args, ctx)
    }
}

/// The Cuke engine responsible for managing and executing Gherkin steps.
///
/// It holds a registry of regex patterns mapped to `AsyncStep` implementations.
/// Steps are typically registered via code generated by `cuke_codegen`.
///
/// Type parameter `W` matches the "World" struct used to maintain state across
/// steps.
pub struct Cuke<W> {
    steps: Vec<(Regex, Box<dyn AsyncStep<W>>)>,
    before_hooks: Vec<Box<dyn AsyncStep<W>>>,
    after_hooks: Vec<Box<dyn AsyncStep<W>>>,
    tag_filter: Option<String>,
}

impl<W> Cuke<W> {
    pub fn new() -> Self {
        Self {
            steps: Vec::new(),
            before_hooks: Vec::new(),
            after_hooks: Vec::new(),
            tag_filter: None,
        }
    }

    /// Sets a tag filter. Only scenarios with this tag (or belonging to a
    /// feature with this tag) will be executed.
    pub fn filter(&mut self, tag: &str) {
        self.tag_filter = Some(tag.to_string());
    }

    /// Registers a step with a regex pattern.
    ///
    /// This method is primarily used by the generated code from `cuke_codegen`.
    pub fn register<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        let regex = Regex::new(pattern).expect("Invalid regex");
        self.steps.push((regex, Box::new(step)));
    }

    pub fn before<S>(&mut self, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.before_hooks.push(Box::new(step));
    }

    pub fn after<S>(&mut self, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.after_hooks.push(Box::new(step));
    }

    // Semantic aliases for Gherkin keywords
    pub fn given<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn when<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn then<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub fn and<S>(&mut self, pattern: &str, step: S)
    where
        S: AsyncStep<W> + 'static,
    {
        self.register(pattern, step);
    }

    pub async fn run(&self, text: &str, world: &mut W) {
        self.run_with_context(text, world, StepContext::default()).await;
    }

    pub async fn run_with_context(&self, text: &str, world: &mut W, ctx: StepContext) {
        for (regex, step) in &self.steps {
            if let Some(captures) = regex.captures(text) {
                // Skip the full match (index 0)
                let args: Vec<String> = captures
                    .iter()
                    .skip(1)
                    .map(|m| m.map_or("", |m| m.as_str()).to_string())
                    .collect();
                step.call(world, args, ctx).await;
                return;
            }
        }
        panic!("No step definition found for: {}", text);
    }

    async fn run_hooks(&self, hooks: &[Box<dyn AsyncStep<W>>], world: &mut W) {
        for hook in hooks {
            hook.call(world, vec![], StepContext::default()).await;
        }
    }

    /// Executes a Gherkin feature from a string.
    pub async fn execute_from_memory(&self, content: &str, world: &mut W) {
        let feature = Feature::parse(content, Default::default()).expect("Failed to parse feature");

        for scenario in &feature.scenarios {
            if !self.should_run(&feature.tags, &scenario.tags) {
                continue;
            }

            if scenario.examples.is_empty() {
                self.run_scenario(&feature, &scenario, world).await;
            } else {
                self.run_scenario_outline(&feature, &scenario, world).await;
            }
        }
    }

    fn should_run(&self, feature_tags: &[String], scenario_tags: &[String]) -> bool {
        if let Some(filter) = &self.tag_filter {
            let filter_str = filter.as_str();
            let filter_name = filter_str.strip_prefix("@").unwrap_or(filter_str);

            let match_found = feature_tags.iter().any(|t| t == filter_str || t == filter_name)
                || scenario_tags.iter().any(|t| t == filter_str || t == filter_name);

            return match_found;
        }
        true
    }

    async fn run_scenario(&self, feature: &Feature, scenario: &gherkin::Scenario, world: &mut W) {
        self.run_hooks(&self.before_hooks, world).await;
        self.run_background(&feature.background, world).await;
        log::info!("Scenario: {}", scenario.name);
        self.run_steps(&scenario.steps, world, &[]).await;
        self.run_hooks(&self.after_hooks, world).await;
    }

    async fn run_scenario_outline(
        &self,
        feature: &Feature,
        scenario: &gherkin::Scenario,
        world: &mut W,
    ) {
        for example in &scenario.examples {
            if let Some(table) = &example.table {
                if table.rows.is_empty() {
                    continue;
                }
                // Assume first row is header
                let header_row = &table.rows[0];
                let headers: Vec<String> = header_row.iter().map(|s| format!("<{}>", s)).collect();

                for row in table.rows.iter().skip(1) {
                    self.run_hooks(&self.before_hooks, world).await;
                    self.run_background(&feature.background, world).await;
                    log::info!("Scenario Outline: {}", scenario.name);

                    let replacements: Vec<(&str, &str)> = headers
                        .iter()
                        .zip(row.iter())
                        .map(|(h, v)| (h.as_str(), v.as_str()))
                        .collect();

                    self.run_steps(&scenario.steps, world, &replacements).await;
                    self.run_hooks(&self.after_hooks, world).await;
                }
            }
        }
    }

    async fn run_steps(
        &self,
        steps: &[gherkin::Step],
        world: &mut W,
        replacements: &[(&str, &str)],
    ) {
        for step in steps {
            let mut value = step.value.clone();
            for (key, val) in replacements {
                value = value.replace(*key, val);
            }

            let table = step.table.clone().map(|t| t.rows.iter().map(|row| row.to_vec()).collect());

            log::info!("  {}{}", step.keyword, value);
            self.run_with_context(&value, world, StepContext { table }).await;
        }
    }

    async fn run_background(&self, bg: &Option<gherkin::Background>, world: &mut W) {
        if let Some(ref bg) = bg {
            let sep = if bg.name.is_empty() { "" } else { " " };
            log::info!("Background:{}{}", sep, bg.name);
            for step in &bg.steps {
                log::info!("  {}{}", step.keyword, step.value);
                self.run(&step.value, world).await;
            }
        }
    }

    /// Executes a Gherkin feature from a file.
    pub async fn execute<P: AsRef<Path>>(&self, path: P, world: &mut W) {
        let content = std::fs::read_to_string(path).expect("Failed to read feature file");
        self.execute_from_memory(&content, world).await;
    }
}

/// Helper trait for parsing a single row of a DataTable into a struct.
pub trait FromDataRow: Sized {
    type Error;
    fn from_row(row: &[String]) -> Result<Self, Self::Error>;
}

/// Helper to convert a vertically oriented DataTable (Key | Value) into a
/// HashMap. Assumes rows are [Key, Value].
pub fn vertical_table_to_map(table: &DataTable) -> std::collections::HashMap<String, String> {
    let mut map = std::collections::HashMap::new();
    for row in table {
        if row.len() >= 2 {
            map.insert(row[0].clone(), row[1].clone());
        }
    }
    map
}

/// Helper to convert a vertically oriented DataTable into a Struct via JSON.
///
/// This function:
/// 1. Converts the DataTable to a Map<String, String>.
/// 2. Serializes the Map to a serde_json::Value.
/// 3. Deserializes the Value into the target type T.
pub fn table_to_struct<T: DeserializeOwned>(table: &DataTable) -> Result<T, serde_json::Error> {
    let map = vertical_table_to_map(table);
    let json_value = serde_json::to_value(map)?;
    serde_json::from_value(json_value)
}

/// Helper to assert that a struct's JSON representation matches the expected
/// fields in a DataTable.
///
/// This function:
/// 1. Converts the actual struct to a serde_json::Value.
/// 2. Iterates over the key-value pairs in the DataTable.
/// 3. Asserts that each key exists in the JSON and matches the value.
///
/// Panics if a field is missing or mismatching.
pub fn assert_json_matches_table<S: Serialize>(actual: &S, table: &DataTable) {
    let expected_fields = vertical_table_to_map(table);
    let actual_json = serde_json::to_value(actual).expect("Failed to serialize actual value");

    for (key, expected_val) in expected_fields {
        match actual_json.get(&key) {
            Some(val) => {
                // Allow loose comparison for numbers/bools by converting to string
                let actual_str = match val {
                    serde_json::Value::String(s) => s.clone(),
                    _ => val.to_string(),
                };
                assert_eq!(
                    actual_str, *expected_val,
                    "Mismatch for field '{}': expected '{}', got '{}' (from JSON: {:?})",
                    key, expected_val, actual_str, val
                );
            }
            None => {
                panic!(
                    "Field '{}' not found in actual JSON. Available fields: {:?}",
                    key,
                    actual_json.as_object().map(|o| o.keys().collect::<Vec<_>>())
                );
            }
        }
    }
}
