# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "runner",
    testonly = True,
    srcs = ["src/main.rs"],
    edition = "2021",
    deps = [
        "//next/verify/host:verify_host_lib",
        "@clap",
        "@tokio",
        "@tracing",
        "@tracing-subscriber",
    ],
)

sh_test(
    name = "runner-e2e",
    srcs = ["runner-e2e.sh"],
    args = [
        "$(location :runner)",
        "$(location //next/verify/instrumentation/vbs:vbs.apk)",
        "$(location @netsim//:netsimd)",
        "$(location //next/cli:netsim)",
        "--spec-dir",
        "../netsim+/next/tests/features",
    ],
    data = [
        ":runner",
        "//next:features",
        "//next/cli:netsim",
        "//next/verify/instrumentation/vbs:vbs.apk",
        "@netsim//:netsimd",
    ],
    tags = ["manual"],
)
