// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

// Generated by scripts/parse_xml.py. Do not edit manually.
#![allow(dead_code)]

#[derive(Debug, Clone)]
pub struct SimIoMapping {
    pub cmd: &'static str,
    pub p1: &'static str,
    pub p2: &'static str,
    pub p3: &'static str,
    pub data: &'static str,
    pub response: &'static str,
}

#[derive(Debug, Clone)]
pub struct FileMapping {
    pub file_id: &'static str,
    pub mappings: &'static [SimIoMapping],
}

#[derive(Debug, Clone)]
pub struct CglaMapping {
    pub cmd: &'static str,
    pub response: &'static str,
}

#[derive(Debug, Clone)]
pub struct AdfFileMock {
    pub id: &'static str,
    pub cgla: &'static [CglaMapping],
}

#[derive(Debug, Clone)]
pub struct AdfMock {
    pub aid: &'static str,
    pub cgla: &'static [CglaMapping],
    pub csim: &'static [CglaMapping],
    pub files: &'static [AdfFileMock],
}

#[derive(Debug, Clone)]
pub struct Profile {
    pub simio_files: &'static [FileMapping],
    pub adfs: &'static [AdfMock],
}

const PROFILE_DEFAULT_SIMIO: &[FileMapping] = &[
    FileMapping {
        file_id: "2F00",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A8205422100300483022F008A01058B032F0601800200C08801F0",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,61184F10A0000003431002FF86FF0389FFFFFFFF50044353494DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,61184F10A0000000871002FF86FF0389FFFFFFFF50045553494DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "2F05",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183022F058A01058B032F060280020004880128",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "4",
                data: "",
                response: "144,0,FFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "2FE2",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183022FE28A01058B032F06038002000A880110",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "A",
                data: "",
                response: "144,0,98683081462002318379",
            },
        ],
    },
    FileMapping {
        file_id: "4F09",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A820542210002FA83024F098A01058B036F060E800201F4880110",
        }],
    },
    FileMapping {
        file_id: "4F11",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A82054221000FFA83024F118A01058B036F060E80020EA6880120",
        }],
    },
    FileMapping {
        file_id: "4F30",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62198205422100400283024F308A01058B036F0606800200808800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "40",
                data: "",
                response: "144,0,A81EC0034F3A01C1034F3306C5034F0902C4034F1104C6034F2503C9034F3107A905CA034F5008AA0FC2034F4A09C7034F4B0AC8034F4C0BFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "40",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "4F33",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A820542210001FA83024F338A01058B036F060E800200FA880130",
        }],
    },
    FileMapping {
        file_id: "4F3A",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A82054221001C1483024F3A8A01058B036F060E80020230880108",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "B",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "C",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "D",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "E",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "F",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "10",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "11",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "12",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "13",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "14",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "4F4C",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A8205422100140A83024F4C8A01058B036F060E800200C8880158",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F11",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "106,130",
        }],
    },
    FileMapping {
        file_id: "6F3B",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621982054221001C0A83026F3B8A01058B036F0605800201188800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F40",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621982054221001C0283026F408A01058B036F0605800200388800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,000000000000000000000000000007915155214365F7FFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F7B",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621C8202412183026F7BA5038001718A01058B036F06038002001E880168",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "1E",
                data: "",
                response: "144,0,64F00064F02064F04064F07064F080FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6FAD",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183026FAD8A01058B036F060180020004880118",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "4",
                data: "",
                response: "144,0,00000003",
            },
        ],
    },
    FileMapping {
        file_id: "6FC7",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621982054221001C0283026F408A01058B036F06058002003E8800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF07915155674523F1FFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6FC9",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62198205422100050183026FC98A01058B036F0602800200058800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "5",
                data: "",
                response: "144,0,0100000000",
            },
        ],
    },
    FileMapping {
        file_id: "6FCA",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62198205422100050183026FCA8A01058B036F060E800200058800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "5",
                data: "",
                response: "144,0,0000000000",
            },
        ],
    },
];

const PROFILE_DEFAULT_ADF_EMPTY_CGLA: &[CglaMapping] =
    &[CglaMapping { cmd: "81F2FF0000", response: "4,6b00" }];

const PROFILE_DEFAULT_ADF_EMPTY_CSIM: &[CglaMapping] =
    &[CglaMapping { cmd: "10,\"0070000001\"", response: "6,019000" }];

const PROFILE_DEFAULT_ADF_EMPTY_FILES: &[AdfFileMock] = &[];

const PROFILE_DEFAULT_ADF_A000000063504B43532D3135_CGLA: &[CglaMapping] = &[
    CglaMapping { cmd: "00A40004025031", response: "4,6124" },
    CglaMapping { cmd: "00B0000010", response: "36,A706300404024401A5063004040244029000" },
    CglaMapping {
        cmd: "00C0000024",
        response: "76,62228202412183025031A503C001408A01058B066F0601010001800200108102002288009000",
    },
];

const PROFILE_DEFAULT_ADF_A000000063504B43532D3135_CSIM: &[CglaMapping] = &[];

const PROFILE_DEFAULT_ADF_A000000063504B43532D3135_FILES: &[AdfFileMock] = &[];

const PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_CGLA: &[CglaMapping] = &[];

const PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_CSIM: &[CglaMapping] = &[];

const PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_FILES: &[AdfFileMock] = &[];

const PROFILE_DEFAULT_ADFS: &[AdfMock] = &[
    AdfMock {
        aid: "",
        cgla: PROFILE_DEFAULT_ADF_EMPTY_CGLA,
        csim: PROFILE_DEFAULT_ADF_EMPTY_CSIM,
        files: PROFILE_DEFAULT_ADF_EMPTY_FILES,
    },
    AdfMock {
        aid: "A000000063504B43532D3135",
        cgla: PROFILE_DEFAULT_ADF_A000000063504B43532D3135_CGLA,
        csim: PROFILE_DEFAULT_ADF_A000000063504B43532D3135_CSIM,
        files: PROFILE_DEFAULT_ADF_A000000063504B43532D3135_FILES,
    },
    AdfMock {
        aid: "A0000000871002FF86FF0389FFFFFFFF",
        cgla: PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_CGLA,
        csim: PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_CSIM,
        files: PROFILE_DEFAULT_ADF_A0000000871002FF86FF0389FFFFFFFF_FILES,
    },
];

pub static PROFILE_DEFAULT: Profile =
    Profile { simio_files: PROFILE_DEFAULT_SIMIO, adfs: PROFILE_DEFAULT_ADFS };

const PROFILE_CTS_SIMIO: &[FileMapping] = &[
    FileMapping {
        file_id: "2F00",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A8205422100300483022F008A01058B032F0601800200C08801F0",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,61184F10A0000003431002FF86FF0389FFFFFFFF50044353494DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,61184F10A0000000871002FF86FF0389FFFFFFFF50045553494DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "30",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "2F05",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183022F058A01058B032F060280020004880128",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "4",
                data: "",
                response: "144,0,FFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "2FE2",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183022FE28A01058B032F06038002000A880110",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "A",
                data: "",
                response: "144,0,98683081462002318379",
            },
        ],
    },
    FileMapping {
        file_id: "4F09",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A820542210002FA83024F098A01058B036F060E800201F4880110",
        }],
    },
    FileMapping {
        file_id: "4F11",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A82054221000FFA83024F118A01058B036F060E80020EA6880120",
        }],
    },
    FileMapping {
        file_id: "4F30",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62198205422100400283024F308A01058B036F0606800200808800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "40",
                data: "",
                response: "144,0,A81EC0034F3A01C1034F3306C5034F0902C4034F1104C6034F2503C9034F3107A905CA034F5008AA0FC2034F4A09C7034F4B0AC8034F4C0BFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "40",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "4F33",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "144,0,621A820542210001FA83024F338A01058B036F060E800200FA880130",
        }],
    },
    FileMapping {
        file_id: "4F3A",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A82054221001C1483024F3A8A01058B036F060E80020230880108",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "B",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "C",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "D",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "E",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "F",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "10",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "11",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "12",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "13",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "14",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "4F4C",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621A8205422100140A83024F4C8A01058B036F060E800200C8880158",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "E",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F11",
        mappings: &[SimIoMapping {
            cmd: "C0",
            p1: "0",
            p2: "0",
            p3: "F",
            data: "",
            response: "106,130",
        }],
    },
    FileMapping {
        file_id: "6F3B",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621982054221001C0A83026F3B8A01058B036F0605800201188800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "2",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "3",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "4",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "5",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "6",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "7",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "8",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "9",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "A",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F40",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621982054221001C0283026F408A01058B036F0605800200388800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "1C",
                data: "",
                response: "144,0,00000000000000000000000000000891688118109844F0FFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6F7B",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,621C8202412183026F7BA5038001718A01058B036F06038002001E880168",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "1E",
                data: "",
                response: "144,0,64F00064F02064F04064F07064F080FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            },
        ],
    },
    FileMapping {
        file_id: "6FAD",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62178202412183026FAD8A01058B036F060180020004880118",
            },
            SimIoMapping {
                cmd: "B0",
                p1: "0",
                p2: "0",
                p3: "4",
                data: "",
                response: "144,0,00000002",
            },
        ],
    },
    FileMapping {
        file_id: "6FC7",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62258205422100260483026FC7A503C001408A01058B066F060103000080020098810200AC8800",
            },
            SimIoMapping {
                cmd: "DC",
                p1: "1",
                p2: "4",
                p3: "26",
                data: "74616741FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF06812143658709FFFFFFFFFFFFFF",
                response: "144,0",
            },
            SimIoMapping {
                cmd: "DC",
                p1: "1",
                p2: "4",
                p3: "26",
                data: "74616742FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF06819078563412FFFFFFFFFFFFFF",
                response: "144,0",
            },
            SimIoMapping {
                cmd: "DC",
                p1: "1",
                p2: "4",
                p3: "26",
                data: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
                response: "144,0",
            },
        ],
    },
    FileMapping {
        file_id: "6FC9",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62258205422100040183026FC9A503C001408A01058B066F060103000080020004810200188800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "4",
                data: "",
                response: "144,0,01000000",
            },
        ],
    },
    FileMapping {
        file_id: "6FCA",
        mappings: &[
            SimIoMapping {
                cmd: "C0",
                p1: "0",
                p2: "0",
                p3: "F",
                data: "",
                response: "144,0,62198205422100050183026FCA8A01058B036F060E800200058800",
            },
            SimIoMapping {
                cmd: "B2",
                p1: "1",
                p2: "4",
                p3: "5",
                data: "",
                response: "144,0,0000000000",
            },
        ],
    },
];

const PROFILE_CTS_ADF_EMPTY_CGLA: &[CglaMapping] =
    &[CglaMapping { cmd: "1,14,\"81F2FF0000\"", response: "4,6b00" }];

const PROFILE_CTS_ADF_EMPTY_CSIM: &[CglaMapping] =
    &[CglaMapping { cmd: "10,\"0070000001\"", response: "6,019000" }];

const PROFILE_CTS_ADF_EMPTY_FILES: &[AdfFileMock] = &[];

const PROFILE_CTS_ADF_A000000063504B43532D3135_CGLA: &[CglaMapping] = &[];

const PROFILE_CTS_ADF_A000000063504B43532D3135_CSIM: &[CglaMapping] = &[];

const PROFILE_CTS_ADF_A000000063504B43532D3135_FILE_4300_CGLA: &[CglaMapping] = &[
    CglaMapping {
        cmd: "00A40004024300",
        response: "76,62228202412183024300A503C001408A01058B066F0601010001800201DC810201EE88009000",
    },
    CglaMapping {
        cmd: "00B0000000",
        response: "516,30088200300404024310301AA0120410A000000476416E64726F696443545340300404024311301AA0120410A000000476416E64726F696443545341300404024312301AA0120410A000000476416E64726F696443545342300404024313301AA0120410A000000476416E64726F696443545343300404024314301AA0120410A000000476416E64726F696443545344300404024315301AA0120410A000000476416E64726F696443545345300404024316301AA0120410A000000476416E64726F6964435453463004040243173010A0080406FFFFFFFFFFFF300404024318301AA0120410A000000476416E64726F696443545347300404024313301AA0129000",
    },
];

const PROFILE_CTS_ADF_A000000063504B43532D3135_FILE_4318_CGLA: &[CglaMapping] = &[
    CglaMapping {
        cmd: "00A40004024318",
        response: "76,62228202412183024318A503C001408A01058B066F0601010001800200188102002A88009000",
    },
    CglaMapping {
        cmd: "00B0000000",
        response: "124,3016041461ED377E85D386A8DFEE6B864BD85B0BFAA5AF8130220420CE7B2B47AE2B7552C8F92CC29124279883041FB623A5F194A82C9BF15D492AA09000",
    },
];

const PROFILE_CTS_ADF_A000000063504B43532D3135_FILES: &[AdfFileMock] = &[
    AdfFileMock { id: "4300", cgla: PROFILE_CTS_ADF_A000000063504B43532D3135_FILE_4300_CGLA },
    AdfFileMock { id: "4318", cgla: PROFILE_CTS_ADF_A000000063504B43532D3135_FILE_4318_CGLA },
];

const PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_CGLA: &[CglaMapping] = &[];

const PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_CSIM: &[CglaMapping] = &[];

const PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_FILES: &[AdfFileMock] = &[];

const PROFILE_CTS_ADF_CSIM_CGLA: &[CglaMapping] = &[
    CglaMapping { cmd: "00A40000023F00", response: "4,6B00" },
    CglaMapping {
        cmd: "00A40004022F06",
        response: "78,622382054221004A1283022F06A503C001408A01058B062F060101000080020534810205489000",
    },
    CglaMapping { cmd: "00A4000C022FE2", response: "4,9000" },
    CglaMapping { cmd: "00A4000C023F00", response: "4,9000" },
    CglaMapping { cmd: "00A4000C02FFFF", response: "4,6A82" },
    CglaMapping { cmd: "00B0000000", response: "24,983311111111111111029000" },
    CglaMapping { cmd: "00FF000000", response: "4,6D00" },
    CglaMapping { cmd: "0170830100", response: "4,6A81" },
    CglaMapping { cmd: "81F2FF0000", response: "4,6B00" },
    CglaMapping { cmd: "FFF2000000", response: "4,6E00" },
];

const PROFILE_CTS_ADF_CSIM_CSIM: &[CglaMapping] = &[
    CglaMapping { cmd: "0070000000", response: "6,019000" },
    CglaMapping { cmd: "0070000001", response: "6,019000" },
    CglaMapping { cmd: "0070800100", response: "4,9000" },
    CglaMapping { cmd: "80F20000", response: "4,6C35" },
    CglaMapping {
        cmd: "80F2000000",
        response: "110,62338202782183023F00A50C80016187010183040007DBF08A01058B062F0601020002C60C90016083010183010A83010D8102FFFF9000",
    },
];

const PROFILE_CTS_ADF_CSIM_FILES: &[AdfFileMock] = &[];

const PROFILE_CTS_ADFS: &[AdfMock] = &[
    AdfMock {
        aid: "",
        cgla: PROFILE_CTS_ADF_EMPTY_CGLA,
        csim: PROFILE_CTS_ADF_EMPTY_CSIM,
        files: PROFILE_CTS_ADF_EMPTY_FILES,
    },
    AdfMock {
        aid: "A000000063504B43532D3135",
        cgla: PROFILE_CTS_ADF_A000000063504B43532D3135_CGLA,
        csim: PROFILE_CTS_ADF_A000000063504B43532D3135_CSIM,
        files: PROFILE_CTS_ADF_A000000063504B43532D3135_FILES,
    },
    AdfMock {
        aid: "A0000000871002FF86FF0389FFFFFFFF",
        cgla: PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_CGLA,
        csim: PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_CSIM,
        files: PROFILE_CTS_ADF_A0000000871002FF86FF0389FFFFFFFF_FILES,
    },
    AdfMock {
        aid: "CSIM",
        cgla: PROFILE_CTS_ADF_CSIM_CGLA,
        csim: PROFILE_CTS_ADF_CSIM_CSIM,
        files: PROFILE_CTS_ADF_CSIM_FILES,
    },
];

pub static PROFILE_CTS: Profile =
    Profile { simio_files: PROFILE_CTS_SIMIO, adfs: PROFILE_CTS_ADFS };
