# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "capture-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.73"
bytes = "1.5.0"
futures = "0.3"
netsim-model = { path = "../model" }
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["sync"] }
