# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

# This file maps Mobile Network Codes (MNC) and Mobile Country Codes (MCC)
# to human-readable operator names.

[operators]
"311740" = { long_name = "TelAlaska", short_name = "TelAlaska" }
"310260" = { long_name = "T-Mobile", short_name = "TMOBILE" }
"46000" = { long_name = "China Mobile", short_name = "CMCC" }
"46001" = { long_name = "China UNICOM", short_name = "UNICOM" }
"46002" = { long_name = "China Mobile", short_name = "CMCC" }
"46003" = { long_name = "China Telecom", short_name = "CT" }
"46004" = { long_name = "China Mobile", short_name = "CMCC" }
"46005" = { long_name = "China Telecom", short_name = "CT" }
"46006" = { long_name = "China UNICOM", short_name = "UNICOM" }
"46007" = { long_name = "China Mobile", short_name = "CMCC" }
"46008" = { long_name = "China Mobile", short_name = "CMCC" }
"46009" = { long_name = "China UNICOM", short_name = "UNICOM" }
"46011" = { long_name = "China Telecom", short_name = "CT" }
