[package]
name = "netsim-api"
version = "0.1.0"
edition = "2021"
authors = ["The Android Open Source Project"]

[dependencies]
tokio = { version = "1.32.0", default-features = false, features = ["rt", "time", "sync", "macros"] }
async-trait = "0.1.73"
thiserror = "1.0"
tracing = "0.1.40"
tracing-attributes = "0.1.27"
bytes = "1.10.1"
futures = "0.3.31"
tokio-stream = "0.1.17"
