# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "grpc-server"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1.0"
device-actor = { path = "../device-actor" }
device-api = { path = "../device-api" }
futures = "0.3"
grpcio = { version = "0.13", default-features = false, features = [
  "protobufv3-codec",
  "openssl",
] }
link-actor = { path = "../link-actor" }
link-api = { path = "../link-api" }

actor-framework = { path = "../actor-framework" }
netsim-model = { path = "../model" }
packet-stream = { path = "../packet-stream" }
protobuf = "3"
tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-stream = "0.1"
tracing = "0.1"
