[package]
name = "capture-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
actor-framework = { path = "../actor-framework" }
anyhow = "1.0"
async-trait = "0.1"
byteorder = "1.4"
bytes = "1.5"
capture-api = { path = "../capture-api" }
common = { package = "netsim-common", path = "../common" }
futures = "0.3"
log = "0.4"
netsim-model = { path = "../model" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
zerocopy = { version = "0.8", features = ["derive"] }
