# Copyright 2024 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libslirp-rs"
version = "0.1.0"
edition = "2024"
##build = "build_cargo.rs"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
doctest = false

[dependencies]
bytes = { version = "1.4.0" }
libc = "0.2"
slirp = { path = "../slirp" }
tokio = { version = "1.32.0", features = ["net", "rt-multi-thread", "sync"] }
tracing = "0.1"
windows-sys = { version = "0.59.0", features = ["Win32_Networking_WinSock"] }

[build-dependencies]
##bindgen = "0.69.4"
