// Copyright 2025 The Android Open Source Project

use std::ffi::c_int;

use bytes::Bytes;
use futures::SinkExt;
use netsim_model::ChipId;
use rootcanal::{
    controller::{Callbacks as ControllerCallbacks, Id},
    types::Phy,
};
use tokio::sync::mpsc;
use tracing::{debug, error};

/// Callbacks for handling HCI and Link Layer packets from Rootcanal.
pub struct HciCallbacks {
    /// The ID of the chip associated with these callbacks.
    pub id: ChipId,
    /// Channel to send HCI packets to the sink task.
    pub hci_tx: Option<mpsc::Sender<Bytes>>,
    /// Channel to send LL packets (not currently used in this path, usually for
    /// sniffer/link bridging).
    pub ll_tx: Option<mpsc::Sender<Bytes>>,
}

impl ControllerCallbacks for HciCallbacks {
    fn send_hci(&self, _source_id: Id, h4_packet: Bytes) {
        if let Some(hci_tx) = self.hci_tx.as_ref() {
            debug!("send_hci: Sending packet len={}", h4_packet.len());
            if let Err(e) = hci_tx.try_send(h4_packet) {
                error!("Failed to send HCI packet: {e}, dropping.");
            }
        }
    }

    fn on_receive_ll(&self, _source_id: Id, packet: &[u8], _phy: Phy, _tx_power: i32) {
        debug!("[{}] Received LL packet", self.id);
        if let Some(ll_tx) = self.ll_tx.as_ref() {
            let packet = Bytes::copy_from_slice(packet);
            if let Err(e) = ll_tx.try_send(packet) {
                error!("Failed to send LL packet: {e}, dropping.");
            }
        }
    }

    fn invalid_packet_received(&self, _source_id: Id, reason: c_int, message: &str, _data: &[u8]) {
        error!(
            "[chip-{}] Invalid packet received by device: reason={reason}, message={message}",
            self.id
        );
    }
}

/// Runs the task that forwards HCI packets from the callbacks to the packet
/// sink. This task runs in the background and ensures that packets generated by
/// `rootcanal` (via `send_hci`) are sent to the `PacketSink` associated with
/// the chip.
pub async fn sink_loop(
    mut sink: netsim_model::chip::PacketSink,
    mut receiver: tokio::sync::mpsc::Receiver<bytes::Bytes>,
    id: ChipId,
) -> ChipId {
    debug!("sink_loop: Started for chip {}", id);
    while let Some(packet) = receiver.recv().await {
        debug!("sink_loop: Received packet len={}", packet.len());
        if sink.send(packet).await.is_err() {
            error!("Sink for chip {} failed", id);
            break;
        } else {
            debug!("sink_loop: Sent packet successfully");
        }
    }
    let _ = sink.close().await;
    error!("Sink task for chip {} finished", id);
    id
}

#[cfg(test)]
mod tests {
    use bytes::Bytes;
    use tokio::sync::{mpsc, mpsc::error::TryRecvError};

    use super::*;

    #[tokio::test]
    async fn test_send_hci_drops_when_channel_full() {
        // Create an extremely small channel with size 2.
        // This mimics the original issue where mpsc::channel(10) filled up rapidly
        // before tokio executors could awake `sink_loop` to drain the packets.
        let (hci_tx, mut hci_rx) = mpsc::channel(2);

        let callbacks = HciCallbacks { id: ChipId::from(1), hci_tx: Some(hci_tx), ll_tx: None };

        // Rootcanal produces packets synchronously and rapidly back-to-back:
        callbacks.send_hci(0, Bytes::from_static(b"req1")); // Success
        callbacks.send_hci(0, Bytes::from_static(b"req2")); // Success

        // The queue is now full. This third packet hits `.try_send()` limit and gets
        // dropped immediately, which reproduces the exact packet loss causing test
        // failure.
        callbacks.send_hci(0, Bytes::from_static(b"req3")); // Dropped!

        // Draining the queue reveals only the first two packets reached the sink
        let packet1 = hci_rx.recv().await.unwrap();
        assert_eq!(packet1, Bytes::from_static(b"req1"));

        let packet2 = hci_rx.recv().await.unwrap();
        assert_eq!(packet2, Bytes::from_static(b"req2"));

        // No third packet exists; the channel is empty.
        match hci_rx.try_recv() {
            Err(TryRecvError::Empty) => {}
            _ => panic!("Expected empty channel!"),
        }
    }
}
