// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

//! This module provides the functionality for creating and managing Bluetooth
//! sniffer chips.
//!
//! A sniffer simply receives all link-layer packets because Rootcanal's Rust
//! `broadcast_to_peers` calls `on_receive_ll` for all cloned controllers.
//! Thus, no specific HCI config is needed.

use netsim_model::{
    chip::{ChipId, SnifferParams},
    chip_error::ChipError,
};
use rootcanal::Rootcanal;
use tracing::debug;

/// Creates a new `SnifferChip`.
pub(crate) fn create(
    _rootcanal: &Rootcanal,
    chip_id: ChipId,
    _params: &SnifferParams,
) -> Result<(), ChipError> {
    debug!("[{chip_id}] Setting up sniffer chip");
    // Subscribes purely through ll_tx attached to HciCallbacks.
    // Automatically receives all LL packets generated by rootcanal peers.
    Ok(())
}
