# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "modem-rs-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
nom = "7"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
modem-rs = { path = "../modem-rs", features = ["test-utils"] }
nom = "7"
