# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ap-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"
netsim-packets = { path = "../packets" }
thiserror = "1.0"
tracing = "0.1"

actor-framework = { path = "../actor-framework" }
aes = "0.8.4"
async-trait = "0.1"
bytes = "1"
ccm = "0.5.0"
netsim-model = { path = "../model" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
zerocopy = "0.7"

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
netsim-testing = { path = "../testing", features = ["testing"] }
tokio-stream = "0.1"
