// Copyright 2026 The Android Open Source Project

syntax = "proto3";

package netsim.ble_service;

import "netsim/model.proto";

// Service to manage Bluetooth test capabilities in the simulation
service BleService {
  // Initiates a Bluetooth scan at a given position.
  // The scanner chip is automatically created internally, and is removed
  // automatically when the gRPC stream gets disconnected.
  rpc Scan(ScanRequest) returns (stream ScanResponse);
}

message ScanRequest {
  // Initial physical position of the scanner in the simulation.
  netsim.model.Position position = 1;

  // Optional parameters, such as HCI event masks or scan intervals,
  // can be added as fields here in the future.
}

message ScanResponse {
  // Raw HCI event packet
  bytes packet = 1;
}
