// Copyright 2026 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package netsim.cell;

import "google/protobuf/empty.proto";

service CellService {
  // Get an existing Cell.
  rpc Get(GetCellRequest) returns (Cell);

  // List all Cells.
  rpc List(ListCellsRequest) returns (ListCellsResponse);

  // Execute an action on a Cell.
  rpc Execute(ExecuteCellRequest) returns (google.protobuf.Empty);
}

message GetCellRequest {
  uint32 id = 1;
}

message ListCellsRequest {}

message ListCellsResponse {
  repeated Cell cells = 1;
}

message ExecuteCellRequest {
  uint32 id = 1;
  oneof action {
    IncomingCall incoming_call = 2;
    UpdateCall update_call = 3;
    EndCall end_call = 4;
    ReceiveSms receive_sms = 5;
    SetSignalStrength set_signal_strength = 6;
    SetVoiceRegistration set_voice_registration = 7;
    SetDataRegistration set_data_registration = 8;
    RemoteAnswer remote_answer = 9;
    RemoteHold remote_hold = 10;
  }
}

message IncomingCall {
  string number = 1;
}

message UpdateCall {
  // Placeholder for future updates
}

message EndCall {
  // RemoteHangup
}

message RemoteAnswer {}

message RemoteHold {
  bool on_hold = 1;
}

message ReceiveSms {
  string sender = 1;
  string text = 2;
}

message SetSignalStrength {
  uint32 rssi = 1;
  uint32 ber = 2;
}

message SetVoiceRegistration {
  RegistrationStatus status = 1;
}

message SetDataRegistration {
  RegistrationStatus status = 1;
}

// Mirroring netsim_model::cell::RegistrationStatus
enum RegistrationStatus {
  NOT_REGISTERED = 0;
  REGISTERED_HOME = 1;
  SEARCHING = 2;
  DENIED = 3;
  UNKNOWN = 4;
  ROAMING = 5;
}

message Cell {
  uint32 id = 1;
  string state = 2;  // "idle", "ringing", etc.
  bool ringing = 3;  // NOTE: Consider deriving ringing directly from state to
                     // reduce payload redundancy

  uint32 sms_count = 4;
  uint32 rssi = 5;
  uint32 ber = 6;
  repeated Call active_calls = 7;
}

message Call {
  string number = 1;
  enum State {
    UNKNOWN = 0;
    ACTIVE = 1;
    HOLDING = 2;
    DIALING = 3;
    ALERTING = 4;
    INCOMING = 5;
    WAITING = 6;
  }
  State state = 2;
}
