# Copyright 2024 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "netsim-packets"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
doctest = false

[dependencies]
anyhow = "1"
bytes = { version = ">=1.4.0" }
pdl-runtime = "0.4.2"
