# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "netsim-common"
version = "0.3.80"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]
doctest = false

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["now"] }
libc = "0.2.150"
protobuf-json-mapping = "3.2.0"
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
zip = { version = "0.6.4", default-features = false }

[dev-dependencies]
rand = "0.8.5"
regex = "1"
