#!/usr/bin/env bash

# Copyright 2022 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Update the Rust protobuf files on git_main-netsim-dev branch

# Prerequisites:
# - protobuf-compiler
# Linux: sudo apt-get install protobuf-compiler
# Mac:   brew install protobuf
# Fixing Cargo version: rustup default 1.85.0

# Check for protoc
if ! command -v protoc &> /dev/null
then
    echo "protobuf-compiler (protoc) not found. Please install it:"
    echo "Linux: sudo apt-get install protobuf-compiler"
    echo "Mac:   brew install protobuf"
    exit 1
fi

set -e # Exit immediately if a command exits with a non-zero status.

echo "Starting Rust protobuf file update process..."

# --- Configuration ---
# Absolute path to tools/netsim using this scripts directory
REPO_NETSIM=$(dirname "$0")/..
PROTO_SRC_DIR="$REPO_NETSIM/rust/proto-cf/src"
if [[ "$(uname)" != "Linux" ]]; then
    echo "Error: This script only supports Linux."
    exit 1
fi

cd "$REPO_NETSIM"

# --- Step 1. Generate protobuf files for proto-cf (protobuf 3.7.2) ---
echo "[Step 1] Generating protobuf files for proto-cf (protobuf 3.7.2)..."
# NOTE: These files are generated by cargo build because protoc-grpcio
# doesn't support protobuf v3 yet.
# They will be reverted and regenerated properly using the build script.
# https://github.com/mtp401/protoc-grpcio/issues/41

# Install compilers since the crates are not in AOSP
# TODO: Add required crate mappings to work in git_main-netsim-dev
export CARGO_HOME=""
export PATH="$HOME/.cargo/bin:$PATH"
if command -v rustup &> /dev/null; then
    rustup default 1.88.0
fi
cargo install protobuf-codegen --version 3.7.2
cargo install grpcio-compiler --version 0.13.0

PROTOC_PLUGIN_PATH=$(which grpc_rust_plugin)
if [ -z "$PROTOC_PLUGIN_PATH" ]; then
    echo "Error: grpc_rust_plugin not found in PATH after cargo install."
    exit 1
fi

PROTOC_CMD="protoc \
 --rust_community_out=$PROTO_SRC_DIR \
 --grpc_out=$PROTO_SRC_DIR \
 --plugin=protoc-gen-grpc=$PROTOC_PLUGIN_PATH \
 --plugin=protoc-gen-rust_community=$(which protoc-gen-rs) \
 -I./proto -I../../external/protobuf/src \
 -I../../tools/rootcanal/proto"

$PROTOC_CMD ../../tools/rootcanal/proto/rootcanal/configuration.proto \
            proto/netsim/*.proto


# --- Step 2. Post-processing Rust Files ---
echo "[Step 2] Post-processing generated Rust files..."

# Remove #![allow(box_pointers)] attribute from generated files.
# This has been removed with latest toolchain.
# TODO: Remove this step after Rust toolchain upgrade.
echo "Removing #![allow(box_pointers)] attribute..."
find "$PROTO_SRC_DIR" -name '*.rs' \
  -exec sed -i '/^#!\[allow(box_pointers)\]$/d' {} +

# Find the most recent rustfmt available in prebuilts for the detected OS
RUSTFMT="../../prebuilts/rust-toolchain/linux-x86/stable/rustfmt"
if [ ! -f "$RUSTFMT" ]; then
    RUSTFMT="rustfmt"
fi
find "$PROTO_SRC_DIR" -name '*.rs' -exec "$RUSTFMT" {} \;

# --- Step 3. Add license headers ---
echo "[Step 3] Adding license headers..."
find "$PROTO_SRC_DIR" -name '*.rs' -exec python3 scripts/format_licenses.py {} +




