# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "custom_host_runner",
    testonly = True,
    srcs = ["src/main.rs"],
    edition = "2024",
    proc_macro_deps = [
        "//next/verify/macros:verify_macros",
    ],
    deps = [
        "//next/verify/host:verify_host_lib",
        "//next/verify/lib",
        "@clap",
        "@tokio",
    ],
)
