# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rootcanal-server"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
device-actor = { path = "../device-actor" }
netsim-model = { path = "../model" }
rand = "0.8"
tokio = { version = "1.28.2", features = ["full", "tracing"] }
tracing = "0.1"

[dev-dependencies]
daemon = { path = "../daemon" }
