# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[book]
authors = ["Bill Schilit"]
language = "en"
multilingual = false
src = "src"
title = "Wireless Network Simulation with netsim"
