// Copyright 2025 The Android Open Source Project

use bytes::Bytes;
use futures::SinkExt;
use netsim_model::chip::ChipId;
use rootcanal::controller::{Callbacks as ControllerCallbacks, Id};
use rootcanal::types::Phy;
use std::ffi::c_int;
use tokio::sync::mpsc;

/// Callbacks for handling HCI and Link Layer packets from Rootcanal.
pub struct HciCallbacks {
    /// The ID of the chip associated with these callbacks.
    pub id: ChipId,
    /// Channel to send HCI packets to the sink task.
    pub hci_tx: Option<mpsc::Sender<Bytes>>,
    /// Channel to send LL packets (not currently used in this path, usually for sniffer/link bridging).
    pub ll_tx: Option<mpsc::Sender<Bytes>>,
}

impl ControllerCallbacks for HciCallbacks {
    fn send_hci(&self, _source_id: Id, h4_packet: Bytes) {
        if let Some(hci_tx) = self.hci_tx.as_ref() {
            if let Err(e) = hci_tx.try_send(h4_packet) {
                log::error!("Failed to send HCI packet: {e}, dropping.");
            }
        }
    }

    fn on_receive_ll(&self, _source_id: Id, packet: &[u8], _phy: Phy, _tx_power: i32) {
        log::debug!("[{}] Received LL packet", self.id);
        if let Some(ll_tx) = self.ll_tx.as_ref() {
            let packet = Bytes::copy_from_slice(packet);
            if let Err(e) = ll_tx.try_send(packet) {
                log::error!("Failed to send LL packet: {e}, dropping.");
            }
        }
    }

    fn invalid_packet_received(&self, _source_id: Id, reason: c_int, message: &str, _data: &[u8]) {
        log::error!(
            "[chip-{}] Invalid packet received by device: reason={reason}, message={message}",
            self.id
        );
    }
}

/// Runs the task that forwards HCI packets from the callbacks to the packet sink.
/// This task runs in the background and ensures that packets generated by `rootcanal`
/// (via `send_hci`) are sent to the `PacketSink` associated with the chip.
pub async fn sink_loop(
    mut sink: netsim_model::chip::PacketSink,
    mut receiver: tokio::sync::mpsc::Receiver<bytes::Bytes>,
    id: ChipId,
) -> ChipId {
    while let Some(packet) = receiver.recv().await {
        if sink.send(packet).await.is_err() {
            log::info!("Sink for chip {} failed", id);
            break;
        }
    }
    log::info!("Sink task for chip {} finished", id);
    id
}
