[package]
name = "wifi-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = "0.3"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = ["full"] }

actor-framework = { path = "../actor-framework" }
ap-actor = { path = "../ap-actor" }
netsim-model = { path = "../model" }
netsim-packets = { path = "../packets" }
slirp-actor = { path = "../slirp-actor" }

[dev-dependencies]
tempfile = "3"
