# Copyright 2024 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hostapd-rs"
version = "0.1.0"
edition = "2021"
##build = "build_cargo.rs"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
doctest = false

[dependencies]
aes = { version = "0.8.4" }
anyhow = "1"
bytes = { version = "1.4.0" }
ccm = "0.5.0"
log = "0.4.17"
netsim-common = { path = "../common" }
netsim-packets = { path = "../packets" }
pdl-runtime = "0.4.2"
tokio = { version = "1.32.0", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }

[build-dependencies]
##bindgen = "0.69.4"
