# Copyright 2025 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "netsim_ui_files",
    srcs = glob(["dist/**"]),
)
