# Copyright 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0

[package]
name = "modem-main"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "modem_simulator"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
daemonize = "0.5.0"
modem-rs = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
url = "2.5.0"
