[package]
name = "wifi"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
netsim-model = { path = "../model" }
client = { path = "../client" }
log = "0.4"
bytes = "1"
futures = "0.3"
tokio-stream = "0.1"
thiserror = "1"
netsim-packets = { path = "../packets" }
pdl-runtime = "0.4.2"
hostapd-rs = { path = "../hostapd-rs" }
common = { package = "netsim-common", path = "../common" }
zerocopy = { version = "0.8", features = ["derive"] }
netsim-proto = { path = "../proto" }
device-api = { path = "../device-api" }
libslirp-rs = { path = "../libslirp-rs" }
socket2 = { version = "0.5", features = ["all"] }
http-proxy = { path = "../http-proxy" }
async-trait = "0.1"

[features]
cuttlefish = []
